libvisual: LV Namespace Reference
LV Namespace Reference
VisActor | VisAudio | VisBin | VisBuffer | VisColor | VisEvent | VisDFT | VisInput | Libvisual | VisMorph | VisPalette | VisParam | VisPlugin | VisRandom | VisRectangle | VisSongInfo | VisTime | VisVideo
Libvisual namespace.
Classes
class Actor
Actor class.
struct AlignedAllocator
Aligned memory allocator.
struct AlignedAllocator< void, alignment >
class Audio
Multi-channel audio stream class.
class Bin
class Buffer
Reference-counted memory block.
struct Color
class EventQueue
class DFT
Computes a Discrete Fourier Transform.
class Input
class IntrusivePtr
Intrusive smart pointer class template.
class System
class Module
class Morph
Morph class.
struct Palette
Colour palette class for indexed colour modes.
class ParamList
struct PluginRef
class PluginRegistry
Manages the registry of plugins.
class RandomContext
Pseudorandom number generator class.
class Rect
Class describing an axis-aligned rectangle.
class Singleton
Singleton class template.
class SongInfo
Song information class.
class Time
Encodes time.
class Timer
class Video
Canvas class for drawing operations.
Typedefs
typedef LV::IntrusivePtr< Actor > ActorPtr
typedef std::unique_ptr
< AudioChannel > AudioChannelPtr
typedef IntrusivePtr< Buffer > BufferPtr
typedef IntrusivePtr< Buffer
const > BufferConstPtr
typedef VisEvent Event
typedef LV::IntrusivePtr< Input > InputPtr
typedef IntrusivePtr< Module > ModulePtr
typedef LV::IntrusivePtr< Morph > MorphPtr
typedef std::vector< PluginRef > PluginList
typedef ::VisPluginType PluginType
typedef std::minstd_rand Generator
typedef uint32_t RandomSeed
typedef IntrusivePtr< Video > VideoPtr
typedef IntrusivePtr< Video
const > VideoConstPtr
Enumerations
enum SongInfoType { SONG_INFO_TYPE_NULL = ::VISUAL_SONGINFO_TYPE_NULL, SONG_INFO_TYPE_SIMPLE = ::VISUAL_SONGINFO_TYPE_SIMPLE, SONG_INFO_TYPE_ADVANCED = ::VISUAL_SONGINFO_TYPE_ADVANCED }
Functions
void intrusive_ptr_add_ref (Actor const *actor)
void intrusive_ptr_release (Actor const *actor)
template<typename T , typename U , std::size_t alignment>
bool operator== (AlignedAllocator< T, alignment > const &, AlignedAllocator< U, alignment > const &)
template<typename T , typename U , std::size_t alignment>
bool operator!= (AlignedAllocator< T, alignment > const &, AlignedAllocator< U, alignment > const &)
void intrusive_ptr_add_ref (Buffer const *buffer)
void intrusive_ptr_release (Buffer const *buffer)
void intrusive_ptr_add_ref (Input const *input)
void intrusive_ptr_release (Input const *input)
uint32_t rand ()
Drop-in replacement for std::rand() using LV's system-wide random number generator.
template<typename T >
T clamp (T value, T lower, T upper)
void intrusive_ptr_add_ref (Module *module)
void intrusive_ptr_release (Module *module)
void intrusive_ptr_add_ref (Morph const *morph)
void intrusive_ptr_release (Morph const *morph)
const char * plugin_get_next_by_name (PluginList const &list, char const *name)
Retrieves the name of the next plugin in the given list.
const char * plugin_get_prev_by_name (PluginList const &list, char const *name)
Retrieves the name of the previous plugin in the given list.
PluginRef * load_plugin_ref (std::string const &plugin_path)
bool operator== (SongInfo const &lhs, SongInfo const &rhs)
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
bool str_has_suffix (std::string const &str, std::string const &suffix)
Checks if a string has a given suffix.
bool for_each_file_in_dir (std::string const &path, std::function< bool(std::string const &)> filter, std::function< bool(std::string const &)> func)
char const * string_to_c (std::string const &string)
Returns a null-terminated C string from a std::string, or nullptr if string is empty.
void intrusive_ptr_add_ref (Video const *video)
void intrusive_ptr_release (Video const *video)
Detailed Description
Libvisual namespace.
Function Documentation
char const * LV::plugin_get_next_by_name (PluginList const & list, char const * name)
Retrieves the name of the next plugin in the given list.
Parameters
list a list of plugins
name name of plugin to start searching from
Returns
name of the next plugin, or NULL if none can be found
Definition at line 50 of file lv_plugin.cpp.
Referenced by visual_input_get_next_by_name(), and visual_morph_get_next_by_name().
char const * LV::plugin_get_prev_by_name (PluginList const & list, char const * name)
Retrieves the name of the previous plugin in the given list.
Parameters
list a list of plugins
name name of plugin to start searching from
Returns
name of the previous plugin, or NULL if none can be found
Definition at line 64 of file lv_plugin.cpp.
Referenced by visual_input_get_prev_by_name(), and visual_morph_get_prev_by_name().
uint32_t LV::rand () inline
Drop-in replacement for std::rand() using LV's system-wide random number generator.
Returns
a random number
Definition at line 110 of file lv_libvisual.h.
bool LV::str_has_suffix (std::string const & str, std::string const & suffix) inline
Checks if a string has a given suffix.
Parameters
str string to check
suffix suffix to look for
Returns
true if string has the given suffix, false otherwise
Definition at line 26 of file lv_util.hpp.
char const* LV::string_to_c (std::string const & string) inline
Returns a null-terminated C string from a std::string, or nullptr if string is empty.
Parameters
string input string
return C string, or nullptr
Definition at line 46 of file lv_util.hpp.