libvisual: VisAudio
VisAudio
Data Structures
struct _VisAudio
The VisAudio structure contains the sample and extra information about the sample like a 256 bands analyzer, sound energy and in the future BPM detection.
struct _VisAudioSamplePool
struct _VisAudioSamplePoolChannel
struct _VisAudioSample
Defines
#define VISUAL_AUDIO(obj) (VISUAL_CHECK_CAST ((obj), VisAudio))
#define VISUAL_AUDIO_SAMPLEPOOL(obj) (VISUAL_CHECK_CAST ((obj), VisAudioSamplePool))
#define VISUAL_AUDIO_SAMPLEPOOL_CHANNEL(obj) (VISUAL_CHECK_CAST ((obj), VisAudioSamplePoolChannel))
#define VISUAL_AUDIO_SAMPLE(obj) (VISUAL_CHECK_CAST ((obj), VisAudioSample))
#define VISUAL_AUDIO_CHANNEL_LEFT "front left 1"
#define VISUAL_AUDIO_CHANNEL_RIGHT "front right 1"
#define VISUAL_AUDIO_CHANNEL_CATEGORY_FRONT "front"
#define VISUAL_AUDIO_CHANNEL_CATEGORY_REAR "rear"
#define VISUAL_AUDIO_CHANNEL_CATEGORY_RIGHT "left"
#define VISUAL_AUDIO_CHANNEL_CATEGORY_LEFT "right"
Typedefs
typedef struct _VisAudio VisAudio
typedef struct _VisAudioSamplePool VisAudioSamplePool
typedef struct
_VisAudioSamplePoolChannel VisAudioSamplePoolChannel
typedef struct _VisAudioSample VisAudioSample
Enumerations
enum VisAudioSampleRateType {
VISUAL_AUDIO_SAMPLE_RATE_NONE = 0, VISUAL_AUDIO_SAMPLE_RATE_8000, VISUAL_AUDIO_SAMPLE_RATE_11250, VISUAL_AUDIO_SAMPLE_RATE_22500,
VISUAL_AUDIO_SAMPLE_RATE_32000, VISUAL_AUDIO_SAMPLE_RATE_44100, VISUAL_AUDIO_SAMPLE_RATE_48000, VISUAL_AUDIO_SAMPLE_RATE_96000,
VISUAL_AUDIO_SAMPLE_RATE_LAST
}
enum VisAudioSampleFormatType {
VISUAL_AUDIO_SAMPLE_FORMAT_NONE = 0, VISUAL_AUDIO_SAMPLE_FORMAT_U8, VISUAL_AUDIO_SAMPLE_FORMAT_S8, VISUAL_AUDIO_SAMPLE_FORMAT_U16,
VISUAL_AUDIO_SAMPLE_FORMAT_S16, VISUAL_AUDIO_SAMPLE_FORMAT_U32, VISUAL_AUDIO_SAMPLE_FORMAT_S32, VISUAL_AUDIO_SAMPLE_FORMAT_FLOAT,
VISUAL_AUDIO_SAMPLE_FORMAT_LAST
}
enum VisAudioSampleChannelType { VISUAL_AUDIO_SAMPLE_CHANNEL_NONE = 0, VISUAL_AUDIO_SAMPLE_CHANNEL_STEREO }
Functions
VisAudio * visual_audio_new (void)
Creates a new VisAudio structure.
int visual_audio_init (VisAudio *audio)
Initializes a VisAudio, this should not be used to reset a VisAudio.
int visual_audio_analyze (VisAudio *audio)
This function analyzes the VisAudio, the Fourier frequency magic gets done here, also the audio energy is calculated and some other magic to provide the developer more information about the current sample and the stream.
int visual_audio_get_sample (VisAudio *audio, VisBuffer *buffer, const char *channelid)
int visual_audio_get_sample_mixed_simple (VisAudio *audio, VisBuffer *buffer, int channels,...)
int visual_audio_get_sample_mixed (VisAudio *audio, VisBuffer *buffer, int divide, int channels,...)
int visual_audio_get_sample_mixed_category (VisAudio *audio, VisBuffer *buffer, const char *category, int divide)
int visual_audio_get_sample_mixed_all (VisAudio *audio, VisBuffer *buffer, int divide)
int visual_audio_get_spectrum (VisAudio *audio, VisBuffer *buffer, int samplelen, const char *channelid, int normalised)
int visual_audio_get_spectrum_multiplied (VisAudio *audio, VisBuffer *buffer, int samplelen, const char *channelid, int normalised, float multiplier)
int visual_audio_get_spectrum_for_sample (VisBuffer *buffer, VisBuffer *sample, int normalised)
int visual_audio_get_spectrum_for_sample_multiplied (VisBuffer *buffer, VisBuffer *sample, int normalised, float multiplier)
int visual_audio_normalise_spectrum (VisBuffer *buffer)
VisAudioSamplePool * visual_audio_samplepool_new (void)
int visual_audio_samplepool_init (VisAudioSamplePool *samplepool)
int visual_audio_samplepool_add (VisAudioSamplePool *samplepool, VisAudioSample *sample, const char *channelid)
int visual_audio_samplepool_add_channel (VisAudioSamplePool *samplepool, VisAudioSamplePoolChannel *channel)
VisAudioSamplePoolChannel * visual_audio_samplepool_get_channel (VisAudioSamplePool *samplepool, const char *channelid)
int visual_audio_samplepool_flush_old (VisAudioSamplePool *samplepool)
int visual_audio_samplepool_input (VisAudioSamplePool *samplepool, VisBuffer *buffer, VisAudioSampleRateType rate, VisAudioSampleFormatType format, VisAudioSampleChannelType channeltype)
int visual_audio_samplepool_input_channel (VisAudioSamplePool *samplepool, VisBuffer *buffer, VisAudioSampleRateType rate, VisAudioSampleFormatType format, const char *channelid)
VisAudioSamplePoolChannel * visual_audio_samplepool_channel_new (const char *channelid)
int visual_audio_samplepool_channel_init (VisAudioSamplePoolChannel *channel, const char *channelid)
int visual_audio_samplepool_channel_add (VisAudioSamplePoolChannel *channel, VisAudioSample *sample)
int visual_audio_samplepool_channel_flush_old (VisAudioSamplePoolChannel *channel)
int visual_audio_sample_buffer_mix (VisBuffer *dest, VisBuffer *src, int divide, float multiplier)
int visual_audio_sample_buffer_mix_many (VisBuffer *dest, int divide, int channels,...)
VisAudioSample * visual_audio_sample_new (VisBuffer *buffer, VisTime *timestamp, VisAudioSampleFormatType format, VisAudioSampleRateType rate)
int visual_audio_sample_init (VisAudioSample *sample, VisBuffer *buffer, VisTime *timestamp, VisAudioSampleFormatType format, VisAudioSampleRateType rate)
int visual_audio_sample_has_internal (VisAudioSample *sample)
int visual_audio_sample_transform_format (VisAudioSample *dest, VisAudioSample *src, VisAudioSampleFormatType format)
int visual_audio_sample_transform_rate (VisAudioSample *dest, VisAudioSample *src, VisAudioSampleRateType rate)
int visual_audio_sample_rate_get_length (VisAudioSampleRateType rate)
int visual_audio_sample_format_get_size (VisAudioSampleFormatType format)
int visual_audio_sample_format_is_signed (VisAudioSampleFormatType format)
VisBeat * visual_audio_get_beat (VisAudio *audio)
int visual_audio_is_beat (VisAudio *audio, VisBeatAlgorithm algo)
Get the value indicating if we have a beat or not.
int visual_audio_is_beat_with_data (VisAudio *audio, VisBeatAlgorithm algo, unsigned char *data, int size)
int visual_audio_get_cheap_audio_data (VisAudio *audio, unsigned char out[2][2][576])
Define Documentation
#define VISUAL_AUDIO (obj) (VISUAL_CHECK_CAST ((obj), VisAudio))
Definition at line 38 of file lv_audio.h.
#define VISUAL_AUDIO_CHANNEL_CATEGORY_FRONT "front"
Definition at line 46 of file lv_audio.h.
#define VISUAL_AUDIO_CHANNEL_CATEGORY_LEFT "right"
Definition at line 49 of file lv_audio.h.
#define VISUAL_AUDIO_CHANNEL_CATEGORY_REAR "rear"
Definition at line 47 of file lv_audio.h.
#define VISUAL_AUDIO_CHANNEL_CATEGORY_RIGHT "left"
Definition at line 48 of file lv_audio.h.
#define VISUAL_AUDIO_CHANNEL_LEFT "front left 1"
Definition at line 43 of file lv_audio.h.
Referenced by visual_audio_analyze(), visual_audio_get_cheap_audio_data(), and visual_audio_is_beat().
#define VISUAL_AUDIO_CHANNEL_RIGHT "front right 1"
Definition at line 44 of file lv_audio.h.
Referenced by visual_audio_analyze(), and visual_audio_is_beat().
#define VISUAL_AUDIO_SAMPLE (obj) (VISUAL_CHECK_CAST ((obj), VisAudioSample))
Definition at line 41 of file lv_audio.h.
#define VISUAL_AUDIO_SAMPLEPOOL (obj) (VISUAL_CHECK_CAST ((obj), VisAudioSamplePool))
Definition at line 39 of file lv_audio.h.
#define VISUAL_AUDIO_SAMPLEPOOL_CHANNEL (obj) (VISUAL_CHECK_CAST ((obj), VisAudioSamplePoolChannel))
Definition at line 40 of file lv_audio.h.
Typedef Documentation
typedef struct _VisAudio VisAudio
Definition at line 81 of file lv_audio.h.
typedef struct _VisAudioSample VisAudioSample
Definition at line 84 of file lv_audio.h.
typedef struct _VisAudioSamplePool VisAudioSamplePool
Definition at line 82 of file lv_audio.h.
typedef struct _VisAudioSamplePoolChannel VisAudioSamplePoolChannel
Definition at line 83 of file lv_audio.h.
Enumeration Type Documentation
enum VisAudioSampleChannelType
Enumerator:
VISUAL_AUDIO_SAMPLE_CHANNEL_NONE
VISUAL_AUDIO_SAMPLE_CHANNEL_STEREO
Definition at line 75 of file lv_audio.h.
enum VisAudioSampleFormatType
Enumerator:
VISUAL_AUDIO_SAMPLE_FORMAT_NONE
VISUAL_AUDIO_SAMPLE_FORMAT_U8
VISUAL_AUDIO_SAMPLE_FORMAT_S8
VISUAL_AUDIO_SAMPLE_FORMAT_U16
VISUAL_AUDIO_SAMPLE_FORMAT_S16
VISUAL_AUDIO_SAMPLE_FORMAT_U32
VISUAL_AUDIO_SAMPLE_FORMAT_S32
VISUAL_AUDIO_SAMPLE_FORMAT_FLOAT
VISUAL_AUDIO_SAMPLE_FORMAT_LAST
Definition at line 63 of file lv_audio.h.
enum VisAudioSampleRateType
Enumerator:
VISUAL_AUDIO_SAMPLE_RATE_NONE
VISUAL_AUDIO_SAMPLE_RATE_8000
VISUAL_AUDIO_SAMPLE_RATE_11250
VISUAL_AUDIO_SAMPLE_RATE_22500
VISUAL_AUDIO_SAMPLE_RATE_32000
VISUAL_AUDIO_SAMPLE_RATE_44100
VISUAL_AUDIO_SAMPLE_RATE_48000
VISUAL_AUDIO_SAMPLE_RATE_96000
VISUAL_AUDIO_SAMPLE_RATE_LAST
Definition at line 51 of file lv_audio.h.
Function Documentation
int visual_audio_analyze (VisAudio * audio)
This function analyzes the VisAudio, the Fourier frequency magic gets done here, also the audio energy is calculated and some other magic to provide the developer more information about the current sample and the stream.
For every sample that is being retrieved this needs to be called. However keep in mind that the VisBin runs it automaticly.
Parameters:
audio Pointer to a VisAudio that needs to be analyzed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_AUDIO_NULL on failure.
Definition at line 187 of file lv_audio.c.
Referenced by visual_input_run().
VisBeat* visual_audio_get_beat (VisAudio * audio)
Definition at line 1418 of file lv_audio.c.
int visual_audio_get_cheap_audio_data (VisAudio * audio, unsigned char out[2][2][576])
Definition at line 1367 of file lv_audio.c.
int visual_audio_get_sample (VisAudio * audio, VisBuffer * buffer, const char * channelid)
Definition at line 326 of file lv_audio.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), and visual_audio_get_spectrum().
int visual_audio_get_sample_mixed (VisAudio * audio, VisBuffer * buffer, int divide, int channels, ...)
Definition at line 396 of file lv_audio.c.
Referenced by visual_audio_is_beat().
int visual_audio_get_sample_mixed_all (VisAudio * audio, VisBuffer * buffer, int divide)
Definition at line 484 of file lv_audio.c.
int visual_audio_get_sample_mixed_category (VisAudio * audio, VisBuffer * buffer, const char * category, int divide)
Definition at line 448 of file lv_audio.c.
int visual_audio_get_sample_mixed_simple (VisAudio * audio, VisBuffer * buffer, int channels, ...)
Definition at line 348 of file lv_audio.c.
int visual_audio_get_spectrum (VisAudio * audio, VisBuffer * buffer, int samplelen, const char * channelid, int normalised)
Definition at line 516 of file lv_audio.c.
Referenced by visual_audio_get_spectrum_multiplied().
int visual_audio_get_spectrum_for_sample (VisBuffer * buffer, VisBuffer * sample, int normalised)
Definition at line 556 of file lv_audio.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_get_spectrum(), and visual_audio_get_spectrum_for_sample_multiplied().
int visual_audio_get_spectrum_for_sample_multiplied (VisBuffer * buffer, VisBuffer * sample, int normalised, float multiplier)
Definition at line 577 of file lv_audio.c.
int visual_audio_get_spectrum_multiplied (VisAudio * audio, VisBuffer * buffer, int samplelen, const char * channelid, int normalised, float multiplier)
Definition at line 536 of file lv_audio.c.
int visual_audio_init (VisAudio * audio)
Initializes a VisAudio, this should not be used to reset a VisAudio.
The resulting initialized VisAudio is a valid VisObject even if it was not allocated. Keep in mind that VisAudio structures that were created by visual_audio_new() should not be passed to visual_audio_init().
See also:
visual_audio_new
Parameters:
audio Pointer to the VisAudio which needs to be initialized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_AUDIO_NULL on failure.
Definition at line 172 of file lv_audio.c.
Referenced by visual_audio_new().
int visual_audio_is_beat (VisAudio * audio, VisBeatAlgorithm algo)
Get the value indicating if we have a beat or not.
Parameters:
audio The audio from which we want a beat.
Returns:
0 or 1 on success, -VISUAL_ERROR_AUDIO_NULL on failure
Peak algorithm adapted from Winamp's AVS plugin. Adv algorithm adapted from the Blursk plugin for xmms. See lv_beat.h for copyright details.
Definition at line 1537 of file lv_audio.c.
int visual_audio_is_beat_with_data (VisAudio * audio, VisBeatAlgorithm algo, unsigned char * data, int size)
Definition at line 1561 of file lv_audio.c.
Referenced by visual_audio_get_cheap_audio_data(), and visual_audio_is_beat().
VisAudio* visual_audio_new (void)
Creates a new VisAudio structure.
Returns:
A newly allocated VisAudio, or NULL on failure.
Definition at line 155 of file lv_audio.c.
Referenced by visual_input_init().
int visual_audio_normalise_spectrum (VisBuffer * buffer)
Definition at line 596 of file lv_audio.c.
Referenced by visual_audio_get_spectrum_for_sample().
int visual_audio_sample_buffer_mix (VisBuffer * dest, VisBuffer * src, int divide, float multiplier)
Definition at line 826 of file lv_audio.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), and visual_audio_sample_buffer_mix_many().
int visual_audio_sample_buffer_mix_many (VisBuffer * dest, int divide, int channels, ...)
Definition at line 865 of file lv_audio.c.
int visual_audio_sample_format_get_size (VisAudioSampleFormatType format)
Definition at line 1032 of file lv_audio.c.
Referenced by visual_audio_sample_transform_format(), and visual_audio_sample_transform_rate().
int visual_audio_sample_format_is_signed (VisAudioSampleFormatType format)
Definition at line 1051 of file lv_audio.c.
Referenced by visual_audio_sample_transform_format().
int visual_audio_sample_has_internal (VisAudioSample * sample)
Definition at line 939 of file lv_audio.c.
int visual_audio_sample_init (VisAudioSample * sample, VisBuffer * buffer, VisTime * timestamp, VisAudioSampleFormatType format, VisAudioSampleRateType rate)
Definition at line 918 of file lv_audio.c.
Referenced by visual_audio_sample_new().
VisAudioSample* visual_audio_sample_new (VisBuffer * buffer, VisTime * timestamp, VisAudioSampleFormatType format, VisAudioSampleRateType rate)
Definition at line 901 of file lv_audio.c.
Referenced by visual_audio_samplepool_input_channel().
int visual_audio_sample_rate_get_length (VisAudioSampleRateType rate)
Definition at line 1013 of file lv_audio.c.
Referenced by visual_audio_sample_transform_format(), and visual_audio_sample_transform_rate().
int visual_audio_sample_transform_format (VisAudioSample * dest, VisAudioSample * src, VisAudioSampleFormatType format)
Definition at line 949 of file lv_audio.c.
int visual_audio_sample_transform_rate (VisAudioSample * dest, VisAudioSample * src, VisAudioSampleRateType rate)
Definition at line 992 of file lv_audio.c.
int visual_audio_samplepool_add (VisAudioSamplePool * samplepool, VisAudioSample * sample, const char * channelid)
Definition at line 637 of file lv_audio.c.
Referenced by visual_audio_samplepool_input_channel().
int visual_audio_samplepool_add_channel (VisAudioSamplePool * samplepool, VisAudioSamplePoolChannel * channel)
Definition at line 659 of file lv_audio.c.
Referenced by visual_audio_samplepool_add().
int visual_audio_samplepool_channel_add (VisAudioSamplePoolChannel * channel, VisAudioSample * sample)
Definition at line 775 of file lv_audio.c.
Referenced by visual_audio_samplepool_add().
int visual_audio_samplepool_channel_flush_old (VisAudioSamplePoolChannel * channel)
Definition at line 788 of file lv_audio.c.
Referenced by visual_audio_samplepool_flush_old().
int visual_audio_samplepool_channel_init (VisAudioSamplePoolChannel * channel, const char * channelid)
Definition at line 755 of file lv_audio.c.
Referenced by visual_audio_samplepool_channel_new().
VisAudioSamplePoolChannel* visual_audio_samplepool_channel_new (const char * channelid)
Definition at line 740 of file lv_audio.c.
Referenced by visual_audio_samplepool_add().
int visual_audio_samplepool_flush_old (VisAudioSamplePool * samplepool)
Definition at line 685 of file lv_audio.c.
Referenced by visual_audio_analyze().
VisAudioSamplePoolChannel* visual_audio_samplepool_get_channel (VisAudioSamplePool * samplepool, const char * channelid)
Definition at line 669 of file lv_audio.c.
Referenced by visual_audio_analyze(), visual_audio_get_sample(), visual_audio_get_sample_mixed_simple(), and visual_audio_samplepool_add().
int visual_audio_samplepool_init (VisAudioSamplePool * samplepool)
Definition at line 622 of file lv_audio.c.
Referenced by visual_audio_samplepool_new().
int visual_audio_samplepool_input (VisAudioSamplePool * samplepool, VisBuffer * buffer, VisAudioSampleRateType rate, VisAudioSampleFormatType format, VisAudioSampleChannelType channeltype)
Definition at line 699 of file lv_audio.c.
int visual_audio_samplepool_input_channel (VisAudioSamplePool * samplepool, VisBuffer * buffer, VisAudioSampleRateType rate, VisAudioSampleFormatType format, const char * channelid)
Definition at line 713 of file lv_audio.c.
VisAudioSamplePool* visual_audio_samplepool_new (void)
Definition at line 607 of file lv_audio.c.
Referenced by visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), and visual_audio_init().