libvisual: VisPalette
VisPalette
Defines
#define VISUAL_PALETTE(obj) (VISUAL_CHECK_CAST ((obj), VisPalette))
Typedefs
typedef
typedefVISUAL_BEGIN_DECLS
struct _VisPalette VisPalette
Functions
VisPalette * visual_palette_new (unsigned int ncolors)
void visual_palette_free (VisPalette *palette)
VisPalette * visual_palette_clone (VisPalette *self)
void visual_palette_copy (VisPalette *dest, VisPalette *src)
VisColor * visual_palette_get_colors (VisPalette *pal)
VisColor * visual_palette_get_color (VisPalette *pal, int index)
unsigned int visual_palette_get_size (VisPalette *pal)
void visual_palette_blend (VisPalette *dest, VisPalette *src1, VisPalette *src2, float rate)
int visual_palette_find_color (VisPalette *pal, VisColor *color)
Define Documentation
#define VISUAL_PALETTE (obj) (VISUAL_CHECK_CAST ((obj), VisPalette))
Definition at line 106 of file lv_palette.h.
Typedef Documentation
typedef typedefVISUAL_BEGIN_DECLS struct _VisPalette VisPalette
Definition at line 113 of file lv_palette.h.
Function Documentation
void visual_palette_blend (VisPalette * dest, VisPalette * src1, VisPalette * src2, float rate)
Definition at line 84 of file lv_palette_c.cpp.
Referenced by visual_morph_run().
VisPalette* visual_palette_clone (VisPalette * self)
Definition at line 40 of file lv_palette_c.cpp.
Referenced by visual_transform_set_palette(), and visual_video_set_palette().
void visual_palette_copy (VisPalette * dest, VisPalette * src)
Definition at line 45 of file lv_palette_c.cpp.
Referenced by visual_param_entry_set_palette().
int visual_palette_find_color (VisPalette * pal, VisColor * color)
Definition at line 93 of file lv_palette_c.cpp.
Referenced by blit_overlay_colorkey(), and blit_overlay_surfacealphacolorkey().
void visual_palette_free (VisPalette * palette)
Definition at line 35 of file lv_palette_c.cpp.
Referenced by visual_actor_video_negotiate(), visual_transform_set_palette(), and visual_video_set_palette().
VisColor* visual_palette_get_color (VisPalette * pal, int index)
Definition at line 75 of file lv_palette_c.cpp.
VisColor* visual_palette_get_colors (VisPalette * pal)
Definition at line 67 of file lv_palette_c.cpp.
Referenced by visual_bitmap_load(), visual_video_argb32_to_index8(), visual_video_index8_to_argb32(), visual_video_index8_to_rgb16(), visual_video_index8_to_rgb24(), visual_video_rgb16_to_index8(), and visual_video_rgb24_to_index8().
unsigned int visual_palette_get_size (VisPalette * pal)
Definition at line 60 of file lv_palette_c.cpp.
Referenced by visual_video_depth_transform().
VisPalette* visual_palette_new (unsigned int ncolors)
Definition at line 30 of file lv_palette_c.cpp.
Referenced by visual_bitmap_load(), and visual_morph_init().