libvisual: VisMath
VisMath
Defines
#define VISUAL_MATH_PI 3.141592653589793238462643383279502884197169399f
Functions
VISUAL_BEGIN_DECLS int visual_math_is_power_of_2 (int n)
Checks if the given value is a power of 2.
unsigned int visual_math_round_power_of_2 (unsigned int n)
Rounds up to the next highest power of 2.
int visual_math_vectorized_multiplier_floats_const_float (float *dest, const float *src, visual_size_t n, float multiplier)
Multiplies an array of floats with one constant multiplier.
int visual_math_vectorized_add_floats_const_float (float *dest, const float *src, visual_size_t n, float adder)
Adds an array of floats with one constant adder.
int visual_math_vectorized_substract_floats_const_float (float *dest, const float *src, visual_size_t n, float substracter)
Substracts an array of floats with one constant substracter.
int visual_math_vectorized_multiplier_floats_floats (float *dest, const float *src1, const float *src2, visual_size_t n)
int visual_math_vectorized_floats_to_int32s (int32_t *ints, const float *flts, visual_size_t n)
Converts an array of floats to integers.
int visual_math_vectorized_int32s_to_floats (float *flts, const int32_t *ints, visual_size_t n)
Converts an array of integers to floats.
int visual_math_vectorized_floats_to_int32s_multiply (int32_t *ints, const float *flts, visual_size_t n, float multiplier)
Converts an array of floats to integers and multiplies it with a const multiplier.
int visual_math_vectorized_int32s_to_floats_multiply (float *flts, const int32_t *ints, visual_size_t n, float multiplier)
Converts an array of integers to floats and multiplies it with a const multiplier.
int visual_math_vectorized_floats_to_int32s_multiply_denormalise (int32_t *ints, const float *flts, visual_size_t n, float multiplier)
Converts an array of floats to integers and multiplies it with a const multiplier.
int visual_math_vectorized_sqrt_floats (float *dest, const float *src, visual_size_t n)
Vectorized square root for single precision floats.
int visual_math_vectorized_complex_to_norm (float *dest, const float *real, const float *imag, visual_size_t n)
Vectorized complex to norm conversion.
int visual_math_vectorized_complex_to_norm_scale (float *dest, const float *real, const float *imag, visual_size_t n, float scaler)
Vectorized complex to norm conversion and result value scaler.
Define Documentation
#define VISUAL_MATH_PI 3.141592653589793238462643383279502884197169399f
Definition at line 52 of file lv_math.h.
Function Documentation
VISUAL_BEGIN_DECLS int visual_math_is_power_of_2 (int n)
Checks if the given value is a power of 2.
Parameters:
n Value to be checked if it's being a power of 2.
Returns:
TRUE if power of 2, FALSE if not.
Definition at line 38 of file lv_math.c.
Referenced by LV::DFT::Impl::best_method().
unsigned int visual_math_round_power_of_2 (unsigned int n)
Rounds up to the next highest power of 2.
Parameters:
n Value to round up
Returns:
Next highest power of 2
Definition at line 43 of file lv_math.c.
int visual_math_vectorized_add_floats_const_float (float * dest, const float * src, visual_size_t n, float adder)
Adds an array of floats with one constant adder.
The same destination and source arrays are allowed. With the right cpu features in place this function is very optimized.
Parameters:
dest Pointer to the destination float array.
src Pointer to the source float array.
n The number of items in the array.
adder The constant adder that is added to every entry in the source array.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 171 of file lv_math.c.
int visual_math_vectorized_complex_to_norm (float * dest, const float * real, const float * imag, visual_size_t n)
Vectorized complex to norm conversion.
Will make norm values from a real and imaginary array.
Parameters:
dest Pointer to the destination float array.
real Pointer to the real part float array.
imag pointer to the imaginary part float array.
n The number of elements to be converted.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 853 of file lv_math.c.
int visual_math_vectorized_complex_to_norm_scale (float * dest, const float * real, const float * imag, visual_size_t n, float scaler)
Vectorized complex to norm conversion and result value scaler.
Will make norm values from a real and imaginary array, after the conversion has been made it will be multiplied by the scaler.
Parameters:
dest Pointer to the destination float array.
real Pointer to the real part float array.
imag pointer to the imaginary part float array.
n The number of elements to be converted.
scaler The scaler that is used to scale the result value.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 918 of file lv_math.c.
int visual_math_vectorized_floats_to_int32s (int32_t * ints, const float * flts, visual_size_t n)
Converts an array of floats to integers.
With the right cpu features in place this function is very optimized.
Parameters:
ints Pointer to the destination int32_t array.
flts Pointer to the source float array.
n The number of items in the array.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 491 of file lv_math.c.
int visual_math_vectorized_floats_to_int32s_multiply (int32_t * ints, const float * flts, visual_size_t n, float multiplier)
Converts an array of floats to integers and multiplies it with a const multiplier.
With the right cpu features in place this function is very optimized.
Parameters:
ints Pointer to the destination int32_t array.
flts Pointer to the source float array.
n The number of items in the array.
multiplier The constant multiplier with which every entry is multiplied.
Returns:
VISUAL_OK on success or -VISUAL_ERROR_NULL on failure.
Definition at line 602 of file lv_math.c.
int visual_math_vectorized_floats_to_int32s_multiply_denormalise (int32_t * ints, const float * flts, visual_size_t n, float multiplier)
Converts an array of floats to integers and multiplies it with a const multiplier.
Furthermore the float values are denormalized in the following way: -1.0 to 1.0 will be converted to: 0.0 to 1.0. With the right cpu features in place this function is very optimized.
Parameters:
ints Pointer to the destination int32_t array.
flts Pointer to the source float array.
n The number of items in the array.
multiplier The constant multiplier with which every entry is multiplied.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 728 of file lv_math.c.
int visual_math_vectorized_int32s_to_floats (float * flts, const int32_t * ints, visual_size_t n)
Converts an array of integers to floats.
With the right cpu features in place this function is very optimized.
Parameters:
flts Pointer to the destination float array.
ints Pointer to the source int32_t array.
n The number of items in the array.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 547 of file lv_math.c.
int visual_math_vectorized_int32s_to_floats_multiply (float * flts, const int32_t * ints, visual_size_t n, float multiplier)
Converts an array of integers to floats and multiplies it with a const multiplier.
With the right cpu features in place this function is very optimized.
Parameters:
flts Pointer to the destination float array.
ints Pointer to the source int32_t array.
n The number of items in the array.
multiplier The constant multiplier with which every entry is multiplied.
Returns:
VISUAL_OK on success or -VISUAL_ERROR_NULL on failure.
Definition at line 662 of file lv_math.c.
int visual_math_vectorized_multiplier_floats_const_float (float * dest, const float * src, visual_size_t n, float multiplier)
Multiplies an array of floats with one constant multiplier.
The same destination and source arrays are allowed. With the right cpu features in place this function is very optimized.
Parameters:
dest Pointer to the destination float array.
src Pointer to the source float array.
n The number of items in the array.
multiplier The constant multiplier with which every element in the source array is multiplied.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 59 of file lv_math.c.
Referenced by visual_audio_get_spectrum_for_sample_multiplied(), and visual_audio_get_spectrum_multiplied().
int visual_math_vectorized_multiplier_floats_floats (float * dest, const float * src1, const float * src2, visual_size_t n)
Definition at line 394 of file lv_math.c.
int visual_math_vectorized_sqrt_floats (float * dest, const float * src, visual_size_t n)
Vectorized square root for single precision floats.
This function works best with data sizes larger than 16 or equal to 16.
Parameters:
dest The destination vector of floats in which the results are placed.
src The source vector of floats of which the square roots will be calculated.
n The number of floats in the vector.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 799 of file lv_math.c.
int visual_math_vectorized_substract_floats_const_float (float * dest, const float * src, visual_size_t n, float substracter)
Substracts an array of floats with one constant substracter.
The same destination and source arrays are allowed. With the right cpu features in place this function is very optimized.
Parameters:
dest Pointer to the destination float array.
src Pointer to the source float array.
n The number of items in the array.
substracter The constant substracter that is substracter from every entry in the source array.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_NULL on failure.
Definition at line 283 of file lv_math.c.