libvisual: VisInput
VisInput
Data Structures
struct _VisInput
The VisInput structure encapsulates the input plugin and provides abstract interfaces to the input.
struct _VisInputPlugin
The VisInputPlugin structure is the main data structure for the input plugin.
Defines
#define VISUAL_INPUT(obj) (VISUAL_CHECK_CAST ((obj), VisInput))
#define VISUAL_INPUT_PLUGIN(obj) (VISUAL_CHECK_CAST ((obj), VisInputPlugin))
Typedefs
typedef struct _VisInput VisInput
Type defination that should be used in plugins to set the plugin type for an input plugin.
typedef struct _VisInputPlugin VisInputPlugin
typedef int(* VisInputUploadCallbackFunc)(VisInput *input, VisAudio *audio, void *priv)
Callback function that is set using visual_input_set_callback should use this signature.
typedef int(* VisPluginInputUploadFunc)(VisPluginData *plugin, VisAudio *audio)
An input plugin needs this signature for the sample upload function.
Functions
VisPluginData * visual_input_get_plugin (VisInput *input)
Gives the encapsulated VisPluginData from a VisInput.
VisList * visual_input_get_list (void)
Gives a list of input plugins in the current plugin registry.
const char * visual_input_get_next_by_name (const char *name)
Gives the next input plugin based on the name of a plugin.
const char * visual_input_get_prev_by_name (const char *name)
Gives the previous input plugin based on the name of a plugin.
VisInput * visual_input_new (const char *inputname)
Creates a new VisInput from name, the plugin will be loaded but won't be realized.
int visual_input_init (VisInput *input, const char *inputname)
Initializes a VisInput, this will set the allocated flag for the object to FALSE.
int visual_input_realize (VisInput *input)
Realize the VisInput.
int visual_input_set_callback (VisInput *input, VisInputUploadCallbackFunc callback, void *priv)
Sets a callback function for VisInput.
int visual_input_run (VisInput *input)
This is called to run a VisInput.
Define Documentation
#define VISUAL_INPUT (obj) (VISUAL_CHECK_CAST ((obj), VisInput))
Definition at line 39 of file lv_input.h.
#define VISUAL_INPUT_PLUGIN (obj) (VISUAL_CHECK_CAST ((obj), VisInputPlugin))
Definition at line 40 of file lv_input.h.
Typedef Documentation
typedef struct _VisInput VisInput
Type defination that should be used in plugins to set the plugin type for an input plugin.
Definition at line 46 of file lv_input.h.
typedef struct _VisInputPlugin VisInputPlugin
Definition at line 47 of file lv_input.h.
typedef int(* VisInputUploadCallbackFunc)(VisInput *input, VisAudio *audio, void *priv)
Callback function that is set using visual_input_set_callback should use this signature.
See also:
visual_input_set_callback
input Pointer to the VisInput structure.
audio Pointer to the VisAudio containing all the audio information, and in which data needs to be set within the callback.
priv Private field to be used by the client. The library will never touch this.
Definition at line 61 of file lv_input.h.
typedef int(* VisPluginInputUploadFunc)(VisPluginData *plugin, VisAudio *audio)
An input plugin needs this signature for the sample upload function.
The sample upload function is used to retrieve sample information when a input is being used to retrieve the audio sample.
plugin Pointer to the VisPluginData instance structure.
audio Pointer to the VisAudio in which the new sample data is set.
Returns:
0 on succes -1 on error.
Definition at line 75 of file lv_input.h.
Function Documentation
VisList* visual_input_get_list (void)
Gives a list of input plugins in the current plugin registry.
Returns:
An VisList of VisPluginRef's containing the input plugins in the plugin registry.
const char* visual_input_get_next_by_name (const char * name)
Gives the next input plugin based on the name of a plugin.
See also:
visual_input_get_prev_by_name
Parameters:
name The name of the current plugin, or NULL to get the first.
Returns:
The name of the next plugin within the list.
Definition at line 83 of file lv_input.cpp.
VisPluginData* visual_input_get_plugin (VisInput * input)
Gives the encapsulated VisPluginData from a VisInput.
Parameters:
input Pointer of a VisInput of which the VisPluginData needs to be returned.
Returns:
VisPluginData that is encapsulated in the VisInput, possibly NULL.
Definition at line 78 of file lv_input.cpp.
const char* visual_input_get_prev_by_name (const char * name)
Gives the previous input plugin based on the name of a plugin.
See also:
visual_input_get_next_by_name
Parameters:
name The name of the current plugin. or NULL to get the last.
Returns:
The name of the previous plugin within the list.
Definition at line 88 of file lv_input.cpp.
int visual_input_init (VisInput * input, const char * inputname)
Initializes a VisInput, this will set the allocated flag for the object to FALSE.
Should not be used to reset a VisInput, or on a VisInput created by visual_input_new().
See also:
visual_input_new
Parameters:
input Pointer to the VisInput that is initialized.
inputname The name of the plugin to load, or NULL to simply initialize a new input.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_INPUT_NULL or -VISUAL_ERROR_PLUGIN_NO_LIST on failure.
Definition at line 113 of file lv_input.cpp.
Referenced by visual_input_new().
VisInput* visual_input_new (const char * inputname)
Creates a new VisInput from name, the plugin will be loaded but won't be realized.
Parameters:
inputname The name of the plugin to load, or NULL to simply allocate a new input.
Returns:
A newly allocated VisInput, optionally containing a loaded plugin. Or NULL on failure.
Definition at line 93 of file lv_input.cpp.
Referenced by visual_bin_connect_by_names().
int visual_input_realize (VisInput * input)
Realize the VisInput.
This also calls the plugin init function.
Parameters:
input Pointer to a VisInput that needs to be realized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_INPUT_NULL or error values returned by visual_plugin_realize () on failure.
Definition at line 148 of file lv_input.cpp.
Referenced by visual_bin_realize().
int visual_input_run (VisInput * input)
This is called to run a VisInput.
This function will call the plugin to upload it's samples and run it through the visual_audio_analyze function. If a callback is set it will use the callback instead of the plugin.
Parameters:
input A pointer to a VisInput that needs to be runned.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_INPUT_NULL or -VISUAL_ERROR_INPUT_PLUGIN_NULL on failure.
Definition at line 168 of file lv_input.cpp.
Referenced by visual_bin_run().
int visual_input_set_callback (VisInput * input, VisInputUploadCallbackFunc callback, void * priv)
Sets a callback function for VisInput.
Callback functions can be used instead of plugins. Using a callback function you can implement an in app PCM data upload function which is like the upload callback that is used for input plugins.
Parameters:
input Pointer to a VisInput that to which a callback needs to be set.
callback The in app callback function that should be used instead of a plugin.
priv A private that can be read within the callback function.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_INPUT_NULL on failure.
Definition at line 158 of file lv_input.cpp.