libvisual: VisSongInfo
VisSongInfo
Defines
#define VISUAL_SONGINFO(obj) (VISUAL_CHECK_CAST ((obj), VisSongInfo))
Typedefs
typedef struct _VisSongInfo VisSongInfo
Enumerations
enum VisSongInfoType { VISUAL_SONGINFO_TYPE_NULL, VISUAL_SONGINFO_TYPE_SIMPLE, VISUAL_SONGINFO_TYPE_ADVANCED }
Used to define the type of song info being used.
Functions
VisSongInfo * visual_songinfo_new (VisSongInfoType type)
void visual_songinfo_free (VisSongInfo *songinfo)
void visual_songinfo_copy (VisSongInfo *dest, VisSongInfo const *src)
int visual_songinfo_compare (VisSongInfo const *s1, VisSongInfo const *s2)
void visual_songinfo_set_type (VisSongInfo *songinfo, VisSongInfoType type)
VisSongInfoType visual_songinfo_get_type (VisSongInfo *songinfo)
void visual_songinfo_set_length (VisSongInfo *songinfo, int length)
int visual_songinfo_get_length (VisSongInfo *songinfo)
void visual_songinfo_set_elapsed (VisSongInfo *songinfo, int elapsed)
int visual_songinfo_get_elapsed (VisSongInfo *songinfo)
void visual_songinfo_set_simple_name (VisSongInfo *songinfo, const char *name)
const char * visual_songinfo_get_simple_name (VisSongInfo *songinfo)
void visual_songinfo_set_artist (VisSongInfo *songinfo, const char *artist)
const char * visual_songinfo_get_artist (VisSongInfo *songinfo)
void visual_songinfo_set_album (VisSongInfo *songinfo, const char *album)
const char * visual_songinfo_get_album (VisSongInfo *songinfo)
void visual_songinfo_set_song (VisSongInfo *songinfo, const char *song)
const char * visual_songinfo_get_song (VisSongInfo *songinfo)
void visual_songinfo_set_cover (VisSongInfo *songinfo, VisVideo *cover)
VisVideo * visual_songinfo_get_cover (VisSongInfo *songinfo)
void visual_songinfo_mark (VisSongInfo *songinfo)
long visual_songinfo_get_age (VisSongInfo *songinfo)
Define Documentation
#define VISUAL_SONGINFO (obj) (VISUAL_CHECK_CAST ((obj), VisSongInfo))
Definition at line 204 of file lv_songinfo.h.
Typedef Documentation
typedef struct _VisSongInfo VisSongInfo
Definition at line 209 of file lv_songinfo.h.
Enumeration Type Documentation
enum VisSongInfoType
Used to define the type of song info being used.
There are two interfaces to notify libvisual of song information, being a simple and a advanced interface.
Enumerator:
VISUAL_SONGINFO_TYPE_NULL
No song info is given.
VISUAL_SONGINFO_TYPE_SIMPLE
Simple interface only sets a songname.
VISUAL_SONGINFO_TYPE_ADVANCED
Advanced interface splits all the stats in separated entries.
Definition at line 42 of file lv_songinfo.h.
Function Documentation
int visual_songinfo_compare (VisSongInfo const * s1, VisSongInfo const * s2)
Definition at line 143 of file lv_songinfo_c.cpp.
Referenced by visual_actor_run().
void visual_songinfo_copy (VisSongInfo * dest, VisSongInfo const * src)
Definition at line 135 of file lv_songinfo_c.cpp.
Referenced by visual_actor_run().
void visual_songinfo_free (VisSongInfo * songinfo)
Definition at line 12 of file lv_songinfo_c.cpp.
long visual_songinfo_get_age (VisSongInfo * songinfo)
Definition at line 128 of file lv_songinfo_c.cpp.
const char* visual_songinfo_get_album (VisSongInfo * songinfo)
Definition at line 92 of file lv_songinfo_c.cpp.
const char* visual_songinfo_get_artist (VisSongInfo * songinfo)
Definition at line 78 of file lv_songinfo_c.cpp.
VisVideo* visual_songinfo_get_cover (VisSongInfo * songinfo)
int visual_songinfo_get_elapsed (VisSongInfo * songinfo)
Definition at line 52 of file lv_songinfo_c.cpp.
Referenced by visual_actor_run().
int visual_songinfo_get_length (VisSongInfo * songinfo)
Definition at line 38 of file lv_songinfo_c.cpp.
const char* visual_songinfo_get_simple_name (VisSongInfo * songinfo)
Definition at line 64 of file lv_songinfo_c.cpp.
const char* visual_songinfo_get_song (VisSongInfo * songinfo)
Definition at line 106 of file lv_songinfo_c.cpp.
VisSongInfoType visual_songinfo_get_type (VisSongInfo * songinfo)
Definition at line 24 of file lv_songinfo_c.cpp.
void visual_songinfo_mark (VisSongInfo * songinfo)
Definition at line 121 of file lv_songinfo_c.cpp.
Referenced by visual_actor_run().
VisSongInfo* visual_songinfo_new (VisSongInfoType type)
Definition at line 7 of file lv_songinfo_c.cpp.
Referenced by visual_actor_init().
void visual_songinfo_set_album (VisSongInfo * songinfo, const char * album)
Definition at line 85 of file lv_songinfo_c.cpp.
void visual_songinfo_set_artist (VisSongInfo * songinfo, const char * artist)
Definition at line 71 of file lv_songinfo_c.cpp.
void visual_songinfo_set_cover (VisSongInfo * songinfo, VisVideo * cover)
Definition at line 113 of file lv_songinfo_c.cpp.
void visual_songinfo_set_elapsed (VisSongInfo * songinfo, int elapsed)
Definition at line 45 of file lv_songinfo_c.cpp.
void visual_songinfo_set_length (VisSongInfo * songinfo, int length)
Definition at line 31 of file lv_songinfo_c.cpp.
void visual_songinfo_set_simple_name (VisSongInfo * songinfo, const char * name)
Definition at line 57 of file lv_songinfo_c.cpp.
void visual_songinfo_set_song (VisSongInfo * songinfo, const char * song)
Definition at line 99 of file lv_songinfo_c.cpp.
void visual_songinfo_set_type (VisSongInfo * songinfo, VisSongInfoType type)
Definition at line 17 of file lv_songinfo_c.cpp.