libvisual: VisParam
VisParam
Data Structures
struct _VisParamContainer
Parameter container, is the container for a set of parameters.
struct _VisParamEntryCallback
A parameter callback entry, used for change notification callbacks.
struct _VisParamEntry
A parameter entry, used for plugin parameters and such.
Defines
#define VISUAL_PARAMCONTAINER(obj) (VISUAL_CHECK_CAST ((obj), VisParamContainer))
#define VISUAL_PARAMENTRY_CALLBACK(obj) (VISUAL_CHECK_CAST ((obj), VisParamEntryCallback))
#define VISUAL_PARAMENTRY(obj) (VISUAL_CHECK_CAST ((obj), VisParamEntry))
#define VISUAL_PARAM_LIST_ENTRY(name) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_NULL }
#define VISUAL_PARAM_LIST_ENTRY_STRING(name, string) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_STRING , string, {0, 0 , 0 } }
#define VISUAL_PARAM_LIST_ENTRY_INTEGER(name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_INTEGER, 0 , {val, 0 , 0 } }
#define VISUAL_PARAM_LIST_ENTRY_FLOAT(name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_FLOAT , 0 , {0 , val, 0 } }
#define VISUAL_PARAM_LIST_ENTRY_DOUBLE(name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_DOUBLE , 0 , {0 , 0 , val} }
#define VISUAL_PARAM_LIST_ENTRY_COLOR(name, r, g, b) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_COLOR , 0 , {0 , 0 , 0 }, { r, g, b, 255 } }
#define VISUAL_PARAM_LIST_END { {0}, 0, 0, VISUAL_PARAM_ENTRY_TYPE_END }
#define VISUAL_PARAM_CALLBACK_ID_MAX 2147483647
Typedefs
typedef struct _VisParamContainer VisParamContainer
typedef struct
_VisParamEntryCallback VisParamEntryCallback
typedef struct _VisParamEntry VisParamEntry
typedef void(* VisParamChangedCallbackFunc)(VisParamEntry *param, void *priv)
The param changed callback is used to be able to notify of changes within parameters.
Enumerations
enum VisParamEntryType {
VISUAL_PARAM_ENTRY_TYPE_NULL, VISUAL_PARAM_ENTRY_TYPE_STRING, VISUAL_PARAM_ENTRY_TYPE_INTEGER, VISUAL_PARAM_ENTRY_TYPE_FLOAT,
VISUAL_PARAM_ENTRY_TYPE_DOUBLE, VISUAL_PARAM_ENTRY_TYPE_COLOR, VISUAL_PARAM_ENTRY_TYPE_PALETTE, VISUAL_PARAM_ENTRY_TYPE_OBJECT,
VISUAL_PARAM_ENTRY_TYPE_COLLECTION, VISUAL_PARAM_ENTRY_TYPE_END
}
Different types of parameters that can be used.
Functions
VisParamContainer * visual_param_container_new (void)
Creates a new VisParamContainer structure.
int visual_param_container_set_eventqueue (VisParamContainer *paramcontainer, VisEventQueue *eventqueue)
Sets the eventqueue in the VisParamContainer, so events can be emitted on param changes.
VisEventQueue * visual_param_container_get_eventqueue (VisParamContainer *paramcontainer)
Get the pointer to the VisEventQueue the VisParamContainer is emitting events to.
int visual_param_container_add (VisParamContainer *paramcontainer, VisParamEntry *param)
Adds a VisParamEntry to a VisParamContainer.
int visual_param_container_add_with_defaults (VisParamContainer *paramcontainer, VisParamEntry *param)
Adds a VisParamEntry to a VisParamContainer, storing default values in the process.
int visual_param_container_add_many (VisParamContainer *paramcontainer, VisParamEntry *params)
Adds a list of VisParamEntry elements, the list is terminated by an entry of type VISUAL_PARAM_ENTRY_TYPE_END.
int visual_param_container_remove (VisParamContainer *paramcontainer, const char *name)
Removes a VisParamEntry from the VisParamContainer by giving the name of the VisParamEntry that needs to be removed.
int visual_param_container_copy (VisParamContainer *destcont, VisParamContainer *srccont)
Clones the source VisParamContainer into the destination VisParamContainer.
int visual_param_container_copy_match (VisParamContainer *destcont, VisParamContainer *srccont)
Copies matching VisParamEntry elements from srccont into destcont, matching on the name.
VisParamEntry * visual_param_container_get (VisParamContainer *paramcontainer, const char *name)
Retrieve a VisParamEntry from a VisParamContainer by giving the name of the VisParamEntry that is requested.
VisParamEntry * visual_param_entry_new (const char *name)
Creates a new VisParamEntry structure.
int visual_param_entry_add_callback (VisParamEntry *param, VisParamChangedCallbackFunc callback, void *priv)
Adds a change notification callback, this shouldn't be used to get notificated within a plugin, but is for things like VisUI.
int visual_param_entry_remove_callback (VisParamEntry *param, int id)
Removes a change notification callback from the list of callbacks.
int visual_param_entry_notify_callbacks (VisParamEntry *param)
Notifies all the callbacks for the given VisParamEntry parameter.
int visual_param_entry_is (VisParamEntry *param, const char *name)
Checks if the VisParamEntry it's name is the given name.
int visual_param_entry_compare (VisParamEntry *src1, VisParamEntry *src2)
Compares two parameters with each other, When they are the same, TRUE is returned, if not FALSE.
int visual_param_entry_changed (VisParamEntry *param)
When called, emits an event in the VisParamContainer it's VisEventQueue when the VisEventQueue is set.
VisParamEntryType visual_param_entry_get_type (VisParamEntry *param)
Retrieves the VisParamEntryType from a VisParamEntry.
int visual_param_entry_set_from_param (VisParamEntry *param, VisParamEntry *src)
Copies the value of the src param into the param.
int visual_param_entry_set_name (VisParamEntry *param, const char *name)
Set the name for a VisParamEntry.
int visual_param_entry_set_string (VisParamEntry *param, const char *string)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_STRING and assigns the string given as argument to it.
int visual_param_entry_set_integer (VisParamEntry *param, int integer)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_INTEGER and assigns the integer given as argument to it.
int visual_param_entry_set_float (VisParamEntry *param, float floating)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_FLOAT and assigns the float given as argument to it.
int visual_param_entry_set_double (VisParamEntry *param, double doubleflt)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_DOUBLE and assigns the double given as argument to it.
int visual_param_entry_set_color (VisParamEntry *param, uint8_t r, uint8_t g, uint8_t b)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLOR and assigns the rgb values given as arguments to it.
int visual_param_entry_set_color_by_color (VisParamEntry *param, VisColor *color)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLOR and assigns the rgb values from the given VisColor as argument to it.
int visual_param_entry_set_palette (VisParamEntry *param, VisPalette *pal)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_PALETTE and assigns a VisPalette to the VisParamEntry.
int visual_param_entry_set_object (VisParamEntry *param, VisObject *object)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_OBJECT and assigns a VisObject to the VisParamEntry.
int visual_param_entry_set_collection (VisParamEntry *param, VisCollection *collection)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLLECTION and assigns a VisCollection to the VisParamEntry.
int visual_param_entry_set_annotation (VisParamEntry *param, char *anno)
Sets the annotation field of the VisParamEntry to the provided null terminated string.
char * visual_param_entry_get_name (VisParamEntry *param)
Get the name of the VisParamEntry.
char * visual_param_entry_get_string (VisParamEntry *param)
Get the string parameter from a VisParamEntry.
int visual_param_entry_get_integer (VisParamEntry *param)
Get the integer parameter from a VisParamEntry.
float visual_param_entry_get_float (VisParamEntry *param)
Get the float parameter from a VisParamEntry.
double visual_param_entry_get_double (VisParamEntry *param)
Get the double parameter from a VisParamEntry.
VisColor * visual_param_entry_get_color (VisParamEntry *param)
Get the color parameter from a VisParamEntry.
VisPalette * visual_param_entry_get_palette (VisParamEntry *param)
Get the palette parameter from a VisParamEntry.
VisObject * visual_param_entry_get_object (VisParamEntry *param)
Get the object parameter from a VisParamEntry.
VisCollection * visual_param_entry_get_collection (VisParamEntry *param)
Get the collection parameter from a VisParamEntry.
char * visual_param_entry_get_annotation (VisParamEntry *param)
Get the annotation parameter from a VisParamEntry.
int visual_param_entry_min_set_integer (VisParamEntry *param, int integer)
Set the minimum integer parameter for VisParamEntry.
int visual_param_entry_min_set_float (VisParamEntry *param, float floating)
Set the minimum float parameter for VisParamEntry.
int visual_param_entry_min_set_double (VisParamEntry *param, double doubleflt)
Set the minimum double parameter for VisParamEntry.
int visual_param_entry_min_get_integer (VisParamEntry *param)
Get the minimum integer parameter from a VisParamEntry.
float visual_param_entry_min_get_float (VisParamEntry *param)
Get the minimum float parameter from a VisParamEntry.
double visual_param_entry_min_get_double (VisParamEntry *param)
Get the minimum double parameter from a VisParamEntry.
int visual_param_entry_max_set_integer (VisParamEntry *param, int integer)
Set the maxium integer parameter for VisParamEntry.
int visual_param_entry_max_set_float (VisParamEntry *param, float floating)
Set the maxium floating point parameter for VisParamEntry.
int visual_param_entry_max_set_double (VisParamEntry *param, double doubleflt)
Set the maxium double precision parameter for VisParamEntry.
int visual_param_entry_max_get_integer (VisParamEntry *param)
Get the maximum integer parameter from a VisParamEntry.
float visual_param_entry_max_get_float (VisParamEntry *param)
Get the maximum float parameter from a VisParamEntry.
double visual_param_entry_max_get_double (VisParamEntry *param)
Get the maximum double precision parameter from a VisParamEntry.
int visual_param_entry_default_set_string (VisParamEntry *param, char *str)
Set the default string parameter for the VisParamEntry.
int visual_param_entry_default_set_integer (VisParamEntry *param, int integer)
Set the default integer parameter for the VisParamEntry.
int visual_param_entry_default_set_float (VisParamEntry *param, float floating)
Set the default floating point parameter for the VisParamEntry.
int visual_param_entry_default_set_double (VisParamEntry *param, double doubleflt)
Set the default floating point parameter for the VisParamEntry.
int visual_param_entry_default_set_color (VisParamEntry *param, VisColor *color)
Set the default color parameter for the VisParamEntry.
char * visual_param_entry_default_get_string (VisParamEntry *param)
Get the default string parameter from a VisParamEntry.
int visual_param_entry_default_get_integer (VisParamEntry *param)
Get the default integer parameter from a VisParamEntry.
float visual_param_entry_default_get_float (VisParamEntry *param)
Get the default floating point parameter from a VisParamEntry.
double visual_param_entry_default_get_double (VisParamEntry *param)
Get the default double precision parameter from a VisParamEntry.
VisColor * visual_param_entry_default_get_color (VisParamEntry *param)
Get the default VisColor parameter from a VisParamEntry.
Define Documentation
#define VISUAL_PARAM_CALLBACK_ID_MAX 2147483647
Definition at line 54 of file lv_param.h.
#define VISUAL_PARAM_LIST_END { {0}, 0, 0, VISUAL_PARAM_ENTRY_TYPE_END }
Definition at line 52 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY (name) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_NULL }
Definition at line 46 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY_COLOR (name, r, g, b) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_COLOR , 0 , {0 , 0 , 0 }, { r, g, b, 255 } }
Definition at line 51 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY_DOUBLE (name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_DOUBLE , 0 , {0 , 0 , val} }
Definition at line 50 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY_FLOAT (name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_FLOAT , 0 , {0 , val, 0 } }
Definition at line 49 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY_INTEGER (name, val) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_INTEGER, 0 , {val, 0 , 0 } }
Definition at line 48 of file lv_param.h.
#define VISUAL_PARAM_LIST_ENTRY_STRING (name, string) { {0}, 0, name, VISUAL_PARAM_ENTRY_TYPE_STRING , string, {0, 0 , 0 } }
Definition at line 47 of file lv_param.h.
#define VISUAL_PARAMCONTAINER (obj) (VISUAL_CHECK_CAST ((obj), VisParamContainer))
Definition at line 41 of file lv_param.h.
#define VISUAL_PARAMENTRY (obj) (VISUAL_CHECK_CAST ((obj), VisParamEntry))
Definition at line 43 of file lv_param.h.
#define VISUAL_PARAMENTRY_CALLBACK (obj) (VISUAL_CHECK_CAST ((obj), VisParamEntryCallback))
Definition at line 42 of file lv_param.h.
Typedef Documentation
typedef void(* VisParamChangedCallbackFunc)(VisParamEntry *param, void *priv)
The param changed callback is used to be able to notify of changes within parameters.
This should not be used within the plugin itself, instead use the event queue there. This is so it's possible to notify of changes outside the plugin. For example, this is needed by VisUI.
param Pointer to the param that has been changed, and to which the callback was set.
priv Private argument, that can be set when adding the callback to the callback list.
Definition at line 84 of file lv_param.h.
typedef struct _VisParamContainer VisParamContainer
Definition at line 72 of file lv_param.h.
typedef struct _VisParamEntry VisParamEntry
Definition at line 74 of file lv_param.h.
typedef struct _VisParamEntryCallback VisParamEntryCallback
Definition at line 73 of file lv_param.h.
Enumeration Type Documentation
enum VisParamEntryType
Different types of parameters that can be used.
Enumerator:
VISUAL_PARAM_ENTRY_TYPE_NULL
No parameter.
VISUAL_PARAM_ENTRY_TYPE_STRING
String parameter.
VISUAL_PARAM_ENTRY_TYPE_INTEGER
Integer parameter.
VISUAL_PARAM_ENTRY_TYPE_FLOAT
Floating point parameter.
VISUAL_PARAM_ENTRY_TYPE_DOUBLE
Double floating point parameter.
VISUAL_PARAM_ENTRY_TYPE_COLOR
VisColor parameter.
VISUAL_PARAM_ENTRY_TYPE_PALETTE
VisPalette parameter.
VISUAL_PARAM_ENTRY_TYPE_OBJECT
VisObject parameter.
VISUAL_PARAM_ENTRY_TYPE_COLLECTION
VisCollection parameter.
VISUAL_PARAM_ENTRY_TYPE_END
List end, and used as terminator for VisParamEntry lists.
Definition at line 59 of file lv_param.h.
Function Documentation
int visual_param_container_add (VisParamContainer * paramcontainer, VisParamEntry * param)
Adds a VisParamEntry to a VisParamContainer.
Parameters:
paramcontainer A pointer to the VisParamContainer in which the VisParamEntry is added.
param A pointer to the VisParamEntry that is added to the VisParamContainer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL, -VISUAL_ERROR_PARAM_NULL or error values returned by visual_list_add () on failure.
Definition at line 135 of file lv_param.c.
Referenced by visual_param_container_copy().
int visual_param_container_add_many (VisParamContainer * paramcontainer, VisParamEntry * params)
Adds a list of VisParamEntry elements, the list is terminated by an entry of type VISUAL_PARAM_ENTRY_TYPE_END.
All the elements are reallocated, so this function can be used for static param lists.
Parameters:
paramcontainer A pointer to the VisParamContainer in which the VisParamEntry elements are added.
params A pointer to the VisParamEntry elements that are added to the VisParamContainer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL or -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 173 of file lv_param.c.
int visual_param_container_add_with_defaults (VisParamContainer * paramcontainer, VisParamEntry * param)
Adds a VisParamEntry to a VisParamContainer, storing default values in the process.
Parameters:
paramcontainer A pointer to the VisParamContainer in which the VisParamEntry is added.
param A pointer to the VisParamEntry that is added to the VisParamContainer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL, -VISUAL_ERROR_PARAM_NULL or error values returned by visual_list_add () on failure.
Definition at line 149 of file lv_param.c.
Referenced by visual_param_container_add_many().
int visual_param_container_copy (VisParamContainer * destcont, VisParamContainer * srccont)
Clones the source VisParamContainer into the destination VisParamContainer.
When an entry with a certain name already exists in the destination container, it will be overwritten with a new value.
Parameters:
destcont A pointer to the VisParamContainer in which the VisParamEntry values are copied.
srccont A pointer to the VisParamContainer from which the VisParamEntry values are copied.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL, on failure.
Definition at line 213 of file lv_param.c.
int visual_param_container_copy_match (VisParamContainer * destcont, VisParamContainer * srccont)
Copies matching VisParamEntry elements from srccont into destcont, matching on the name.
Parameters:
destcont A pointer to the VisParamContainer in which the VisParamEntry values are copied.
srccont A pointer to the VisParamContainer from which the VisParamEntry values are copied.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL, on failure.
Definition at line 243 of file lv_param.c.
VisParamEntry* visual_param_container_get (VisParamContainer * paramcontainer, const char * name)
Retrieve a VisParamEntry from a VisParamContainer by giving the name of the VisParamEntry that is requested.
Parameters:
paramcontainer A pointer to the VisParamContainer from which a VisParamEntry is requested.
name The name of the VisParamEntry that is requested from the VisParamContainer.
Returns:
Pointer to the VisParamEntry, or NULL.
Definition at line 262 of file lv_param.c.
Referenced by visual_param_container_copy(), and visual_param_container_copy_match().
VisEventQueue* visual_param_container_get_eventqueue (VisParamContainer * paramcontainer)
Get the pointer to the VisEventQueue the VisParamContainer is emitting events to.
Parameters:
paramcontainer A pointer to the VisParamContainer from which the VisEventQueue is requested.
Returns:
Pointer to the VisEventQueue possibly NULL, NULL on failure.
Definition at line 128 of file lv_param.c.
VisParamContainer* visual_param_container_new (void)
Creates a new VisParamContainer structure.
Returns:
A newly allocated VisParamContainer structure.
Definition at line 103 of file lv_param.c.
Referenced by visual_plugin_new().
int visual_param_container_remove (VisParamContainer * paramcontainer, const char * name)
Removes a VisParamEntry from the VisParamContainer by giving the name of the VisParamEntry that needs to be removed.
Parameters:
paramcontainer A pointer to the VisParamContainer from which a VisParamEntry needs to be removed.
name The name of the VisParamEntry that needs to be removed from the VisParamContainer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL, -VISUAL_ERROR_NULL or -VISUAL_ERROR_PARAM_NOT_FOUND on failure.
Definition at line 193 of file lv_param.c.
int visual_param_container_set_eventqueue (VisParamContainer * paramcontainer, VisEventQueue * eventqueue)
Sets the eventqueue in the VisParamContainer, so events can be emitted on param changes.
Parameters:
paramcontainer A pointer to the VisParamContainer to which the VisEventQueue needs to be set.
eventqueue A Pointer to the VisEventQueue that is used for the events the VisParamContainer can emit.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_CONTAINER_NULL on failure.
Definition at line 119 of file lv_param.c.
Referenced by visual_plugin_realize(), and visual_plugin_unload().
int visual_param_entry_add_callback (VisParamEntry * param, VisParamChangedCallbackFunc callback, void * priv)
Adds a change notification callback, this shouldn't be used to get notificated within a plugin, but is for things like VisUI.
Parameters:
param Pointer to the VisParamEntry to which a change notification callback is added.
callback The notification callback, which is called on changes in the VisParamEntry.
priv A private that can be used in the callback function.
return callback id in the form of a positive value on success, -VISUAL_ERROR_PARAM_NULL, -VISUAL_ERROR_PARAM_CALLBACK_NULL or -VISUAL_ERROR_PARAM_CALLBACK_TOO_MANY on failure.
Definition at line 296 of file lv_param.c.
int visual_param_entry_changed (VisParamEntry * param)
When called, emits an event in the VisParamContainer it's VisEventQueue when the VisEventQueue is set.
Parameters:
param Pointer to the VisParamEntry that is changed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 367 of file lv_param.c.
Referenced by visual_param_container_add(), visual_param_container_add_with_defaults(), visual_param_entry_set_color(), visual_param_entry_set_color_by_color(), visual_param_entry_set_double(), visual_param_entry_set_float(), visual_param_entry_set_integer(), visual_param_entry_set_object(), visual_param_entry_set_palette(), and visual_param_entry_set_string().
int visual_param_entry_compare (VisParamEntry * src1, VisParamEntry * src2)
Compares two parameters with each other, When they are the same, TRUE is returned, if not FALSE.
Keep in mind that FALSE is always returned for VISUAL_PARAM_ENTRY_TYPE_PALETTE and VISUAL_PARAM_ENTRY_TYPE_OBJECT.
Parameters:
src1 Pointer to the first VisParamEntry for comparison.
src2 Pointer to the second VisParamEntry for comparison.
Returns:
TRUE if the same, FALSE if not the same, -VISUAL_ERROR_PARAM_NULL, -VISUAL_ERROR_PARAM_INVALID_TYPE or -VISUAL_ERROR_IMPOSSIBLE on failure.
Definition at line 393 of file lv_param.c.
VisColor* visual_param_entry_default_get_color (VisParamEntry * param)
Get the default VisColor parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the default VisColor parameter from the VisParamEntry.
Definition at line 975 of file lv_param.c.
double visual_param_entry_default_get_double (VisParamEntry * param)
Get the default double precision parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the default double precision parameter from the VisParamEntry.
Definition at line 969 of file lv_param.c.
float visual_param_entry_default_get_float (VisParamEntry * param)
Get the default floating point parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the default floating point parameter from the VisParamEntry.
Definition at line 963 of file lv_param.c.
int visual_param_entry_default_get_integer (VisParamEntry * param)
Get the default integer parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the default integer parameter from the VisParamEntry.
Definition at line 957 of file lv_param.c.
char* visual_param_entry_default_get_string (VisParamEntry * param)
Get the default string parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the default string parameter from the VisParamEntry.
Definition at line 951 of file lv_param.c.
int visual_param_entry_default_set_color (VisParamEntry * param, VisColor * color)
Set the default color parameter for the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 944 of file lv_param.c.
int visual_param_entry_default_set_double (VisParamEntry * param, double doubleflt)
Set the default floating point parameter for the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 937 of file lv_param.c.
int visual_param_entry_default_set_float (VisParamEntry * param, float floating)
Set the default floating point parameter for the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 930 of file lv_param.c.
int visual_param_entry_default_set_integer (VisParamEntry * param, int integer)
Set the default integer parameter for the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 923 of file lv_param.c.
int visual_param_entry_default_set_string (VisParamEntry * param, char * str)
Set the default string parameter for the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 911 of file lv_param.c.
char* visual_param_entry_get_annotation (VisParamEntry * param)
Get the annotation parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the annotation parameter is requested.
Returns:
Pointer to the annotation string parameter from the VisParamEntry.
Definition at line 799 of file lv_param.c.
VisCollection* visual_param_entry_get_collection (VisParamEntry * param)
Get the collection parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the collection parameter is requested.
Returns:
Pointer to the VisCollection parameter from the VisParamEntry.
Definition at line 787 of file lv_param.c.
VisColor* visual_param_entry_get_color (VisParamEntry * param)
Get the color parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the color parameter is requested.
Returns:
Pointer to the VisColor parameter from the VisParamEntry. It's adviced to use the VisColor that is returned as read only seen changing it directly won't emit events and can cause synchronous problems between the plugin and the parameter system. Instead use the visual_param_entry_set_color* methods to change the parameter value.
Definition at line 748 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
double visual_param_entry_get_double (VisParamEntry * param)
Get the double parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the double parameter is requested.
Returns:
The double parameter from the VisParamEntry.
Definition at line 738 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
float visual_param_entry_get_float (VisParamEntry * param)
Get the float parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the float parameter is requested.
Returns:
The float parameter from the VisParamEntry.
Definition at line 728 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_get_integer (VisParamEntry * param)
Get the integer parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the integer parameter is requested.
Returns:
The integer parameter from the VisParamEntry.
Definition at line 718 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
char* visual_param_entry_get_name (VisParamEntry * param)
Get the name of the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the name is requested.
Returns:
The name of the VisParamEntry or NULL.
Definition at line 698 of file lv_param.c.
Referenced by visual_param_container_add_many(), visual_param_container_copy(), and visual_param_container_copy_match().
VisObject* visual_param_entry_get_object (VisParamEntry * param)
Get the object parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the object parameter is requested.
Returns:
Pointer to the VisObject parameter from the VisParamEntry.
Definition at line 774 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
VisPalette* visual_param_entry_get_palette (VisParamEntry * param)
Get the palette parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the palette parameter is requested.
Returns:
Pointer to the VisPalette parameter from the VisParamEntry. The returned VisPalette should be exclusively used as read only.
Definition at line 761 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
char* visual_param_entry_get_string (VisParamEntry * param)
Get the string parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the string parameter is requested.
Returns:
The string parameter from the VisParamEntry or NULL.
Definition at line 705 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
VisParamEntryType visual_param_entry_get_type (VisParamEntry * param)
Retrieves the VisParamEntryType from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the VisParamEntryType is requested.
Returns:
The VisParamEntryType on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 386 of file lv_param.c.
int visual_param_entry_is (VisParamEntry * param, const char * name)
Checks if the VisParamEntry it's name is the given name.
Parameters:
param Pointer to the VisParamEntry of which we want to check the name.
name The name we want to check against.
Returns:
TRUE if the VisParamEntry is the one we requested, or FALSE if not.
Definition at line 357 of file lv_param.c.
double visual_param_entry_max_get_double (VisParamEntry * param)
Get the maximum double precision parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the maxiumum double precision parameter from the VisParamEntry.
Definition at line 903 of file lv_param.c.
float visual_param_entry_max_get_float (VisParamEntry * param)
Get the maximum float parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the maximum floating point parameter from the VisParamEntry.
Definition at line 895 of file lv_param.c.
int visual_param_entry_max_get_integer (VisParamEntry * param)
Get the maximum integer parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the maximum integer parameter from the VisParamEntry.
Definition at line 887 of file lv_param.c.
int visual_param_entry_max_set_double (VisParamEntry * param, double doubleflt)
Set the maxium double precision parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 878 of file lv_param.c.
int visual_param_entry_max_set_float (VisParamEntry * param, float floating)
Set the maxium floating point parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 868 of file lv_param.c.
int visual_param_entry_max_set_integer (VisParamEntry * param, int integer)
Set the maxium integer parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 858 of file lv_param.c.
double visual_param_entry_min_get_double (VisParamEntry * param)
Get the minimum double parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the minimum double parameter from the VisParamEntry.
Definition at line 850 of file lv_param.c.
float visual_param_entry_min_get_float (VisParamEntry * param)
Get the minimum float parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the minimum float parameter from the VisParamEntry.
Definition at line 842 of file lv_param.c.
int visual_param_entry_min_get_integer (VisParamEntry * param)
Get the minimum integer parameter from a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
Pointer to the minimum integer parameter from the VisParamEntry.
Definition at line 834 of file lv_param.c.
int visual_param_entry_min_set_double (VisParamEntry * param, double doubleflt)
Set the minimum double parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 824 of file lv_param.c.
int visual_param_entry_min_set_float (VisParamEntry * param, float floating)
Set the minimum float parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 815 of file lv_param.c.
int visual_param_entry_min_set_integer (VisParamEntry * param, int integer)
Set the minimum integer parameter for VisParamEntry.
Parameters:
param Pointer to the VisParamEntry from which the parameter is requested.
Returns:
VISUAL_OK on sucess, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 806 of file lv_param.c.
VisParamEntry* visual_param_entry_new (const char * name)
Creates a new VisParamEntry structure.
Parameters:
name The name that is assigned to the VisParamEntry.
Returns:
A newly allocated VisParamEntry structure.
Definition at line 280 of file lv_param.c.
Referenced by visual_param_container_add_many(), and visual_param_container_copy().
int visual_param_entry_notify_callbacks (VisParamEntry * param)
Notifies all the callbacks for the given VisParamEntry parameter.
Parameters:
param Pointer to the VisParamEntry of which all the change notification callbacks need to be called.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 344 of file lv_param.c.
Referenced by visual_param_entry_changed().
int visual_param_entry_remove_callback (VisParamEntry * param, int id)
Removes a change notification callback from the list of callbacks.
Parameters:
param Pointer to the VisParamEntry from which a change notification callback is removed.
id The callback ID that was given by the visual_param_entry_add_callback method.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 323 of file lv_param.c.
int visual_param_entry_set_annotation (VisParamEntry * param, char * anno)
Sets the annotation field of the VisParamEntry to the provided null terminated string.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
anno A null terminated string which to assign to the VisParamEntry's annotation field.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL or -VISUAL_ERROR_PARAM_ANNO_NULL on failure.
Definition at line 684 of file lv_param.c.
int visual_param_entry_set_collection (VisParamEntry * param, VisCollection * collection)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLLECTION and assigns a VisCollection to the VisParamEntry.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
object Pointer to the VisObject that is linked to the VisParamEntry.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 667 of file lv_param.c.
int visual_param_entry_set_color (VisParamEntry * param, uint8_t r, uint8_t g, uint8_t b)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLOR and assigns the rgb values given as arguments to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
r The red value for this color parameter.
g The green value for this color parameter.
b The blue value for this color parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 603 of file lv_param.c.
int visual_param_entry_set_color_by_color (VisParamEntry * param, VisColor * color)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_COLOR and assigns the rgb values from the given VisColor as argument to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
color Pointer to the VisColor from which the rgb values are copied into the parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 618 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_double (VisParamEntry * param, double doubleflt)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_DOUBLE and assigns the double given as argument to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
doubleflt The double value for this parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 588 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_float (VisParamEntry * param, float floating)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_FLOAT and assigns the float given as argument to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
floating The float value for this parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 573 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_from_param (VisParamEntry * param, VisParamEntry * src)
Copies the value of the src param into the param.
Also sets the param to the type of which the source param is.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
src Pointer to the VisParamEntry from which the value is retrieved.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL, -VISUAL_ERROR_PARAM_INVALID_TYPE on failure.
Definition at line 457 of file lv_param.c.
Referenced by visual_param_container_add_many(), visual_param_container_copy(), and visual_param_container_copy_match().
int visual_param_entry_set_integer (VisParamEntry * param, int integer)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_INTEGER and assigns the integer given as argument to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
integer The integer value for this parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 558 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_name (VisParamEntry * param, const char * name)
Set the name for a VisParamEntry.
Parameters:
param Pointer to the VisParamEntry to which the name is set.
name The name that is set to the VisParamEntry.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 512 of file lv_param.c.
Referenced by visual_param_entry_new().
int visual_param_entry_set_object (VisParamEntry * param, VisObject * object)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_OBJECT and assigns a VisObject to the VisParamEntry.
With a VisObject VisParamEntry, the VisObject is referenced, not cloned.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
object Pointer to the VisObject that is linked to the VisParamEntry.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 648 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_palette (VisParamEntry * param, VisPalette * pal)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_PALETTE and assigns a VisPalette to the VisParamEntry.
This function does not check if there is a difference between the prior set palette and the new one, and always emits the changed event. so watch out with usage.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
pal Pointer to the VisPalette from which the palette data is retrieved for the VisParamEntry.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 633 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().
int visual_param_entry_set_string (VisParamEntry * param, const char * string)
Sets the VisParamEntry to VISUAL_PARAM_ENTRY_TYPE_STRING and assigns the string given as argument to it.
Parameters:
param Pointer to the VisParamEntry to which a parameter is set.
string The string for this parameter.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PARAM_NULL on failure.
Definition at line 527 of file lv_param.c.
Referenced by visual_param_entry_set_from_param().