libvisual: VisBuffer
VisBuffer
Data Structures
struct _VisBuffer
The VisBuffer data structure holding a buffer and information regarding the buffer.
Defines
#define VISUAL_BUFFER(obj) (VISUAL_CHECK_CAST ((obj), VisBuffer))
Typedefs
typedef struct _VisBuffer VisBuffer
typedef void(* VisBufferDestroyerFunc)(VisBuffer *buffer)
A VisBuffer destroyer function needs this signature.
Functions
VisBuffer * visual_buffer_new (void)
Creates a new VisBuffer.
int visual_buffer_init (VisBuffer *buffer, void *data, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Initializes a VisBuffer, it's safe to use visual_buffer_set_data_pair on a non heap allocated VisBuffer, however do not unref it when you're using this method.
VisBuffer * visual_buffer_new_with_buffer (void *data, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Creates a new VisBuffer with data, datasize and destroyer set.
VisBuffer * visual_buffer_new_allocate (visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Creates a new VisBuffer, allocates data, sets the destroyer.
int visual_buffer_init_allocate (VisBuffer *buffer, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Initializes a VisBuffer and allocates the data, it's safe to use visual_buffer_set_data_pair on a non heap allocated VisBuffer, however do not unref it when you're using this method.
int visual_buffer_destroy_content (VisBuffer *buffer)
Destroys the content of a VisBuffer using the VisBufferDestroyerFunc that is set to the VisBuffer.
int visual_buffer_set_destroyer (VisBuffer *buffer, VisBufferDestroyerFunc destroyer)
Sets the destroyer function for the content of a VisBuffer.
VisBufferDestroyerFunc visual_buffer_get_destroyer (VisBuffer *buffer)
Retrieves the destroyer function that is set to a VisBuffer.
int visual_buffer_set_data_pair (VisBuffer *buffer, void *data, visual_size_t datasize)
Sets the data pair (data and it's size) to a VisBuffer.
int visual_buffer_set_size (VisBuffer *buffer, visual_size_t datasize)
Sets the size of the data to a VisBuffer.
int visual_buffer_set_data (VisBuffer *buffer, void *data)
Sets the data to a VisBuffer.
int visual_buffer_allocate_data (VisBuffer *buffer)
Allocates the data for a VisBuffer, the amount of bytes allocated is defined by the data size that is set to the VisBuffer.
void * visual_buffer_get_data (VisBuffer *buffer)
Gets pointer to the data that is encapsulated by the VisBuffer.
void * visual_buffer_get_data_offset (VisBuffer *buffer, int byteoffset)
Gets pointer to the data that is encapsulated by the VisBuffer using an offset.
visual_size_t visual_buffer_get_size (VisBuffer *buffer)
Gets the size in bytes of a VisBuffer.
int visual_buffer_get_allocated (VisBuffer *buffer)
Return if the internal buffer is flagged as allocated or not.
int visual_buffer_clone (VisBuffer *dest, VisBuffer *src)
Clones a VisBuffer, this will copy the data.
VisBuffer * visual_buffer_clone_new (VisBuffer *src)
Clones a VisBuffer in the form of a newly allocated structure, this will copy the data.
int visual_buffer_copy_data_to (VisBuffer *src, void *dest)
Copies all the data contained by the VisBuffer into dest.
int visual_buffer_put (VisBuffer *dest, VisBuffer *src, int byteoffset)
Copies data into the VisBuffer from another VisBuffer starting at byteoffset.
int visual_buffer_put_data (VisBuffer *dest, void *data, visual_size_t size, int byteoffset)
Copies data into the VisBuffer using a data pointer and it's size.
int visual_buffer_put_atomic (VisBuffer *dest, VisBuffer *src, int byteoffset)
Copies data into the VisBuffer from another VisBuffer starting at byteoffset.
int visual_buffer_put_data_atomic (VisBuffer *dest, void *data, visual_size_t size, int byteoffset)
Copies data into the VisBuffer using a data pointer and it's size.
int visual_buffer_append (VisBuffer *dest, VisBuffer *src)
Appends a VisBuffer to a VisBuffer, this will also reallocate the buffer so it's big enough.
int visual_buffer_append_data (VisBuffer *dest, void *data, visual_size_t size)
Appends data to a VisBuffer, this will also reallocate the buffer so it's big enough.
int visual_buffer_fill (VisBuffer *buffer, char value)
Fills the buffer with a value (byte wise).
int visual_buffer_fill_with_pattern (VisBuffer *buffer, void *data, visual_size_t size)
Fills the buffer with a pattern of data.
void visual_buffer_destroyer_free (VisBuffer *buffer)
A standard destroyer that can be set on VisBuffers.
Define Documentation
#define VISUAL_BUFFER (obj) (VISUAL_CHECK_CAST ((obj), VisBuffer))
Definition at line 36 of file lv_buffer.h.
Typedef Documentation
typedef struct _VisBuffer VisBuffer
Definition at line 38 of file lv_buffer.h.
typedef void(* VisBufferDestroyerFunc)(VisBuffer *buffer)
A VisBuffer destroyer function needs this signature.
It can be used to destroy the content of a VisBuffer on a unref.
buffer The VisBuffer data structure.
Definition at line 46 of file lv_buffer.h.
Function Documentation
int visual_buffer_allocate_data (VisBuffer * buffer)
Allocates the data for a VisBuffer, the amount of bytes allocated is defined by the data size that is set to the VisBuffer.
Parameters:
buffer Pointer to the VisBuffer for which the data is allocated.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 167 of file lv_buffer.c.
Referenced by visual_buffer_clone(), visual_buffer_init_allocate(), visual_buffer_new_allocate(), and visual_video_allocate_buffer().
int visual_buffer_append (VisBuffer * dest, VisBuffer * src)
Appends a VisBuffer to a VisBuffer, this will also reallocate the buffer so it's big enough.
Parameters:
dest Pointer to the VisBuffer to which the other VisBuffer is appended.
src Pointer to the VisBuffer that is appended.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 293 of file lv_buffer.c.
int visual_buffer_append_data (VisBuffer * dest, void * data, visual_size_t size)
Appends data to a VisBuffer, this will also reallocate the buffer so it's big enough.
Parameters:
dest Pointer to the VisBufer to which the data is appended.
data Pointer to the data that is appended.
size The size in bytes of the data that is appended to the VisBuffer
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 303 of file lv_buffer.c.
int visual_buffer_clone (VisBuffer * dest, VisBuffer * src)
Clones a VisBuffer, this will copy the data.
Parameters:
dest Pointer to the destination VisBuffer.
src Pointer to the source VisBuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 207 of file lv_buffer.c.
Referenced by visual_audio_samplepool_input_channel(), and visual_buffer_clone_new().
VisBuffer* visual_buffer_clone_new (VisBuffer * src)
Clones a VisBuffer in the form of a newly allocated structure, this will copy the data.
Parameters:
src Pointer to the source VisBuffer.
Returns:
Newly allocated cloned VisBuffer on success, NULL on failure.
Definition at line 226 of file lv_buffer.c.
int visual_buffer_copy_data_to (VisBuffer * src, void * dest)
Copies all the data contained by the VisBuffer into dest.
Parameters:
src Pointer to the VisBuffer which contains the source data.
dest Pointer to the buffer in which all the data is copied.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 239 of file lv_buffer.c.
int visual_buffer_destroy_content (VisBuffer * buffer)
Destroys the content of a VisBuffer using the VisBufferDestroyerFunc that is set to the VisBuffer.
Parameters:
buffer Pointer to the VisBuffer of which the content is destroyed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 109 of file lv_buffer.c.
Referenced by visual_video_free_buffer().
void visual_buffer_destroyer_free (VisBuffer * buffer)
A standard destroyer that can be set on VisBuffers.
This destroyer simply frees the memory that is allocated.
Parameters:
buffer Pointer to the VisBuffer that owns the memory that needs to be freed.
Definition at line 338 of file lv_buffer.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), visual_audio_get_spectrum(), visual_audio_sample_transform_format(), visual_audio_sample_transform_rate(), visual_audio_samplepool_input_channel(), and visual_video_allocate_buffer().
int visual_buffer_fill (VisBuffer * buffer, char value)
Fills the buffer with a value (byte wise).
Parameters:
buffer Pointer to the VisBuffer which is to be filled with one byte value.
value The value that is used to fill the buffer with.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 313 of file lv_buffer.c.
Referenced by visual_audio_get_sample(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_simple(), visual_audio_get_spectrum(), and visual_audio_sample_buffer_mix_many().
int visual_buffer_fill_with_pattern (VisBuffer * buffer, void * data, visual_size_t size)
Fills the buffer with a pattern of data.
This can be used to fill a buffer with a structure, floats whatever. It's assumed that the buffer is rightly allocated, when this is not the case it can happen that only a part of the pattern is copied.
Parameters:
buffer Pointer to the VisBuffer which is to be filled with a pattern.
data The data pattern.
size The size of the pattern
Definition at line 322 of file lv_buffer.c.
int visual_buffer_get_allocated (VisBuffer * buffer)
Return if the internal buffer is flagged as allocated or not.
Parameters:
buffer Pointer to the VisBuffer of which the allocated flag is requested.
Returns:
TRUE or FALSE depending on the allocated flag on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 200 of file lv_buffer.c.
Referenced by visual_video_allocate_buffer(), visual_video_free_buffer(), visual_video_have_allocated_buffer(), and visual_video_set_buffer().
void* visual_buffer_get_data (VisBuffer * buffer)
Gets pointer to the data that is encapsulated by the VisBuffer.
Parameters:
buffer Pointer to the VisBuffer of which the data is requested.
Returns:
Pointer to the data on success, NULL on failure.
Definition at line 179 of file lv_buffer.c.
Referenced by visual_audio_get_spectrum_for_sample(), visual_audio_get_spectrum_for_sample_multiplied(), visual_audio_get_spectrum_multiplied(), visual_audio_normalise_spectrum(), visual_audio_sample_buffer_mix(), visual_buffer_clone(), visual_ringbuffer_get_data_offset(), visual_video_get_pixels(), and visual_video_set_buffer().
void* visual_buffer_get_data_offset (VisBuffer * buffer, int byteoffset)
Gets pointer to the data that is encapsulated by the VisBuffer using an offset.
Parameters:
buffer Pointer to the VisBuffer of which the data is requested.
byteoffset The offset in N bytes.
Returns:
Pointer to the data on success, NULL on failure.
Definition at line 186 of file lv_buffer.c.
VisBufferDestroyerFunc visual_buffer_get_destroyer (VisBuffer * buffer)
Retrieves the destroyer function that is set to a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer of which the destroyer function is requested.
Returns:
Pointer to the destroyer function, or NULL on failure.
Definition at line 130 of file lv_buffer.c.
Referenced by visual_buffer_clone().
visual_size_t visual_buffer_get_size (VisBuffer * buffer)
Gets the size in bytes of a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer of which the size is requested.
Returns:
Size in bytes on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 193 of file lv_buffer.c.
Referenced by visual_audio_get_sample(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), visual_audio_get_spectrum_for_sample(), visual_audio_get_spectrum_for_sample_multiplied(), visual_audio_get_spectrum_multiplied(), visual_audio_normalise_spectrum(), visual_audio_sample_buffer_mix(), visual_buffer_clone(), visual_buffer_put_data(), visual_ringbuffer_get_data_offset(), and visual_ringbuffer_get_size().
int visual_buffer_init (VisBuffer * buffer, void * data, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Initializes a VisBuffer, it's safe to use visual_buffer_set_data_pair on a non heap allocated VisBuffer, however do not unref it when you're using this method.
The reason to do this can be performance because the VisObject initialization is skipped. Be very careful with this and only do it when you know what you're doing.
See also:
visual_buffer_new
Parameters:
buffer Pointer to the VisBuffer that is to be initialized.
data The which the VisBuffer encapsulates.
datasize The size of the data (in bytes).
destroyer The destroyer that is to be used on the data when the buffer is destroyed or the refcount reaches 0.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 57 of file lv_buffer.c.
Referenced by visual_audio_analyze(), visual_buffer_init_allocate(), visual_buffer_new(), and visual_ringbuffer_get_data_offset().
int visual_buffer_init_allocate (VisBuffer * buffer, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Initializes a VisBuffer and allocates the data, it's safe to use visual_buffer_set_data_pair on a non heap allocated VisBuffer, however do not unref it when you're using this method.
The reason to do this can be performance because the VisObject initialization is skipped. Be very careful with this and only do it when you know what you're doing.
See also:
visual_buffer_new_allocate
Parameters:
buffer Pointer to the VisBuffer that is to be initialized.
datasize The size of the data (in bytes).
destroyer The destroyer that is to be used on the data when the buffer is destroyed or the refcount reaches 0.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 96 of file lv_buffer.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), and visual_audio_get_spectrum().
VisBuffer* visual_buffer_new (void)
Creates a new VisBuffer.
A VisBuffer encapsulates a memory buffer and it's size, it's also a VisObject so it can be referenced.
Returns:
A newly allocated VisBuffer.
Definition at line 42 of file lv_buffer.c.
Referenced by visual_audio_samplepool_input_channel(), visual_buffer_clone_new(), visual_buffer_new_allocate(), visual_buffer_new_with_buffer(), and visual_video_init().
VisBuffer* visual_buffer_new_allocate (visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Creates a new VisBuffer, allocates data, sets the destroyer.
Parameters:
datasize The size of the data requested (in bytes).
destroyer The destroyer that is to be used on the data when the buffer is destroyed or the refcount reaches 0.
Returns:
A newly allocated VisBuffer.
Definition at line 85 of file lv_buffer.c.
Referenced by visual_audio_sample_transform_format(), visual_audio_sample_transform_rate(), visual_ringbuffer_get_data_new(), and visual_ringbuffer_get_data_new_without_wrap().
VisBuffer* visual_buffer_new_with_buffer (void * data, visual_size_t datasize, VisBufferDestroyerFunc destroyer)
Creates a new VisBuffer with data, datasize and destroyer set.
Parameters:
data The which the VisBuffer encapsulates.
datasize The size of the data (in bytes).
destroyer The destroyer that is to be used on the data when the buffer is destroyed or the refcount reaches 0.
Returns:
A newly allocated VisBuffer.
Definition at line 75 of file lv_buffer.c.
Referenced by visual_ringbuffer_add_buffer_by_data().
int visual_buffer_put (VisBuffer * dest, VisBuffer * src, int byteoffset)
Copies data into the VisBuffer from another VisBuffer starting at byteoffset.
The copy is NOT atomic.
Parameters:
dest Pointer to the destination VisBuffer.
src Pointer to the source VisBuffer.
byteoffset The offset in the destination VisBuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 249 of file lv_buffer.c.
Referenced by visual_audio_sample_transform_format(), visual_buffer_append(), and visual_ringbuffer_get_data_offset().
int visual_buffer_put_atomic (VisBuffer * dest, VisBuffer * src, int byteoffset)
Copies data into the VisBuffer from another VisBuffer starting at byteoffset.
The copy is atomic, everything or nothing is copied.
Parameters:
dest Pointer to the destination VisBuffer.
src Pointer to the source VisBuffer.
byteoffset The offset in the destination VisBuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 275 of file lv_buffer.c.
int visual_buffer_put_data (VisBuffer * dest, void * data, visual_size_t size, int byteoffset)
Copies data into the VisBuffer using a data pointer and it's size.
The copy is NOT atomic.
See also:
visual_buffer_put
Parameters:
dest Pointer to the destination VisBuffer.
data Pointer to the data.
size The size of the data.
byteoffset The offset in the destination VisBuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 257 of file lv_buffer.c.
Referenced by visual_buffer_append_data(), visual_buffer_fill_with_pattern(), visual_buffer_put(), and visual_buffer_put_data_atomic().
int visual_buffer_put_data_atomic (VisBuffer * dest, void * data, visual_size_t size, int byteoffset)
Copies data into the VisBuffer using a data pointer and it's size.
The copy is atomic, everything or nothing is copied.
See also:
visual_buffer_put_atomic
Parameters:
dest Pointer to the destination VisBuffer.
data Pointer to the data.
size The size of the data.
byteoffset The offset in the destination VisBuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 283 of file lv_buffer.c.
Referenced by visual_buffer_put_atomic().
int visual_buffer_set_data (VisBuffer * buffer, void * data)
Sets the data to a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer to which the data is set.
data Pointer to the data.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 156 of file lv_buffer.c.
Referenced by visual_buffer_set_data_pair(), visual_video_allocate_buffer(), and visual_video_set_buffer().
int visual_buffer_set_data_pair (VisBuffer * buffer, void * data, visual_size_t datasize)
Sets the data pair (data and it's size) to a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer to which the data pair is set.
data Pointer to the data.
datasize Size in bytes of the data.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 137 of file lv_buffer.c.
Referenced by visual_audio_get_cheap_audio_data(), visual_audio_is_beat(), visual_buffer_destroy_content(), visual_buffer_init(), visual_buffer_new_with_buffer(), and visual_video_free_buffer().
int visual_buffer_set_destroyer (VisBuffer * buffer, VisBufferDestroyerFunc destroyer)
Sets the destroyer function for the content of a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer to which the destroyer function is set.
destroyer The destroyer function.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 121 of file lv_buffer.c.
Referenced by visual_audio_samplepool_input_channel(), visual_buffer_clone(), visual_buffer_init(), visual_buffer_init_allocate(), visual_buffer_new_allocate(), visual_buffer_new_with_buffer(), visual_video_allocate_buffer(), and visual_video_set_buffer().
int visual_buffer_set_size (VisBuffer * buffer, visual_size_t datasize)
Sets the size of the data to a VisBuffer.
Parameters:
buffer Pointer to the VisBuffer to which the data size is set.
datasize Size in bytes of the data.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BUFFER_NULL on failure.
Definition at line 147 of file lv_buffer.c.
Referenced by visual_buffer_clone(), visual_buffer_init_allocate(), visual_buffer_new_allocate(), visual_buffer_set_data_pair(), visual_video_allocate_buffer(), visual_video_set_dimension(), and visual_video_set_pitch().