libvisual: VisTime
VisTime
Defines
#define VISUAL_NSEC_PER_SEC 1000000000
#define VISUAL_USEC_PER_SEC 1000000
#define VISUAL_MSEC_PER_SEC 1000
#define VISUAL_NSEC_PER_MSEC 1000000
#define VISUAL_NSEC_PER_USEC 1000
#define VISUAL_TIME(obj) (VISUAL_CHECK_CAST ((obj), VisTime))
#define VISUAL_TIMER(obj) (VISUAL_CHECK_CAST ((obj), VisTimer))
Typedefs
typedef struct _VisTime VisTime
The VisTime structure can contain seconds and microseconds for timing purpose.
typedef struct _VisTimer VisTimer
Functions
VISUAL_BEGIN_DECLS VisTime * visual_time_new (void)
VisTime * visual_time_new_now (void)
VisTime * visual_time_new_with_values (long sec, long nsec)
VisTime * visual_time_clone (VisTime *src)
void visual_time_free (VisTime *time_)
void visual_time_set (VisTime *time_, long sec, long usec)
void visual_time_copy (VisTime *dest, VisTime *src)
void visual_time_get_now (VisTime *time_)
void visual_time_diff (VisTime *diff, VisTime *time1, VisTime *time2)
int visual_time_is_past (VisTime *time_, VisTime *ref)
double visual_time_to_secs (VisTime *time_)
uint64_t visual_time_to_msecs (VisTime *time_)
uint64_t visual_time_to_usecs (VisTime *time_)
void visual_usleep (uint64_t usecs)
void visual_time_set_from_msecs (VisTime *time_, uint64_t msecs)
VisTimer * visual_timer_new (void)
void visual_timer_free (VisTimer *timer)
void visual_timer_reset (VisTimer *timer)
void visual_timer_start (VisTimer *timer)
void visual_timer_stop (VisTimer *timer)
void visual_timer_resume (VisTimer *timer)
int visual_timer_is_active (VisTimer *timer)
void visual_timer_elapsed (VisTimer *timer, VisTime *time_)
uint64_t visual_timer_elapsed_msecs (VisTimer *timer)
uint64_t visual_timer_elapsed_usecs (VisTimer *timer)
double visual_timer_elapsed_secs (VisTimer *timer)
int visual_timer_is_past (VisTimer *timer, VisTime *time_)
int visual_timer_is_past2 (VisTimer *timer, long sec, long nsec)
Define Documentation
#define VISUAL_MSEC_PER_SEC 1000
Definition at line 38 of file lv_time.h.
#define VISUAL_NSEC_PER_MSEC 1000000
Definition at line 39 of file lv_time.h.
#define VISUAL_NSEC_PER_SEC 1000000000
Definition at line 36 of file lv_time.h.
#define VISUAL_NSEC_PER_USEC 1000
Definition at line 40 of file lv_time.h.
Referenced by visual_bin_switch_set_time().
#define VISUAL_TIME (obj) (VISUAL_CHECK_CAST ((obj), VisTime))
Definition at line 225 of file lv_time.h.
#define VISUAL_TIMER (obj) (VISUAL_CHECK_CAST ((obj), VisTimer))
Definition at line 226 of file lv_time.h.
#define VISUAL_USEC_PER_SEC 1000000
Definition at line 37 of file lv_time.h.
Referenced by LV::usleep().
Typedef Documentation
typedef struct _VisTime VisTime
The VisTime structure can contain seconds and microseconds for timing purpose.
Definition at line 217 of file lv_time.h.
typedef struct _VisTimer VisTimer
Definition at line 220 of file lv_time.h.
Function Documentation
VisTime* visual_time_clone (VisTime * src)
Definition at line 22 of file lv_time_c.cpp.
Referenced by visual_audio_sample_init().
void visual_time_copy (VisTime * dest, VisTime * src)
Definition at line 42 of file lv_time_c.cpp.
Referenced by visual_morph_set_time().
void visual_time_diff (VisTime * diff, VisTime * time1, VisTime * time2)
Definition at line 58 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_flush_old().
void visual_time_free (VisTime * time_)
Definition at line 29 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_flush_old(), visual_audio_samplepool_input_channel(), and visual_plugin_load().
void visual_time_get_now (VisTime * time_)
Definition at line 51 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_flush_old().
int visual_time_is_past (VisTime * time_, VisTime * ref)
Definition at line 67 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_flush_old().
VISUAL_BEGIN_DECLS VisTime* visual_time_new (void)
Definition at line 7 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_flush_old(), visual_beat_adv_init(), and visual_morph_init().
VisTime* visual_time_new_now (void)
Definition at line 12 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_input_channel(), and visual_plugin_load().
VisTime* visual_time_new_with_values (long sec, long nsec)
Definition at line 17 of file lv_time_c.cpp.
Referenced by visual_audio_samplepool_channel_init(), and visual_bin_new().
void visual_time_set (VisTime * time_, long sec, long usec)
Definition at line 34 of file lv_time_c.cpp.
Referenced by visual_bin_switch_set_time().
void visual_time_set_from_msecs (VisTime * time_, uint64_t msecs)
uint64_t visual_time_to_msecs (VisTime * time_)
Definition at line 82 of file lv_time_c.cpp.
double visual_time_to_secs (VisTime * time_)
Definition at line 75 of file lv_time_c.cpp.
uint64_t visual_time_to_usecs (VisTime * time_)
Definition at line 89 of file lv_time_c.cpp.
Referenced by visual_morph_run(), and visual_plugin_load().
void visual_timer_elapsed (VisTimer * timer, VisTime * time_)
Definition at line 139 of file lv_time_c.cpp.
uint64_t visual_timer_elapsed_msecs (VisTimer * timer)
Definition at line 154 of file lv_time_c.cpp.
double visual_timer_elapsed_secs (VisTimer * timer)
Definition at line 147 of file lv_time_c.cpp.
uint64_t visual_timer_elapsed_usecs (VisTimer * timer)
Definition at line 161 of file lv_time_c.cpp.
Referenced by visual_morph_run().
void visual_timer_free (VisTimer * timer)
Definition at line 106 of file lv_time_c.cpp.
int visual_timer_is_active (VisTimer * timer)
Definition at line 132 of file lv_time_c.cpp.
Referenced by visual_morph_run().
int visual_timer_is_past (VisTimer * timer, VisTime * time_)
Definition at line 168 of file lv_time_c.cpp.
int visual_timer_is_past2 (VisTimer * timer, long sec, long nsec)
Definition at line 175 of file lv_time_c.cpp.
VisTimer* visual_timer_new (void)
Definition at line 101 of file lv_time_c.cpp.
Referenced by visual_morph_init().
void visual_timer_reset (VisTimer * timer)
Definition at line 111 of file lv_time_c.cpp.
void visual_timer_resume (VisTimer * timer)
void visual_timer_start (VisTimer * timer)
Definition at line 118 of file lv_time_c.cpp.
Referenced by visual_morph_run().
void visual_timer_stop (VisTimer * timer)
Definition at line 125 of file lv_time_c.cpp.
Referenced by visual_morph_is_done().
void visual_usleep (uint64_t usecs)
Definition at line 96 of file lv_time_c.cpp.