libvisual: VisDFT
VisDFT
Defines
#define VISUAL_DFT(obj) (VISUAL_CHECK_CAST ((obj), VisDFT))
Typedefs
typedef struct _VisDFT VisDFT
Functions
void visual_fourier_initialize (void)
int visual_fourier_is_initialized (void)
void visual_fourier_deinitialize (void)
VisDFT * visual_dft_new (unsigned int samples_out, unsigned int samples_in)
void visual_dft_free (VisDFT *dft)
void visual_dft_perform (VisDFT *dft, float *output, float const *input)
void visual_dft_log_scale (float *output, float const *input, unsigned int size)
void visual_dft_log_scale_standard (float *output, float const *input, unsigned int size)
void visual_dft_log_scale_custom (float *output, float const *input, unsigned int size, float log_scale_divisor)
Define Documentation
#define VISUAL_DFT (obj) (VISUAL_CHECK_CAST ((obj), VisDFT))
Definition at line 131 of file lv_fourier.h.
Typedef Documentation
typedef struct _VisDFT VisDFT
Definition at line 136 of file lv_fourier.h.
Function Documentation
void visual_dft_free (VisDFT * dft)
Definition at line 12 of file lv_fourier_c.cpp.
Referenced by visual_audio_get_spectrum_for_sample().
void visual_dft_log_scale (float * output, float const * input, unsigned int size)
Definition at line 24 of file lv_fourier_c.cpp.
void visual_dft_log_scale_custom (float * output, float const * input, unsigned int size, float log_scale_divisor)
Definition at line 34 of file lv_fourier_c.cpp.
void visual_dft_log_scale_standard (float * output, float const * input, unsigned int size)
Definition at line 29 of file lv_fourier_c.cpp.
Referenced by visual_audio_normalise_spectrum().
VisDFT* visual_dft_new (unsigned int samples_out, unsigned int samples_in)
Definition at line 7 of file lv_fourier_c.cpp.
Referenced by visual_audio_get_spectrum_for_sample().
void visual_dft_perform (VisDFT * dft, float * output, float const * input)
Definition at line 17 of file lv_fourier_c.cpp.
Referenced by visual_audio_get_spectrum_for_sample().
void visual_fourier_deinitialize (void)
Definition at line 49 of file lv_fourier_c.cpp.
void visual_fourier_initialize (void)
Definition at line 39 of file lv_fourier_c.cpp.
int visual_fourier_is_initialized (void)
Definition at line 44 of file lv_fourier_c.cpp.