libvisual: VisBeat
VisBeat
Data Structures
struct _VisBeatType
struct _VisBeatPeak
struct _VisBeatAdv
struct _VisBeat
Defines
#define VISUAL_BEAT(obj) (VISUAL_CHECK_CAST ((obj), VisBeat))
#define VISUAL_BEAT_ADV(obj) (VISUAL_CHECK_CAST ((obj), VisBeatAdv))
#define BEAT_REAL 1
#define BEAT_GUESSED 2
#define BEAT_MAX_BPM 170
#define BEAT_MIN_BPM 60
#define BEAT_BETTER_CONF_ADOPT 2
#define BEAT_TOP_CONF_ADOPT 8
#define BEAT_MIN_STICKY 8
#define BEAT_STICKY_THRESHOLD 70
#define BEAT_STICKY_THRESHOLD_LOW 85
#define BEAT_ADV_MAX 200
#define BEAT_MAX_SIZE 4096
Typedefs
typedef struct _VisBeat VisBeat
typedef struct _VisBeatType VisBeatType
typedef struct _VisBeatPeak VisBeatPeak
typedef struct _VisBeatAdv VisBeatAdv
Enumerations
enum VisBeatSlider { VISUAL_BEAT_SLIDE_IN, VISUAL_BEAT_SLIDE_OUT }
enum VisBeatAlgorithm { VISUAL_BEAT_ALGORITHM_PEAK, VISUAL_BEAT_ALGORITHM_ADV }
Functions
VisBeat * visual_beat_new (void)
Create a new VisBeat.
int visual_beat_init (VisBeat *beat)
Initialize a VisBeat.
int visual_beat_refine_beat (VisBeat *beat, int beat_in)
Refine the beat indication through adaptive learning.
int visual_beat_change_song (VisBeat *beat)
Signal that the song has changed.
int visual_beat_reset_adapt (VisBeat *beat)
Reset a VisBeat so that it may readapt.
int visual_beat_slider_get (VisBeat *beat, VisBeatSlider slider)
int visual_beat_set_config (VisBeat *beat, int smartbeat, int smartbeatsticky, int smartbeatresetnewsong, int smartbeatonlysticky)
Set the configuration parameters for a VisBeat.
int visual_beat_set_smartbeat (VisBeat *beat, int smartbeat)
Set the smartbeat parameter for a VisBeat.
int visual_beat_set_smartbeat_sticky (VisBeat *beat, int smartbeatsticky)
int visual_beat_set_smartbeat_reset_on_newsong (VisBeat *beat, int smartbeatnewsong)
Set the smartbeat parameter for a VisBeat.
int visual_beat_set_smartbeat_only_sticky (VisBeat *beat, int smartbeatonlysticky)
Set the smartbeat parameter for a VisBeat.
VisBeatPeak * visual_beat_get_peak (VisBeat *beat)
Retrieve the VisBeatPeak from a VisBeat.
VisBeatAdv * visual_beat_get_adv (VisBeat *beat)
Retrieve the VisBeatAdv from a VisBeat.
char * visual_beat_get_info (VisBeat *beat)
Retrive a formatted string indicating current BPM and confidence.
Define Documentation
#define BEAT_ADV_MAX 200
Definition at line 84 of file lv_beat.h.
Referenced by visual_beat_adv_init().
#define BEAT_BETTER_CONF_ADOPT 2
Definition at line 78 of file lv_beat.h.
#define BEAT_GUESSED 2
Definition at line 73 of file lv_beat.h.
Referenced by visual_beat_refine_beat().
#define BEAT_MAX_BPM 170
Definition at line 75 of file lv_beat.h.
Referenced by beat_calc_bpm(), and visual_beat_refine_beat().
#define BEAT_MAX_SIZE 4096
Definition at line 85 of file lv_beat.h.
Referenced by visual_audio_is_beat(), and visual_audio_is_beat_with_data().
#define BEAT_MIN_BPM 60
Definition at line 76 of file lv_beat.h.
Referenced by beat_calc_bpm(), beat_double_beat(), beat_half_beat(), and visual_beat_refine_beat().
#define BEAT_MIN_STICKY 8
Definition at line 80 of file lv_beat.h.
Referenced by beat_calc_bpm().
#define BEAT_REAL 1
Definition at line 72 of file lv_beat.h.
Referenced by beat_calc_bpm(), and visual_beat_refine_beat().
#define BEAT_STICKY_THRESHOLD 70
Definition at line 81 of file lv_beat.h.
Referenced by beat_calc_bpm().
#define BEAT_STICKY_THRESHOLD_LOW 85
Definition at line 82 of file lv_beat.h.
Referenced by beat_calc_bpm().
#define BEAT_TOP_CONF_ADOPT 8
Definition at line 79 of file lv_beat.h.
Referenced by visual_beat_refine_beat().
#define VISUAL_BEAT (obj) (VISUAL_CHECK_CAST ((obj), VisBeat))
Definition at line 69 of file lv_beat.h.
#define VISUAL_BEAT_ADV (obj) (VISUAL_CHECK_CAST ((obj), VisBeatAdv))
Definition at line 70 of file lv_beat.h.
Typedef Documentation
typedef struct _VisBeat VisBeat
Definition at line 87 of file lv_beat.h.
typedef struct _VisBeatAdv VisBeatAdv
Definition at line 90 of file lv_beat.h.
typedef struct _VisBeatPeak VisBeatPeak
Definition at line 89 of file lv_beat.h.
typedef struct _VisBeatType VisBeatType
Definition at line 88 of file lv_beat.h.
Enumeration Type Documentation
enum VisBeatAlgorithm
Enumerator:
VISUAL_BEAT_ALGORITHM_PEAK
VISUAL_BEAT_ALGORITHM_ADV
Definition at line 97 of file lv_beat.h.
enum VisBeatSlider
Enumerator:
VISUAL_BEAT_SLIDE_IN
VISUAL_BEAT_SLIDE_OUT
Definition at line 92 of file lv_beat.h.
Function Documentation
int visual_beat_change_song (VisBeat * beat)
Signal that the song has changed.
Parameters:
beat This VisBeat for which we want to give the signal that the song changed.
Returns:
VISUAL_OK on success, or -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 287 of file lv_beat.c.
VisBeatAdv* visual_beat_get_adv (VisBeat * beat)
Retrieve the VisBeatAdv from a VisBeat.
Parameters:
beat The VisBeat from which to retrieve its VisBeatAdv.
Returns:
The VisBeatAdv on success, NULL upon failure.
Definition at line 499 of file lv_beat.c.
Referenced by visual_audio_is_beat_with_data().
char* visual_beat_get_info (VisBeat * beat)
Retrive a formatted string indicating current BPM and confidence.
Parameters:
beat The VisBeat from which info is desired.
Returns:
The formatted string on success, or NULL on failure.
Definition at line 296 of file lv_beat.c.
Referenced by visual_audio_is_beat_with_data().
VisBeatPeak* visual_beat_get_peak (VisBeat * beat)
Retrieve the VisBeatPeak from a VisBeat.
Parameters:
beat The VisBeat from which to retrieve its VisBeatPeak.
Returns:
The VisBeatPeak on success, NULL upon failure.
Definition at line 492 of file lv_beat.c.
Referenced by visual_audio_is_beat_with_data().
int visual_beat_init (VisBeat * beat)
Initialize a VisBeat.
This should not be used on an already initialized VisBeat.
Parameters:
beat The VisBeat to be initialized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 129 of file lv_beat.c.
Referenced by visual_beat_new().
VisBeat* visual_beat_new (void)
Create a new VisBeat.
Returns:
A newly allocated VisBeat, or NULL on failure.
Definition at line 118 of file lv_beat.c.
Referenced by visual_audio_new().
int visual_beat_refine_beat (VisBeat * beat, int beat_in)
Refine the beat indication through adaptive learning.
Parameters:
beat The VisBeat for which a new beat is to be refined.
isBeat The beat as a boolean -- TRUE for a beat, FALSE otherwise.
Returns:
TRUE or FALSE indicating whether this is a beat or not.
Definition at line 368 of file lv_beat.c.
Referenced by visual_audio_is_beat_with_data().
int visual_beat_reset_adapt (VisBeat * beat)
Reset a VisBeat so that it may readapt.
Parameters:
beat The VisBeat to be reset.
Returns:
VISUAL_OK on success, or -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 327 of file lv_beat.c.
Referenced by beat_calc_bpm(), and visual_beat_refine_beat().
int visual_beat_set_config (VisBeat * beat, int smartbeat, int smartbeatsticky, int smartbeatresetnewsong, int smartbeatonlysticky)
Set the configuration parameters for a VisBeat.
beat The VisBeat for which the parameters are to be set.
Parameters:
smartbeat Advanced beat detection if TRUE. If this is not set, the other config parameters are ignored.
smartbeatsticky Auto-keep if TRUE.
smartbeatresetnewsong Upon song change if value is FALSE then adapt from known BPM, if TRUE then restart from scratch.
smartbeatonlysticky Predict only if BPM has been found if set TRUE.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 239 of file lv_beat.c.
int visual_beat_set_smartbeat (VisBeat * beat, int smartbeat)
Set the smartbeat parameter for a VisBeat.
Parameters:
beat The VisBeat for which parameter is set.
smartbeat See visual_beat_set_config
Returns:
VISUAL_OK on success, or -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 251 of file lv_beat.c.
int visual_beat_set_smartbeat_only_sticky (VisBeat * beat, int smartbeatonlysticky)
Set the smartbeat parameter for a VisBeat.
Parameters:
beat The VisBeat for which parameter is set.
smartbeat See visual_beat_set_config
Returns:
VISUAL_OK on success, or -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 278 of file lv_beat.c.
int visual_beat_set_smartbeat_reset_on_newsong (VisBeat * beat, int smartbeatnewsong)
Set the smartbeat parameter for a VisBeat.
Parameters:
beat The VisBeat for which parameter is set.
smartbeat See visual_beat_set_config
Returns:
VISUAL_OK on success, or -VISUAL_ERROR_BEAT_NULL on failure.
Definition at line 269 of file lv_beat.c.
int visual_beat_set_smartbeat_sticky (VisBeat * beat, int smartbeatsticky)
Definition at line 260 of file lv_beat.c.
int visual_beat_slider_get (VisBeat * beat, VisBeatSlider slider)
Definition at line 361 of file lv_beat.c.
Referenced by visual_audio_is_beat_with_data().