libvisual: VisMorph
VisMorph
Data Structures
struct _VisMorph
The VisMorph structure encapsulates the morph plugin and provides abstract interfaces for morphing between actors, or rather between two video sources.
struct _VisMorphPlugin
The VisMorphPlugin structure is the main data structure for the morph plugin.
Defines
#define VISUAL_MORPH(obj) (VISUAL_CHECK_CAST ((obj), VisMorph))
#define VISUAL_MORPH_PLUGIN(obj) (VISUAL_CHECK_CAST ((obj), VisMorphPlugin))
Typedefs
typedef struct _VisMorph VisMorph
typedef struct _VisMorphPlugin VisMorphPlugin
typedef int(* VisPluginMorphPaletteFunc)(VisPluginData *plugin, float rate, VisAudio *audio, VisPalette *pal, VisVideo *src1, VisVideo *src2)
A morph plugin needs this signature for the palette function.
typedef int(* VisPluginMorphApplyFunc)(VisPluginData *plugin, float rate, VisAudio *audio, VisVideo *dest, VisVideo *src1, VisVideo *src2)
A morph plugin needs this signature for the apply function.
Enumerations
enum VisMorphMode { VISUAL_MORPH_MODE_SET, VISUAL_MORPH_MODE_STEPS, VISUAL_MORPH_MODE_TIME }
Morph morphing methods.
Functions
VisPluginData * visual_morph_get_plugin (VisMorph *morph)
Gives the encapsulated VisPluginData from a VisMorph.
const char * visual_morph_get_next_by_name (const char *name)
Gives the next morph plugin based on the name of a plugin.
const char * visual_morph_get_prev_by_name (const char *name)
Gives the previous morph plugin based on the name of a plugin.
VisMorph * visual_morph_new (const char *morphname)
Creates a new VisMorph from name, the plugin will be loaded but won't be realized.
int visual_morph_init (VisMorph *morph, const char *morphname)
Initializes a VisMorph, this will set the allocated flag for the object to FALSE.
int visual_morph_realize (VisMorph *morph)
Realize the VisMorph.
int visual_morph_get_supported_depth (VisMorph *morph)
Gives the by the plugin natively supported depths.
VisVideoAttributeOptions * visual_morph_get_video_attribute_options (VisMorph *morph)
int visual_morph_set_video (VisMorph *morph, VisVideo *video)
Used to connect the target display, or a buffer it's VisVideo to the VisMorph plugin.
int visual_morph_set_time (VisMorph *morph, VisTime *time)
Set the time when the morph should be finished morphing.
int visual_morph_set_rate (VisMorph *morph, float rate)
Used to set the rate of the VisMmorph.
int visual_morph_set_steps (VisMorph *morph, int steps)
Used to set the number of steps that a morph will take to finish.
int visual_morph_set_mode (VisMorph *morph, VisMorphMode mode)
Used to set the method of morphing.
VisPalette * visual_morph_get_palette (VisMorph *morph)
Some morph plugins can give a custom palette while morphing two 8 bits plugins.
int visual_morph_is_done (VisMorph *morph)
Function that helps to check if a morph is done with it's morphing.
int visual_morph_requests_audio (VisMorph *morph)
Some morph plugins request an VisAudio context to draw properly.
int visual_morph_run (VisMorph *morph, VisAudio *audio, VisVideo *src1, VisVideo *src2)
This is called to run the VisMorph.
Define Documentation
#define VISUAL_MORPH (obj) (VISUAL_CHECK_CAST ((obj), VisMorph))
Definition at line 41 of file lv_morph.h.
#define VISUAL_MORPH_PLUGIN (obj) (VISUAL_CHECK_CAST ((obj), VisMorphPlugin))
Definition at line 42 of file lv_morph.h.
Typedef Documentation
typedef struct _VisMorph VisMorph
Definition at line 56 of file lv_morph.h.
typedef struct _VisMorphPlugin VisMorphPlugin
Definition at line 57 of file lv_morph.h.
typedef int(* VisPluginMorphApplyFunc)(VisPluginData *plugin, float rate, VisAudio *audio, VisVideo *dest, VisVideo *src1, VisVideo *src2)
A morph plugin needs this signature for the apply function.
The apply function is used to execute a morph between two VisVideo sources. It's the 'render' function of the morph plugin and here is the morphing done.
plugin Pointer to the VisPluginData instance structure.
rate A float between 0.0 and 1.0 that tells how far the morph has proceeded.
audio Pointer to the VisAudio containing all the data regarding the current audio sample.
src1 A pointer to the first VisVideo source.
src2 A pointer to the second VisVideo source.
Returns:
0 on succes -1 on error.
Definition at line 93 of file lv_morph.h.
typedef int(* VisPluginMorphPaletteFunc)(VisPluginData *plugin, float rate, VisAudio *audio, VisPalette *pal, VisVideo *src1, VisVideo *src2)
A morph plugin needs this signature for the palette function.
The palette function is used to give a palette for the morph. The palette function isn't mandatory and the VisMorph system will interpolate between the two palettes in VISUAL_VIDEO_DEPTH_8BIT when a palette function isn't set.
plugin Pointer to the VisPluginData instance structure.
rate A float between 0.0 and 1.0 that tells how far the morph has proceeded.
audio Pointer to the VisAudio containing all the data regarding the current audio sample.
pal A pointer to the target VisPalette in which the morph between the two palettes is saved. Should have 256 VisColor entries.
src1 A pointer to the first VisVideo source.
src2 A pointer to the second VisVideo source.
Returns:
0 on succes -1 on error.
Definition at line 77 of file lv_morph.h.
Enumeration Type Documentation
enum VisMorphMode
Morph morphing methods.
Enumerator:
VISUAL_MORPH_MODE_SET
Morphing is done by a rate set, nothing is automated here.
VISUAL_MORPH_MODE_STEPS
Morphing is done by setting a number of steps, the morph will be automated.
VISUAL_MORPH_MODE_TIME
Morphing is done by setting a target time when the morph should be done, This is as well automated.
Definition at line 47 of file lv_morph.h.
Function Documentation
const char* visual_morph_get_next_by_name (const char * name)
Gives the next morph plugin based on the name of a plugin.
See also:
visual_morph_get_prev_by_name
Parameters:
name The name of the current plugin, or NULL to get the first.
Returns:
The name of the next plugin within the list.
Definition at line 84 of file lv_morph.cpp.
VisPalette* visual_morph_get_palette (VisMorph * morph)
Some morph plugins can give a custom palette while morphing two 8 bits plugins.
Parameters:
morph Pointer to a VisMorph of which the palette needs to be retrieved.
Returns:
The pointer to the custom palette on succes or NULL on failure.
Definition at line 241 of file lv_morph.cpp.
Referenced by visual_bin_get_palette(), and visual_morph_run().
VisPluginData* visual_morph_get_plugin (VisMorph * morph)
Gives the encapsulated VisPluginData from a VisMorph.
Parameters:
morph Pointer of a VisMorph of which the VisPluginData needs to be returned.
Returns:
VisPluginData that is encapsulated in the VisMorph, possibly NULL.
Definition at line 79 of file lv_morph.cpp.
const char* visual_morph_get_prev_by_name (const char * name)
Gives the previous morph plugin based on the name of a plugin.
See also:
visual_morph_get_next_by_name
Parameters:
name The name of the current plugin. or NULL to get the last.
Returns:
The name of the previous plugin within the list.
Definition at line 89 of file lv_morph.cpp.
int visual_morph_get_supported_depth (VisMorph * morph)
Gives the by the plugin natively supported depths.
Parameters:
morph Pointer to a VisMorph of which the supported depth of it's encapsulated plugin is requested.
Returns:
an OR value of the VISUAL_VIDEO_CONTEXT_* values which can be checked against using AND on success, -1 on failure
Definition at line 164 of file lv_morph.cpp.
Referenced by visual_bin_set_morph_by_name().
VisVideoAttributeOptions* visual_morph_get_video_attribute_options (VisMorph * morph)
Definition at line 179 of file lv_morph.cpp.
int visual_morph_init (VisMorph * morph, const char * morphname)
Initializes a VisMorph, this will set the allocated flag for the object to FALSE.
Should not be used to reset a VisMorph, or on a VisMorph created by visual_morph_new().
See also:
visual_morph_new
Parameters:
morph Pointer to the VisMorph that is initialized.
morphname The name of the plugin to load, or NULL to simply initialize a new morph.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL or -VISUAL_ERROR_PLUGIN_NO_LIST on failure.
Definition at line 114 of file lv_morph.cpp.
Referenced by visual_morph_new().
int visual_morph_is_done (VisMorph * morph)
Function that helps to check if a morph is done with it's morphing.
Parameters:
morph Pointer to a VisMorph of which we want to know if it's done yet.
Returns:
TRUE or FALSE, -VISUAL_ERROR_MORPH_NULL on failure.
Definition at line 248 of file lv_morph.cpp.
Referenced by visual_bin_run().
VisMorph* visual_morph_new (const char * morphname)
Creates a new VisMorph from name, the plugin will be loaded but won't be realized.
Parameters:
morphname The name of the plugin to load, or NULL to simply allocate a new morph.
Returns:
A newly allocated VisMorph, optionally containing a loaded plugin. Or NULL on failure.
Definition at line 94 of file lv_morph.cpp.
Referenced by visual_bin_set_morph_by_name().
int visual_morph_realize (VisMorph * morph)
Realize the VisMorph.
This also calls the plugin init function.
Parameters:
morph Pointer to a VisMorph that needs to be realized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL, -VISUAL_ERROR_PLUGIN_NULL or error values returned by visual_plugin_realize () on failure.
Definition at line 156 of file lv_morph.cpp.
Referenced by visual_bin_realize(), and visual_bin_run().
int visual_morph_requests_audio (VisMorph * morph)
Some morph plugins request an VisAudio context to draw properly.
Using this function you can check if the VisMorphPlugin being used in the VisMorph requests this.
Parameters:
morph Pointer to a VisMorph of which we want to know if it wants a VisAudio.
Returns:
TRUE or FALSE, -VISUAL_ERROR_MORPH_NULL or -VISUAL_ERROR_MORPH_PLUGIN_NULL on failure.
Definition at line 272 of file lv_morph.cpp.
int visual_morph_run (VisMorph * morph, VisAudio * audio, VisVideo * src1, VisVideo * src2)
This is called to run the VisMorph.
It will put the result in the buffer that is previously set by visual_morph_set_video and also when the morph is being runned in 8 bits mode it will automaticly interpolate between the two palettes if the plugin doesn't have a method for adjusting the palette.
Note that all the VisVideo structures being used need to be clones.
Parameters:
morph Pointer to a VisMorph that needs to be runned.
audio Pointer to a VisAudio which a morph could use for extra effects
src1 Pointer to a VisVideo that acts as the first source for the morph.
src2 Pointer to a VisVideo that acts as the second source for the morph.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL, -VISUAL_ERROR_AUDIO_NULL, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_NULL on failure.
Todo:
: We might want to have a bigger type here, but long longs aren't atomic on most architectures, so that won't do for now, maybe when we can lock (for threading) we can look into that
Definition at line 290 of file lv_morph.cpp.
Referenced by visual_bin_run().
int visual_morph_set_mode (VisMorph * morph, VisMorphMode mode)
Used to set the method of morphing.
Parameters:
morph Pointer to a VisMorph to which the method of morphing is set.
mode Method of morphing that is of type VisMorphMode.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL on failure.
Definition at line 232 of file lv_morph.cpp.
Referenced by visual_bin_switch_actor(), and visual_morph_init().
int visual_morph_set_rate (VisMorph * morph, float rate)
Used to set the rate of the VisMmorph.
The rate ranges from 0 to 1 and the content of the result depends on the morph plugin being used.
Parameters:
morph Pointer to a VisMorph to which the rate needs to be set.
rate Value that sets the rate of the current morph. The rate contains the amount that is currently being morphed and needs to be manually adjust. The morph system doesn't increase the rate itself.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL on failure.
Definition at line 214 of file lv_morph.cpp.
Referenced by visual_bin_switch_actor(), and visual_morph_init().
int visual_morph_set_steps (VisMorph * morph, int steps)
Used to set the number of steps that a morph will take to finish.
Parameters:
morph Pointer to a VisMorph to which the number of morph steps is set.
steps The number of steps that a morph should take.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL on failure.
Definition at line 223 of file lv_morph.cpp.
Referenced by visual_bin_switch_actor(), and visual_morph_init().
int visual_morph_set_time (VisMorph * morph, VisTime * time)
Set the time when the morph should be finished morphing.
The VisMorph keeps a local copy of the given time.
Parameters:
morph Pointer to the VisMorph to which finish time is set.
time Pointer to the VisTime that contains the finish time.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL, -VISUAL_ERROR_TIME_NULL or error values returned by visual_time_copy () on failure.
Definition at line 204 of file lv_morph.cpp.
Referenced by visual_bin_switch_actor().
int visual_morph_set_video (VisMorph * morph, VisVideo * video)
Used to connect the target display, or a buffer it's VisVideo to the VisMorph plugin.
See also:
visual_video_new
Parameters:
morph Pointer to a VisMorph to which the VisVideo needs to be set.
video Pointer to a VisVideo which contains information about the target display and the pointer to it's screenbuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MORPH_NULL or -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 194 of file lv_morph.cpp.
Referenced by visual_bin_switch_actor(), and visual_bin_sync().