libvisual: VisBin
VisBin
Data Structures
struct _VisBin
Defines
#define VISUAL_BIN(obj) (VISUAL_CHECK_CAST ((obj), VisBin))
Typedefs
typedef struct _VisBin VisBin
Enumerations
enum VisBinSwitchStyle { VISUAL_SWITCH_STYLE_DIRECT, VISUAL_SWITCH_STYLE_MORPH }
enum VisBinDepth { VISUAL_BIN_DEPTH_LOWEST, VISUAL_BIN_DEPTH_HIGHEST }
Functions
VisBin * visual_bin_new (void)
int visual_bin_realize (VisBin *bin)
int visual_bin_set_actor (VisBin *bin, VisActor *actor)
VisActor * visual_bin_get_actor (VisBin *bin)
int visual_bin_set_input (VisBin *bin, VisInput *input)
VisInput * visual_bin_get_input (VisBin *bin)
int visual_bin_set_morph (VisBin *bin, VisMorph *morph)
int visual_bin_set_morph_by_name (VisBin *bin, const char *morphname)
VisMorph * visual_bin_get_morph (VisBin *bin)
int visual_bin_connect (VisBin *bin, VisActor *actor, VisInput *input)
int visual_bin_connect_by_names (VisBin *bin, const char *actname, const char *inname)
int visual_bin_sync (VisBin *bin, int noevent)
int visual_bin_set_video (VisBin *bin, VisVideo *video)
int visual_bin_set_supported_depth (VisBin *bin, int depthflag)
int visual_bin_set_preferred_depth (VisBin *bin, VisBinDepth depthpreferred)
int visual_bin_set_depth (VisBin *bin, int depth)
int visual_bin_get_depth (VisBin *bin)
int visual_bin_depth_changed (VisBin *bin)
VisPalette * visual_bin_get_palette (VisBin *bin)
int visual_bin_switch_actor_by_name (VisBin *bin, const char *actname)
int visual_bin_switch_actor (VisBin *bin, VisActor *actor)
int visual_bin_switch_finalize (VisBin *bin)
int visual_bin_switch_set_style (VisBin *bin, VisBinSwitchStyle style)
int visual_bin_switch_set_steps (VisBin *bin, int steps)
int visual_bin_switch_set_automatic (VisBin *bin, int automatic)
int visual_bin_switch_set_rate (VisBin *bin, float rate)
int visual_bin_switch_set_mode (VisBin *bin, VisMorphMode mode)
int visual_bin_switch_set_time (VisBin *bin, long sec, long usec)
int visual_bin_run (VisBin *bin)
Define Documentation
#define VISUAL_BIN (obj) (VISUAL_CHECK_CAST ((obj), VisBin))
Definition at line 40 of file lv_bin.h.
Typedef Documentation
typedef struct _VisBin VisBin
Definition at line 52 of file lv_bin.h.
Enumeration Type Documentation
enum VisBinDepth
Enumerator:
VISUAL_BIN_DEPTH_LOWEST
VISUAL_BIN_DEPTH_HIGHEST
Definition at line 47 of file lv_bin.h.
enum VisBinSwitchStyle
Enumerator:
VISUAL_SWITCH_STYLE_DIRECT
VISUAL_SWITCH_STYLE_MORPH
Definition at line 42 of file lv_bin.h.
Function Documentation
int visual_bin_connect (VisBin * bin, VisActor * actor, VisInput * input)
Definition at line 227 of file lv_bin.c.
Referenced by visual_bin_connect_by_names().
int visual_bin_connect_by_names (VisBin * bin, const char * actname, const char * inname)
Definition at line 260 of file lv_bin.c.
int visual_bin_depth_changed (VisBin * bin)
Definition at line 443 of file lv_bin.c.
VisActor* visual_bin_get_actor (VisBin * bin)
Definition at line 143 of file lv_bin.c.
int visual_bin_get_depth (VisBin * bin)
Definition at line 436 of file lv_bin.c.
VisInput* visual_bin_get_input (VisBin * bin)
Definition at line 161 of file lv_bin.c.
VisMorph* visual_bin_get_morph (VisBin * bin)
Definition at line 208 of file lv_bin.c.
VisPalette* visual_bin_get_palette (VisBin * bin)
Definition at line 455 of file lv_bin.c.
VisBin* visual_bin_new (void)
Definition at line 97 of file lv_bin.c.
int visual_bin_realize (VisBin * bin)
Definition at line 116 of file lv_bin.c.
int visual_bin_run (VisBin * bin)
Definition at line 801 of file lv_bin.c.
int visual_bin_set_actor (VisBin * bin, VisActor * actor)
Definition at line 132 of file lv_bin.c.
Referenced by visual_bin_connect().
int visual_bin_set_depth (VisBin * bin, int depth)
Definition at line 409 of file lv_bin.c.
Referenced by visual_bin_connect(), visual_bin_switch_actor_by_name(), and visual_bin_switch_finalize().
int visual_bin_set_input (VisBin * bin, VisInput * input)
Definition at line 150 of file lv_bin.c.
Referenced by visual_bin_connect().
int visual_bin_set_morph (VisBin * bin, VisMorph * morph)
Definition at line 168 of file lv_bin.c.
int visual_bin_set_morph_by_name (VisBin * bin, const char * morphname)
Definition at line 179 of file lv_bin.c.
int visual_bin_set_preferred_depth (VisBin * bin, VisBinDepth depthpreferred)
Definition at line 400 of file lv_bin.c.
int visual_bin_set_supported_depth (VisBin * bin, int depthflag)
Definition at line 391 of file lv_bin.c.
int visual_bin_set_video (VisBin * bin, VisVideo * video)
Definition at line 382 of file lv_bin.c.
int visual_bin_switch_actor (VisBin * bin, VisActor * actor)
Definition at line 596 of file lv_bin.c.
Referenced by visual_bin_switch_actor_by_name().
int visual_bin_switch_actor_by_name (VisBin * bin, const char * actname)
Definition at line 465 of file lv_bin.c.
int visual_bin_switch_finalize (VisBin * bin)
Definition at line 684 of file lv_bin.c.
Referenced by visual_bin_run().
int visual_bin_switch_set_automatic (VisBin * bin, int automatic)
Definition at line 765 of file lv_bin.c.
int visual_bin_switch_set_mode (VisBin * bin, VisMorphMode mode)
Definition at line 783 of file lv_bin.c.
int visual_bin_switch_set_rate (VisBin * bin, float rate)
Definition at line 774 of file lv_bin.c.
int visual_bin_switch_set_steps (VisBin * bin, int steps)
Definition at line 756 of file lv_bin.c.
int visual_bin_switch_set_style (VisBin * bin, VisBinSwitchStyle style)
Definition at line 747 of file lv_bin.c.
int visual_bin_switch_set_time (VisBin * bin, long sec, long usec)
Definition at line 792 of file lv_bin.c.
int visual_bin_sync (VisBin * bin, int noevent)
Definition at line 286 of file lv_bin.c.