libvisual: VisCPU
VisCPU
Data Structures
struct _VisCPU
This VisCPU structure contains information regarding the processor.
Typedefs
typedef struct _VisCPU VisCPU
Enumerations
enum VisCPUType {
VISUAL_CPU_TYPE_MIPS, VISUAL_CPU_TYPE_ALPHA, VISUAL_CPU_TYPE_SPARC, VISUAL_CPU_TYPE_X86,
VISUAL_CPU_TYPE_POWERPC, VISUAL_CPU_TYPE_ARM, VISUAL_CPU_TYPE_OTHER
}
Enumerate containing the different architectual types.
Functions
void visual_cpu_initialize (void)
Initializes the VisCPU caps structure by detecting the CPU features and flags.
const VisCPU * visual_cpu_get_caps (void)
Function to get the VisCPU caps initialized by visual_cpu_initialize(), this contains information regarding the CPU features and flags.
int visual_cpu_has_tsc (void)
Function to retrieve if the tsc CPU feature is enabled.
int visual_cpu_has_mmx (void)
Function to retrieve if the MMX CPU feature is enabled.
int visual_cpu_has_mmx2 (void)
Function to retrieve if the MMX2 CPU feature is enabled.
int visual_cpu_has_sse (void)
Function to retrieve if the SSE CPU feature is enabled.
int visual_cpu_has_sse2 (void)
Function to retrieve if the SSE2 CPU feature is enabled.
int visual_cpu_has_3dnow (void)
Function to retrieve if the 3dnow CPU feature is enabled.
int visual_cpu_has_3dnow2 (void)
Function to retrieve if the 3dnowext CPU feature is enabled.
int visual_cpu_has_altivec (void)
Function to retrieve if the altivec CPU feature is enabled.
int visual_cpu_has_armv7 (void)
Function to retrieve if the ARM v7 feature is enabled.
int visual_cpu_has_vfpv3 (void)
Function to retrieve if the ARM VFPv3 feature is enabled.
int visual_cpu_has_neon (void)
Function to retrieve if the ARM Neon feature is enabled.
int visual_cpu_has_ldrex_strex (void)
Function to retrieve if the ARM LDREX_STREX feature is enabled.
Typedef Documentation
typedef struct _VisCPU VisCPU
Definition at line 50 of file lv_cpu.h.
Enumeration Type Documentation
enum VisCPUType
Enumerate containing the different architectual types.
Enumerator:
VISUAL_CPU_TYPE_MIPS
Running on the mips architecture.
VISUAL_CPU_TYPE_ALPHA
Running on the alpha architecture.
VISUAL_CPU_TYPE_SPARC
Running on the sparc architecture.
VISUAL_CPU_TYPE_X86
Running on the X86 architecture.
VISUAL_CPU_TYPE_POWERPC
Running on the PowerPC architecture.
VISUAL_CPU_TYPE_ARM
Running on the ARM architecture,.
VISUAL_CPU_TYPE_OTHER
Running on an architecture that is not specified.
Definition at line 40 of file lv_cpu.h.
Function Documentation
const VisCPU* visual_cpu_get_caps (void)
Function to get the VisCPU caps initialized by visual_cpu_initialize(), this contains information regarding the CPU features and flags.
Returns:
The VisCPU caps structure.
Definition at line 526 of file lv_cpu.c.
int visual_cpu_has_3dnow (void)
Function to retrieve if the 3dnow CPU feature is enabled.
Returns:
Whether 3dnow is enabled or not.
Definition at line 565 of file lv_cpu.c.
Referenced by visual_math_vectorized_add_floats_const_float(), visual_math_vectorized_floats_to_int32s(), visual_math_vectorized_floats_to_int32s_multiply(), visual_math_vectorized_floats_to_int32s_multiply_denormalise(), visual_math_vectorized_int32s_to_floats(), visual_math_vectorized_int32s_to_floats_multiply(), visual_math_vectorized_multiplier_floats_const_float(), visual_math_vectorized_multiplier_floats_floats(), visual_math_vectorized_substract_floats_const_float(), and visual_mem_initialize().
int visual_cpu_has_3dnow2 (void)
Function to retrieve if the 3dnowext CPU feature is enabled.
Returns:
Whether 3dnowext is enabled or not.
Definition at line 573 of file lv_cpu.c.
int visual_cpu_has_altivec (void)
Function to retrieve if the altivec CPU feature is enabled.
Returns:
Whether altivec is enabled or not.
Definition at line 581 of file lv_cpu.c.
int visual_cpu_has_armv7 (void)
Function to retrieve if the ARM v7 feature is enabled.
Returns:
Whether altivec is enabled or not.
Definition at line 589 of file lv_cpu.c.
int visual_cpu_has_ldrex_strex (void)
Function to retrieve if the ARM LDREX_STREX feature is enabled.
Returns:
Whether altivec is enabled or not.
Definition at line 613 of file lv_cpu.c.
int visual_cpu_has_mmx (void)
Function to retrieve if the MMX CPU feature is enabled.
Returns:
Whether MMX is enabled or not.
Definition at line 534 of file lv_cpu.c.
Referenced by blit_overlay_alphasrc(), visual_alpha_blend_initialize(), visual_mem_initialize(), and visual_video_scale().
int visual_cpu_has_mmx2 (void)
Function to retrieve if the MMX2 CPU feature is enabled.
Returns:
Whether MMX2 is enabled or not.
Definition at line 542 of file lv_cpu.c.
Referenced by visual_mem_initialize().
int visual_cpu_has_neon (void)
Function to retrieve if the ARM Neon feature is enabled.
Returns:
Whether altivec is enabled or not.
Definition at line 605 of file lv_cpu.c.
int visual_cpu_has_sse (void)
Function to retrieve if the SSE CPU feature is enabled.
Returns:
Whether SSE is enabled or not.
Definition at line 550 of file lv_cpu.c.
Referenced by visual_math_vectorized_add_floats_const_float(), visual_math_vectorized_complex_to_norm(), visual_math_vectorized_complex_to_norm_scale(), visual_math_vectorized_multiplier_floats_const_float(), visual_math_vectorized_multiplier_floats_floats(), visual_math_vectorized_sqrt_floats(), and visual_math_vectorized_substract_floats_const_float().
int visual_cpu_has_sse2 (void)
Function to retrieve if the SSE2 CPU feature is enabled.
Returns:
Whether SSE2 is enabled or not.
Definition at line 557 of file lv_cpu.c.
int visual_cpu_has_tsc (void)
Function to retrieve if the tsc CPU feature is enabled.
Returns:
Whether tsc is enabled or not.
int visual_cpu_has_vfpv3 (void)
Function to retrieve if the ARM VFPv3 feature is enabled.
Returns:
Whether altivec is enabled or not.
Definition at line 597 of file lv_cpu.c.
void visual_cpu_initialize (void)
Initializes the VisCPU caps structure by detecting the CPU features and flags.
This is normally called by visual_init() and is needed by visual_mem_initialize() in order to detect the most optimal mem_copy and mem_set functions.
Definition at line 430 of file lv_cpu.c.