libvisual: VisActor
VisActor
Data Structures
struct _VisActor
The VisActor structure encapsulates the actor plugin and provides abstract interfaces to the actor.
struct _VisActorPluginEnviron
The VisActorPluginEnviron structure is the main environmental element for a VisActorPlugin.
struct _VisActorPlugin
The VisActorPlugin structure is the main data structure for the actor (visualisation) plugin.
Defines
#define VISUAL_ACTOR(obj) (VISUAL_CHECK_CAST ((obj), VisActor))
#define VISUAL_ACTOR_PLUGINENVIRON(obj) (VISUAL_CHECK_CAST ((obj), VisActorPluginEnviron))
#define VISUAL_ACTOR_PLUGIN(obj) (VISUAL_CHECK_CAST ((obj), VisActorPlugin))
#define VISUAL_ACTOR_PLUGIN_ENVIRON "Libvisual:core:actor:environ"
Name defination of the standard VisActorPluginEnviron element for an actor plugin.
Typedefs
typedef struct _VisActor VisActor
typedef struct
_VisActorPluginEnviron VisActorPluginEnviron
typedef struct _VisActorPlugin VisActorPlugin
typedef int(* VisPluginActorRequisitionFunc)(VisPluginData *plugin, int *width, int *height)
An actor plugin needs this signature for the requisition function.
typedef VisPalette *(* VisPluginActorPaletteFunc)(VisPluginData *plugin)
An actor plugin needs this signature for the palette function.
typedef int(* VisPluginActorRenderFunc)(VisPluginData *plugin, VisVideo *video, VisAudio *audio)
An actor plugin needs this signature for the render function.
Functions
VisPluginData * visual_actor_get_plugin (VisActor *actor)
Gives the encapsulated VisPluginData from a VisActor.
const char * visual_actor_get_next_by_name_gl (const char *name)
Gives the next actor plugin based on the name of a plugin but skips non GL plugins.
const char * visual_actor_get_prev_by_name_gl (const char *name)
Gives the previous actor plugin based on the name of a plugin but skips non GL plugins.
const char * visual_actor_get_next_by_name_nogl (const char *name)
Gives the next actor plugin based on the name of a plugin but skips GL plugins.
const char * visual_actor_get_prev_by_name_nogl (const char *name)
Gives the previous actor plugin based on the name of a plugin but skips GL plugins.
const char * visual_actor_get_next_by_name (const char *name)
Gives the next actor plugin based on the name of a plugin.
const char * visual_actor_get_prev_by_name (const char *name)
Gives the previous actor plugin based on the name of a plugin.
VisActor * visual_actor_new (const char *actorname)
Creates a new actor from name, the plugin will be loaded but won't be realized.
int visual_actor_init (VisActor *actor, const char *actorname)
Initializes a VisActor, this will set the allocated flag for the object to FALSE.
int visual_actor_realize (VisActor *actor)
Realize the VisActor.
VisSongInfo * visual_actor_get_songinfo (VisActor *actor)
Gives a pointer to the song info data within the VisActor.
VisPalette * visual_actor_get_palette (VisActor *actor)
Gives a pointer to the palette within the VisActor.
int visual_actor_video_negotiate (VisActor *actor, int rundepth, int noevent, int forced)
This function negotiates the VisActor with it's target video that is set by visual_actor_set_video.
int visual_actor_get_supported_depth (VisActor *actor)
Gives the by the plugin natively supported depths.
VisVideoAttributeOptions * visual_actor_get_video_attribute_options (VisActor *actor)
int visual_actor_set_video (VisActor *actor, VisVideo *video)
Used to connect the target display it's VisVideo structure to the VisActor.
int visual_actor_run (VisActor *actor, VisAudio *audio)
This is called to run a VisActor.
Define Documentation
#define VISUAL_ACTOR (obj) (VISUAL_CHECK_CAST ((obj), VisActor))
Definition at line 43 of file lv_actor.h.
#define VISUAL_ACTOR_PLUGIN (obj) (VISUAL_CHECK_CAST ((obj), VisActorPlugin))
Definition at line 45 of file lv_actor.h.
Referenced by visual_actor_get_next_by_name_gl(), visual_actor_get_next_by_name_nogl(), visual_actor_get_prev_by_name_gl(), and visual_actor_get_prev_by_name_nogl().
#define VISUAL_ACTOR_PLUGIN_ENVIRON "Libvisual:core:actor:environ"
Name defination of the standard VisActorPluginEnviron element for an actor plugin.
Definition at line 50 of file lv_actor.h.
Referenced by visual_actor_init().
#define VISUAL_ACTOR_PLUGINENVIRON (obj) (VISUAL_CHECK_CAST ((obj), VisActorPluginEnviron))
Definition at line 44 of file lv_actor.h.
Typedef Documentation
typedef struct _VisActor VisActor
Definition at line 52 of file lv_actor.h.
typedef struct _VisActorPlugin VisActorPlugin
Definition at line 54 of file lv_actor.h.
typedef struct _VisActorPluginEnviron VisActorPluginEnviron
Definition at line 53 of file lv_actor.h.
typedef VisPalette*(* VisPluginActorPaletteFunc)(VisPluginData *plugin)
An actor plugin needs this signature for the palette function.
The palette function is used to retrieve the desired palette from the plugin.
plugin Pointer to the VisPluginData instance structure.
Returns:
Pointer to the VisPalette used by the plugin, this should be a VisPalette with 256 VisColor entries, NULL is also allowed to be returned.
Definition at line 81 of file lv_actor.h.
typedef int(* VisPluginActorRenderFunc)(VisPluginData *plugin, VisVideo *video, VisAudio *audio)
An actor plugin needs this signature for the render function.
The render function is used to render the frame for the visualisation.
plugin Pointer to the VisPluginData instance structure.
video Pointer to the VisVideo containing all information about the display surface. Params like height and width won't suddenly change, this is always notified as an event so the plugin can adjust to the new dimension.
audio Pointer to the VisAudio containing all the data regarding the current audio sample.
Returns:
0 on succes -1 on error.
Definition at line 95 of file lv_actor.h.
typedef int(* VisPluginActorRequisitionFunc)(VisPluginData *plugin, int *width, int *height)
An actor plugin needs this signature for the requisition function.
The requisition function is used to determine the size required by the plugin for a given width/height value.
plugin Pointer to the VisPluginData instance structure.
width Pointer to an int containing the width requested, will be altered to the nearest supported width.
height Pointer to an int containing the height requested, will be altered to the nearest supported height.
Returns:
0 on succes -1 on error.
Definition at line 70 of file lv_actor.h.
Function Documentation
const char* visual_actor_get_next_by_name (const char * name)
Gives the next actor plugin based on the name of a plugin.
See also:
visual_actor_get_prev_by_name
Parameters:
name The name of the current plugin, or NULL to get the first.
Returns:
The name of the next plugin within the list.
Definition at line 197 of file lv_actor.cpp.
Referenced by visual_actor_get_next_by_name_gl(), and visual_actor_get_next_by_name_nogl().
const char* visual_actor_get_next_by_name_gl (const char * name)
Gives the next actor plugin based on the name of a plugin but skips non GL plugins.
See also:
visual_actor_get_prev_by_name_gl
Parameters:
name The name of the current plugin or NULL to get the first.
Returns:
The name of the next plugin within the list that is a GL plugin.
Definition at line 105 of file lv_actor.cpp.
const char* visual_actor_get_next_by_name_nogl (const char * name)
Gives the next actor plugin based on the name of a plugin but skips GL plugins.
See also:
visual_actor_get_prev_by_name_nogl
Parameters:
name The name of the current plugin or NULL to get the first.
Returns:
The name of the next plugin within the list that is not a GL plugin.
Definition at line 151 of file lv_actor.cpp.
VisPalette* visual_actor_get_palette (VisActor * actor)
Gives a pointer to the palette within the VisActor.
This can be needed to set a palette on the target display when it's in index mode.
See also:
VisPalette
Parameters:
actor Pointer to a VisActor of which the palette is needed.
Returns:
Pointer to the palette structure on succes or NULL on failure. Also it's possible that NULL is returned when the plugin is running in a full color mode or openGL. The returned palette is read only.
Definition at line 302 of file lv_actor.cpp.
Referenced by visual_actor_run(), and visual_bin_get_palette().
VisPluginData* visual_actor_get_plugin (VisActor * actor)
Gives the encapsulated VisPluginData from a VisActor.
Parameters:
actor Pointer of a VisActor of which the VisPluginData needs to be returned.
Returns:
VisPluginData that is encapsulated in the VisActor, possibly NULL.
Definition at line 100 of file lv_actor.cpp.
Referenced by visual_actor_get_palette(), and visual_actor_run().
const char* visual_actor_get_prev_by_name (const char * name)
Gives the previous actor plugin based on the name of a plugin.
See also:
visual_actor_get_next_by_name
Parameters:
name The name of the current plugin. or NULL to get the last.
Returns:
The name of the previous plugin within the list.
Definition at line 202 of file lv_actor.cpp.
Referenced by visual_actor_get_prev_by_name_gl(), and visual_actor_get_prev_by_name_nogl().
const char* visual_actor_get_prev_by_name_gl (const char * name)
Gives the previous actor plugin based on the name of a plugin but skips non GL plugins.
See also:
visual_actor_get_next_by_name_gl
Parameters:
name The name of the current plugin or NULL to get the last.
Returns:
The name of the previous plugin within the list that is a GL plugin.
Definition at line 128 of file lv_actor.cpp.
const char* visual_actor_get_prev_by_name_nogl (const char * name)
Gives the previous actor plugin based on the name of a plugin but skips GL plugins.
See also:
visual_actor_get_next_by_name_nogl
Parameters:
name The name of the current plugin or NULL to get the last.
Returns:
The name of the previous plugin within the list that is not a GL plugin.
Definition at line 174 of file lv_actor.cpp.
VisSongInfo* visual_actor_get_songinfo (VisActor * actor)
Gives a pointer to the song info data within the VisActor.
This song info data can be used to set name, artist and even coverart which can be used by the plugins and the framework itself.
See also:
VisSongInfo
Parameters:
actor Pointer to a VisActor of which the song info is needed.
Returns:
Pointer to the song info structure on succes or NULL on failure.
Definition at line 290 of file lv_actor.cpp.
int visual_actor_get_supported_depth (VisActor * actor)
Gives the by the plugin natively supported depths.
Parameters:
actor Pointer to a VisActor of which the supported depth of it's encapsulated plugin is requested.
Returns:
an OR value of the VISUAL_VIDEO_DEPTH_* values which can be checked against using AND on success, -VISUAL_ERROR_ACTOR_NULL, -VISUAL_ERROR_PLUGIN_NULL or -VISUAL_ERROR_ACTOR_PLUGIN_NULL on failure.
Definition at line 466 of file lv_actor.cpp.
Referenced by visual_actor_video_negotiate(), visual_bin_connect(), visual_bin_switch_actor_by_name(), and visual_bin_switch_finalize().
VisVideoAttributeOptions* visual_actor_get_video_attribute_options (VisActor * actor)
Definition at line 481 of file lv_actor.cpp.
int visual_actor_init (VisActor * actor, const char * actorname)
Initializes a VisActor, this will set the allocated flag for the object to FALSE.
Should not be used to reset a VisActor, or on a VisActor created by visual_actor_new().
See also:
visual_actor_new
Parameters:
actor Pointer to the VisActor that is initialized.
actorname The name of the plugin to load, or NULL to simply initialize a new actor.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_ACTOR_NULL or -VISUAL_ERROR_PLUGIN_NO_LIST on failure.
Definition at line 227 of file lv_actor.cpp.
Referenced by visual_actor_new().
VisActor* visual_actor_new (const char * actorname)
Creates a new actor from name, the plugin will be loaded but won't be realized.
Parameters:
actorname The name of the plugin to load, or NULL to simply allocate a new actor.
Returns:
A newly allocated VisActor, optionally containing a loaded plugin. Or NULL on failure.
Definition at line 207 of file lv_actor.cpp.
Referenced by visual_bin_connect_by_names(), and visual_bin_switch_actor_by_name().
int visual_actor_realize (VisActor * actor)
Realize the VisActor.
This also calls the plugin init function.
Parameters:
actor Pointer to a VisActor that needs to be realized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_ACTOR_NULL, -VISUAL_ERROR_PLUGIN_NULL or error values returned by visual_plugin_realize () on failure.
Definition at line 282 of file lv_actor.cpp.
Referenced by visual_bin_realize(), visual_bin_run(), and visual_bin_sync().
int visual_actor_run (VisActor * actor, VisAudio * audio)
This is called to run a VisActor.
It also pump it's events when needed, checks for new song events and also does the fitting and depth transformation actions when needed.
Every run cycle one frame is created, so this function needs to be used in the main draw loop of the application.
Parameters:
actor Pointer to a VisActor that needs to be runned.
audio Pointer to a VisAudio that contains all the audio data.
return VISUAL_OK on success, -VISUAL_ERROR_ACTOR_NULL, -VISUAL_ERROR_ACTOR_VIDEO_NULL, -VISUAL_ERROR_NULL or -VISUAL_ERROR_ACTOR_PLUGIN_NULL on failure.
Definition at line 505 of file lv_actor.cpp.
Referenced by visual_bin_run().
int visual_actor_set_video (VisActor * actor, VisVideo * video)
Used to connect the target display it's VisVideo structure to the VisActor.
Using the visual_video methods the screenbuffer, it's depth and dimension and optionally it's pitch can be set so the actor plugins know about their graphical environment and have a place to draw.
After this function it's most likely that visual_actor_video_negotiate needs to be called.
See also:
visual_video_new
visual_actor_video_negotiate
Parameters:
actor Pointer to a VisActor to which the VisVideo needs to be set.
video Pointer to a VisVideo which contains information about the target display and the pointer to it's screenbuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_ACTOR_NULL on failure.
Definition at line 496 of file lv_actor.cpp.
Referenced by visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), visual_bin_switch_finalize(), and visual_bin_sync().
int visual_actor_video_negotiate (VisActor * actor, int rundepth, int noevent, int forced)
This function negotiates the VisActor with it's target video that is set by visual_actor_set_video.
When needed it also sets up size fitting environment and depth transformation environment.
The function has a few extra arguments that are mainly to be used from within internal code.
This function needs to be called everytime there is a change within either the size or depth of the target video.
The main method of calling this function is: "visual_actor_video_negotiate (actor, 0, FALSE, FALSE)"
See also:
visual_actor_set_video
Parameters:
actor Pointer to a VisActor that needs negotiation.
rundepth An depth in the form of the VISUAL_VIDEO_DEPTH_* style when a depth is forced. This could be needed when for example a plugin has both a 8 bits and a 32 bits display method but while the target video is in 32 bits you still want to run the plugin in 8 bits. If this is desired the "forced" argument also needs to be set on TRUE.
noevent When set on TRUE this does only renegotiate depth transformation environments. For example when the target display was running in 32 bits and switched to 8 bits while the plugin was already in 8 bits it doesn't need an events, which possibly reinitializes the plugin.
forced This should be set if the rundepth argument is set, so it forces the plugin in a certain depth.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_ACTOR_NULL, -VISUAL_ERROR_PLUGIN_NULL, -VISUAL_ERROR_PLUGIN_REF_NULL, -VISUAL_ERROR_ACTOR_VIDEO_NULL or -VISUAL_ERROR_ACTOR_GL_NEGOTIATE on failure.
Definition at line 328 of file lv_actor.cpp.
Referenced by visual_bin_run(), visual_bin_switch_actor_by_name(), visual_bin_switch_finalize(), and visual_bin_sync().