libvisual: VisRingBuffer
VisRingBuffer
Data Structures
struct _VisRingBufferEntry
The VisRingBufferEntry data structure is an entry within the ringbuffer.
struct _VisRingBuffer
The VisRingBuffer data structure holding the ringbuffer.
Defines
#define VISUAL_RINGBUFFER(obj) (VISUAL_CHECK_CAST ((obj), VisRingBuffer))
#define VISUAL_RINGBUFFER_ENTRY(obj) (VISUAL_CHECK_CAST ((obj), VisRingBufferEntry))
Typedefs
typedef struct _VisRingBufferEntry VisRingBufferEntry
typedef struct _VisRingBuffer VisRingBuffer
typedef VisBuffer *(* VisRingBufferDataFunc)(VisRingBuffer *ringbuffer, VisRingBufferEntry *entry)
A VisRingBuffer data provider function needs this signature.
typedef void(* VisRingBufferDestroyFunc)(VisRingBufferEntry *entry)
typedef int(* VisRingBufferSizeFunc)(VisRingBuffer *ringbuffer, VisRingBufferEntry *entry)
Enumerations
enum VisRingBufferEntryType { VISUAL_RINGBUFFER_ENTRY_TYPE_NONE = 0, VISUAL_RINGBUFFER_ENTRY_TYPE_BUFFER = 1, VISUAL_RINGBUFFER_ENTRY_TYPE_FUNCTION = 2 }
Enum defining the VisRingBufferEntryTypes.
Functions
VisRingBuffer * visual_ringbuffer_new (void)
Creates a new VisRingBuffer structure.
int visual_ringbuffer_init (VisRingBuffer *ringbuffer)
int visual_ringbuffer_add_entry (VisRingBuffer *ringbuffer, VisRingBufferEntry *entry)
Adds a VisRingBufferEntry to the end of the ringbuffer.
int visual_ringbuffer_add_buffer (VisRingBuffer *ringbuffer, VisBuffer *buffer)
Adds a VisBuffer to the end of the ringbuffer.
int visual_ringbuffer_add_buffer_by_data (VisRingBuffer *ringbuffer, void *data, int nbytes)
Adds a portion of data to the ringbuffer of nbytes byte size.
int visual_ringbuffer_add_function (VisRingBuffer *ringbuffer, VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void *functiondata)
int visual_ringbuffer_get_size (VisRingBuffer *ringbuffer)
VisList * visual_ringbuffer_get_list (VisRingBuffer *ringbuffer)
Gets a list of all ringbuffer fragments that are currently in the ringbuffer.
int visual_ringbuffer_get_data (VisRingBuffer *ringbuffer, VisBuffer *data, int nbytes)
int visual_ringbuffer_get_data_offset (VisRingBuffer *ringbuffer, VisBuffer *data, int offset, int nbytes)
int visual_ringbuffer_get_data_from_end (VisRingBuffer *ringbuffer, VisBuffer *data, int nbytes)
int visual_ringbuffer_get_data_without_wrap (VisRingBuffer *ringbuffer, VisBuffer *data, int nbytes)
VisBuffer * visual_ringbuffer_get_data_new (VisRingBuffer *ringbuffer, int nbytes)
VisBuffer * visual_ringbuffer_get_data_new_without_wrap (VisRingBuffer *ringbuffer, int nbytes)
VisRingBufferEntry * visual_ringbuffer_entry_new (VisBuffer *buffer)
int visual_ringbuffer_entry_init (VisRingBufferEntry *entry, VisBuffer *buffer)
VisRingBufferEntry * visual_ringbuffer_entry_new_function (VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void *functiondata)
int visual_ringbuffer_entry_init_function (VisRingBufferEntry *entry, VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void *functiondata)
void * visual_ringbuffer_entry_get_functiondata (VisRingBufferEntry *entry)
Define Documentation
#define VISUAL_RINGBUFFER (obj) (VISUAL_CHECK_CAST ((obj), VisRingBuffer))
Definition at line 39 of file lv_ringbuffer.h.
#define VISUAL_RINGBUFFER_ENTRY (obj) (VISUAL_CHECK_CAST ((obj), VisRingBufferEntry))
Definition at line 40 of file lv_ringbuffer.h.
Typedef Documentation
typedef struct _VisRingBuffer VisRingBuffer
Definition at line 52 of file lv_ringbuffer.h.
typedef VisBuffer*(* VisRingBufferDataFunc)(VisRingBuffer *ringbuffer, VisRingBufferEntry *entry)
A VisRingBuffer data provider function needs this signature.
It can be used to provide ringbuffer entry data on runtime through a callback.
ringbuffer The VisRingBuffer data structure.
entry The VisRingBufferEntry to which the callback entry is connected.
Definition at line 61 of file lv_ringbuffer.h.
typedef void(* VisRingBufferDestroyFunc)(VisRingBufferEntry *entry)
Definition at line 63 of file lv_ringbuffer.h.
typedef struct _VisRingBufferEntry VisRingBufferEntry
Definition at line 51 of file lv_ringbuffer.h.
typedef int(* VisRingBufferSizeFunc)(VisRingBuffer *ringbuffer, VisRingBufferEntry *entry)
Definition at line 65 of file lv_ringbuffer.h.
Enumeration Type Documentation
enum VisRingBufferEntryType
Enum defining the VisRingBufferEntryTypes.
Enumerator:
VISUAL_RINGBUFFER_ENTRY_TYPE_NONE
State less entry.
VISUAL_RINGBUFFER_ENTRY_TYPE_BUFFER
Normal byte buffer.
VISUAL_RINGBUFFER_ENTRY_TYPE_FUNCTION
Data retrieval using a callback.
Definition at line 45 of file lv_ringbuffer.h.
Function Documentation
int visual_ringbuffer_add_buffer (VisRingBuffer * ringbuffer, VisBuffer * buffer)
Adds a VisBuffer to the end of the ringbuffer.
Parameters:
ringbuffer The VisRingBuffer to which the VisBuffer is added.
buffer The VisBuffer that is added to the VisRingBuffer.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_RINGBUFFER_NULL, -VISUAL_ERROR_RINGBUFFER_ENTRY_NULL on failure.
Definition at line 113 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_add_buffer_by_data().
int visual_ringbuffer_add_buffer_by_data (VisRingBuffer * ringbuffer, void * data, int nbytes)
Adds a portion of data to the ringbuffer of nbytes byte size.
Parameters:
ringbuffer Pointer to the ringbuffer to which the data is added.
data Pointer to the data that is added to the ringbuffer.
nbytes The size of the data that is added to the ringbuffer.
Returns:
VISUAL_OK on succes or -VISUAL_ERROR_RINGBUFFER_NULL, -VISUAL_ERROR_NULL, -VISUAL_ERROR_RINGBUFFER_ENTRY_NULL on failure.
Definition at line 124 of file lv_ringbuffer.c.
int visual_ringbuffer_add_entry (VisRingBuffer * ringbuffer, VisRingBufferEntry * entry)
Adds a VisRingBufferEntry to the end of the ringbuffer.
Parameters:
ringbuffer The VisRingBuffer to which the VisRingBufferEntry is added.
entry The VisRingBufferEntry that is added to the end of the ringbuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_RINGBUFFER_NULL or -VISUAL_ERROR_RINGBUFFER_ENTRY_NULL on failure.
Definition at line 103 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_add_buffer(), and visual_ringbuffer_add_function().
int visual_ringbuffer_add_function (VisRingBuffer * ringbuffer, VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void * functiondata)
Definition at line 136 of file lv_ringbuffer.c.
Referenced by visual_audio_samplepool_channel_add().
void* visual_ringbuffer_entry_get_functiondata (VisRingBufferEntry * entry)
Definition at line 495 of file lv_ringbuffer.c.
Referenced by visual_audio_samplepool_channel_flush_old().
int visual_ringbuffer_entry_init (VisRingBufferEntry * entry, VisBuffer * buffer)
Definition at line 432 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_entry_new().
int visual_ringbuffer_entry_init_function (VisRingBufferEntry * entry, VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void * functiondata)
Definition at line 471 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_entry_new_function().
VisRingBufferEntry* visual_ringbuffer_entry_new (VisBuffer * buffer)
Definition at line 417 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_add_buffer().
VisRingBufferEntry* visual_ringbuffer_entry_new_function (VisRingBufferDataFunc datafunc, VisRingBufferDestroyFunc destroyfunc, VisRingBufferSizeFunc sizefunc, void * functiondata)
Definition at line 452 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_add_function().
int visual_ringbuffer_get_data (VisRingBuffer * ringbuffer, VisBuffer * data, int nbytes)
Definition at line 193 of file lv_ringbuffer.c.
Referenced by visual_audio_analyze().
int visual_ringbuffer_get_data_from_end (VisRingBuffer * ringbuffer, VisBuffer * data, int nbytes)
Definition at line 362 of file lv_ringbuffer.c.
Referenced by visual_audio_get_sample().
VisBuffer* visual_ringbuffer_get_data_new (VisRingBuffer * ringbuffer, int nbytes)
Definition at line 386 of file lv_ringbuffer.c.
VisBuffer* visual_ringbuffer_get_data_new_without_wrap (VisRingBuffer * ringbuffer, int nbytes)
Definition at line 399 of file lv_ringbuffer.c.
int visual_ringbuffer_get_data_offset (VisRingBuffer * ringbuffer, VisBuffer * data, int offset, int nbytes)
Definition at line 198 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_get_data(), visual_ringbuffer_get_data_from_end(), visual_ringbuffer_get_data_new(), and visual_ringbuffer_get_data_without_wrap().
int visual_ringbuffer_get_data_without_wrap (VisRingBuffer * ringbuffer, VisBuffer * data, int nbytes)
Definition at line 373 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_get_data_new_without_wrap().
VisList* visual_ringbuffer_get_list (VisRingBuffer * ringbuffer)
Gets a list of all ringbuffer fragments that are currently in the ringbuffer.
Parameters:
ringbuffer Pointer to the VisRingBuffer of which the fragments are requested.
Returns:
A VisList of VisRingBufferEntry items or NULL on failure.
Definition at line 186 of file lv_ringbuffer.c.
Referenced by visual_audio_samplepool_channel_flush_old().
int visual_ringbuffer_get_size (VisRingBuffer * ringbuffer)
Definition at line 152 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_get_data_from_end(), visual_ringbuffer_get_data_new_without_wrap(), and visual_ringbuffer_get_data_without_wrap().
int visual_ringbuffer_init (VisRingBuffer * ringbuffer)
Definition at line 88 of file lv_ringbuffer.c.
Referenced by visual_ringbuffer_new().
VisRingBuffer* visual_ringbuffer_new (void)
Creates a new VisRingBuffer structure.
The VisRingBuffer system is a double linked ringbuffer implementation.
Returns:
A newly allocated VisRingBuffer.
Definition at line 73 of file lv_ringbuffer.c.
Referenced by visual_audio_samplepool_channel_init().