libvisual: VisThread
VisThread
Typedefs
typedef
typedefVISUAL_BEGIN_DECLS
struct _VisThread VisThread
The VisThread data structure and the VisThread subsystem is a wrapper system for native threading implementations.
typedef struct _VisMutex VisMutex
The VisMutex data structure and the VisMutex subsystem is a wrapper system for native thread locking implementations.
typedef void *(* VisThreadFunc)(void *data)
The function defination for a function that forms the base of a new VisThread when visual_thread_create is used.
Functions
int visual_thread_initialize (void)
Initializes the VisThread subsystem.
int visual_thread_is_initialized (void)
Request if VisThread is initialized or not.
int visual_thread_is_supported (void)
Is used to check if threading is supported.
VisThread * visual_thread_create (VisThreadFunc func, void *data, int joinable)
Creates a new VisThread that is used in threading.
int visual_thread_free (VisThread *thread)
After a VisThread is not needed anylonger it needs to be freed using this function.
void * visual_thread_join (VisThread *thread)
Joins a VisThread with another.
void visual_thread_exit (void *retval)
Exits a VisThread, this will terminate the thread.
void visual_thread_yield (void)
Yield the current VisThread so another gets time.
VisMutex * visual_mutex_new (void)
Creates a new VisMutex that is used to do thread locking so data can be synchronized.
int visual_mutex_free (VisMutex *mutex)
A VisMutex is allocated to have more flexibility with the actual thread backend.
int visual_mutex_init (VisMutex *mutex)
A VisMutex that has not been allocated using visual_mutex_new () can be initialized using this function.
int visual_mutex_lock (VisMutex *mutex)
Locks a VisMutex, with the VisMutex locks checked right, only one thread can access the area at once.
int visual_mutex_trylock (VisMutex *mutex)
Tries to lock a VisMutex, however instead of visual_mutex_lock it does not block on failure.
int visual_mutex_unlock (VisMutex *mutex)
Unlocks a VisMutex so other threads that use the same lock can now enter the critical area.
Typedef Documentation
typedef struct _VisMutex VisMutex
The VisMutex data structure and the VisMutex subsystem is a wrapper system for native thread locking implementations.
Definition at line 32 of file lv_thread.h.
typedef typedefVISUAL_BEGIN_DECLS struct _VisThread VisThread
The VisThread data structure and the VisThread subsystem is a wrapper system for native threading implementations.
Definition at line 26 of file lv_thread.h.
typedef void*(* VisThreadFunc)(void *data)
The function defination for a function that forms the base of a new VisThread when visual_thread_create is used.
See also:
visual_thread_create
data Pointer that can contains the private data from the visual_thread_create function.
Returns:
Pointer to the data when a thread is joined.
Definition at line 44 of file lv_thread.h.
Function Documentation
int visual_mutex_free (VisMutex * mutex)
A VisMutex is allocated to have more flexibility with the actual thread backend.
Thus they need to be freed as well.
Parameters:
mutex Pointer to the VisMutex that needs to be freed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MUTEX_NULL on failure.
Definition at line 82 of file lv_thread_disabled.c.
int visual_mutex_init (VisMutex * mutex)
A VisMutex that has not been allocated using visual_mutex_new () can be initialized using this function.
You can use non allocated VisMutex variables in this context by giving a reference to them.
Parameters:
mutex Pointer to the VisMutex which needs to be initialized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MUTEX_NULL, -VISUAL_ERROR_THREAD_NOT_INTIALIZED, -VISUAL_ERROR_THREAD_NOT_SUPPORTED or -VISUAL_ERROR_THREAD_NOT_ENABLED on failure.
int visual_mutex_lock (VisMutex * mutex)
Locks a VisMutex, with the VisMutex locks checked right, only one thread can access the area at once.
This will block if the thread is already locked.
Parameters:
mutex Pointer to the VisMutex to register the lock.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MUTEX_NULL, -VISUAL_ERROR_MUTEX_LOCK_FAILURE, -VISUAL_ERROR_THREAD_NOT_INITIALIZED, -VISUAL_ERROR_THREAD_NOT_SUPPORTED, -VISUAL_ERROR_THREAD_NOT_ENABLED on failure.
Definition at line 89 of file lv_thread_disabled.c.
VisMutex* visual_mutex_new (void)
Creates a new VisMutex that is used to do thread locking so data can be synchronized.
Returns:
A newly allocated VisMutex that can be used with the visual_mutex_lock and visual_mutex_unlock functions or NULL on failure.
Definition at line 75 of file lv_thread_disabled.c.
int visual_mutex_trylock (VisMutex * mutex)
Tries to lock a VisMutex, however instead of visual_mutex_lock it does not block on failure.
but returns instead with -VISUAL_ERROR_MUTEX_TRYLOCK_FAILURE as error value.
Parameters:
mutex Pointer to the VisMutex that needs to be locked.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MUTEX_NULL, -VISUAL_ERROR_MUTEX_TRYLOCK_FAILURE, -VISUAL_ERROR_THREAD_NOT_INITIALIZED, -VISUAL_ERROR_THREAD_NOT_SUPPORTED or -VISUAL_ERROR_THREAD_NOT_ENABLED on failure.
Definition at line 96 of file lv_thread_disabled.c.
int visual_mutex_unlock (VisMutex * mutex)
Unlocks a VisMutex so other threads that use the same lock can now enter the critical area.
Parameters:
mutex Pointer to the VisMutex that is unlocked.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MUTEX_NULL, -VISUAL_ERROR_MUTEX_UNLOCK_FAILURE. -VISUAL_ERROR_THREAD_NOT_INITIALIZED, -VISUAL_ERROR_THREAD_NOT_SUPPORTED or -VISUAL_ERROR_THREAD_NOT_ENABLED on failure.
Definition at line 103 of file lv_thread_disabled.c.
VisThread* visual_thread_create (VisThreadFunc func, void * data, int joinable)
Creates a new VisThread that is used in threading.
Parameters:
func The threading function.
data The private data that is send to the threading function.
joinable Flag that contains whatever the thread can be joined or not.
Returns:
A newly allocated VisThread, or NULL on failure.
Definition at line 44 of file lv_thread_disabled.c.
void visual_thread_exit (void * retval)
Exits a VisThread, this will terminate the thread.
Parameters:
retval The return value that is catched by the visual_thread_join function.
Definition at line 65 of file lv_thread_disabled.c.
int visual_thread_free (VisThread * thread)
After a VisThread is not needed anylonger it needs to be freed using this function.
Parameters:
thread The VisThread that needs to be freed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_THREAD_NULL or error values returned by visual_mem_free on failure.
Definition at line 51 of file lv_thread_disabled.c.
int visual_thread_initialize (void)
Initializes the VisThread subsystem.
This function needs to be called before VisThread can be used. Also this function is called from within visual_init().
Returns:
TRUE if initialized, FALSE if not initialized.
Definition at line 29 of file lv_thread_disabled.c.
int visual_thread_is_initialized (void)
Request if VisThread is initialized or not.
This function should not be confused with visual_thread_is_supported().
Returns:
TRUE if initialized, FALSE if not initialized.
Definition at line 34 of file lv_thread_disabled.c.
Referenced by visual_mutex_free(), visual_mutex_lock(), visual_mutex_new(), visual_mutex_trylock(), visual_mutex_unlock(), visual_thread_create(), visual_thread_exit(), visual_thread_free(), visual_thread_join(), and visual_thread_yield().
int visual_thread_is_supported (void)
Is used to check if threading is supported.
When threading is used this should always be checked, it's possible to disable threads from within the code, so no #ifdefs should be used.
Returns:
TRUE if threading is supported or FALSE if not.
Definition at line 39 of file lv_thread_disabled.c.
void* visual_thread_join (VisThread * thread)
Joins a VisThread with another.
Parameters:
thread The VisThread that is about to be joined.
Returns:
Possible result that was passed to visual_thread_exit as retval or NULL.
Definition at line 58 of file lv_thread_disabled.c.
void visual_thread_yield (void)
Yield the current VisThread so another gets time.
Definition at line 70 of file lv_thread_disabled.c.