libvisual: VisEvent
VisEvent
Data Structures
struct _VisEventKeyboard
Keyboard event data structure.
struct _VisEventMouseMotion
Mouse movement event data structure.
struct _VisEventMouseButton
Mouse button event data structure.
struct _VisEventResize
Dimension change event data structure.
struct _VisEventNewSong
Song change event data structure.
struct _VisEventQuit
Quit event data structure.
struct _VisEventVisibility
Visibility event data structure.
struct _VisEventGeneric
Generic event data structure.
struct _VisEventParam
Param change event data structure.
struct _VisEvent
The main event data structure.
struct _VisEventQueue
The event queue data structure.
Defines
#define VISUAL_EVENT_KEYBOARD(obj) (VISUAL_CHECK_CAST ((obj), VisEventKeyboard))
#define VISUAL_EVENT_MOUSEMOTION(obj) (VISUAL_CHECK_CAST ((obj), VisEventMouseMotion))
#define VISUAL_EVENT_MOUSEBUTTON(obj) (VISUAL_CHECK_CAST ((obj), VisEventMouseButton))
#define VISUAL_EVENT_RESIZE(obj) (VISUAL_CHECK_CAST ((obj), VisEventResize))
#define VISUAL_EVENT_NEWSONG(obj) (VISUAL_CHECK_CAST ((obj), VisEventNewSong))
#define VISUAL_EVENT_QUIT(obj) (VISUAL_CHECK_CAST ((obj), VisEventQuit))
#define VISUAL_EVENT_VISIBILITY(obj) (VISUAL_CHECK_CAST ((obj), VisEventVisibility))
#define VISUAL_EVENT_GENERIC(obj) (VISUAL_CHECK_CAST ((obj), VisEventGeneric))
#define VISUAL_EVENT_PARAM(obj) (VISUAL_CHECK_CAST ((obj), VisEventParam))
#define VISUAL_EVENT(obj) (VISUAL_CHECK_CAST ((obj), VisEvent))
#define VISUAL_EVENTQUEUE(obj) (VISUAL_CHECK_CAST ((obj), VisEventQueue))
#define VISUAL_EVENT_MAXEVENTS 256
Number of events allowed in the queue.
Typedefs
typedef struct _VisEventKeyboard VisEventKeyboard
typedef struct _VisEventMouseMotion VisEventMouseMotion
typedef struct _VisEventMouseButton VisEventMouseButton
typedef struct _VisEventResize VisEventResize
typedef struct _VisEventNewSong VisEventNewSong
typedef struct _VisEventQuit VisEventQuit
typedef struct _VisEventVisibility VisEventVisibility
typedef struct _VisEventGeneric VisEventGeneric
typedef struct _VisEventParam VisEventParam
typedef struct _VisEvent VisEvent
typedef struct _VisEventQueue VisEventQueue
Enumerations
enum VisEventType {
VISUAL_EVENT_NOEVENT, VISUAL_EVENT_KEYDOWN, VISUAL_EVENT_KEYUP, VISUAL_EVENT_MOUSEMOTION,
VISUAL_EVENT_MOUSEBUTTONDOWN, VISUAL_EVENT_MOUSEBUTTONUP, VISUAL_EVENT_NEWSONG, VISUAL_EVENT_RESIZE,
VISUAL_EVENT_PARAM, VISUAL_EVENT_QUIT, VISUAL_EVENT_GENERIC, VISUAL_EVENT_VISIBILITY,
VISUAL_EVENT_LAST = 0xffffff
}
Used to define what kind of event is emitted by the VisEvent system.
enum VisKeyState { VISUAL_KEY_DOWN, VISUAL_KEY_UP }
Used to define key states within the VisEvent system.
enum VisMouseState { VISUAL_MOUSE_DOWN, VISUAL_MOUSE_UP }
Used to define mouse button states within the VisEvent system.
Functions
VisEvent * visual_event_new (void)
Creates a new VisEvent structure.
int visual_event_init (VisEvent *event)
int visual_event_copy (VisEvent *dest, VisEvent *src)
VisEventQueue * visual_event_queue_new (void)
Creates a new VisEventQueue data structure.
int visual_event_queue_init (VisEventQueue *eventqueue)
int visual_event_queue_poll (VisEventQueue *eventqueue, VisEvent *event)
Polls for new events.
int visual_event_queue_poll_by_reference (VisEventQueue *eventqueue, VisEvent **event)
int visual_event_queue_add (VisEventQueue *eventqueue, VisEvent *event)
Adds an event to the event queue.
int visual_event_queue_add_keyboard (VisEventQueue *eventqueue, VisKey keysym, int keymod, VisKeyState state)
Adds a new keyboard event to the event queue.
int visual_event_queue_add_mousemotion (VisEventQueue *eventqueue, int x, int y)
Adds a new mouse movement event to the event queue.
int visual_event_queue_add_mousebutton (VisEventQueue *eventqueue, int button, VisMouseState state, int x, int y)
Adds a new mouse button event to the event queue.
int visual_event_queue_add_resize (VisEventQueue *eventqueue, VisVideo *video, int width, int height)
Adds a new dimension change event to the event queue.
int visual_event_queue_add_newsong (VisEventQueue *eventqueue, VisSongInfo *songinfo)
Adds a new song change event to the event queue.
int visual_event_queue_add_param (VisEventQueue *eventqueue, void *param)
Adds a new parameter change event to the event queue.
int visual_event_queue_add_quit (VisEventQueue *eventqueue, int pass_zero_please)
Adds a new quit event to the event queue.
int visual_event_queue_add_visibility (VisEventQueue *eventqueue, int is_visible)
Adds a new visibility event to the event queue.
int visual_event_queue_add_generic (VisEventQueue *eventqueue, int eid, int param_int, void *param_ptr)
Adds a new generic event to the event queue.
Define Documentation
#define VISUAL_EVENT (obj) (VISUAL_CHECK_CAST ((obj), VisEvent))
Definition at line 25 of file lv_event.h.
#define VISUAL_EVENT_GENERIC (obj) (VISUAL_CHECK_CAST ((obj), VisEventGeneric))
Definition at line 23 of file lv_event.h.
#define VISUAL_EVENT_KEYBOARD (obj) (VISUAL_CHECK_CAST ((obj), VisEventKeyboard))
Definition at line 16 of file lv_event.h.
#define VISUAL_EVENT_MAXEVENTS 256
Number of events allowed in the queue.
Definition at line 31 of file lv_event.h.
Referenced by visual_event_queue_add().
#define VISUAL_EVENT_MOUSEBUTTON (obj) (VISUAL_CHECK_CAST ((obj), VisEventMouseButton))
Definition at line 18 of file lv_event.h.
#define VISUAL_EVENT_MOUSEMOTION (obj) (VISUAL_CHECK_CAST ((obj), VisEventMouseMotion))
Definition at line 17 of file lv_event.h.
#define VISUAL_EVENT_NEWSONG (obj) (VISUAL_CHECK_CAST ((obj), VisEventNewSong))
Definition at line 20 of file lv_event.h.
#define VISUAL_EVENT_PARAM (obj) (VISUAL_CHECK_CAST ((obj), VisEventParam))
Definition at line 24 of file lv_event.h.
#define VISUAL_EVENT_QUIT (obj) (VISUAL_CHECK_CAST ((obj), VisEventQuit))
Definition at line 21 of file lv_event.h.
#define VISUAL_EVENT_RESIZE (obj) (VISUAL_CHECK_CAST ((obj), VisEventResize))
Definition at line 19 of file lv_event.h.
#define VISUAL_EVENT_VISIBILITY (obj) (VISUAL_CHECK_CAST ((obj), VisEventVisibility))
Definition at line 22 of file lv_event.h.
#define VISUAL_EVENTQUEUE (obj) (VISUAL_CHECK_CAST ((obj), VisEventQueue))
Definition at line 26 of file lv_event.h.
Typedef Documentation
typedef struct _VisEvent VisEvent
Definition at line 79 of file lv_event.h.
typedef struct _VisEventGeneric VisEventGeneric
Definition at line 77 of file lv_event.h.
typedef struct _VisEventKeyboard VisEventKeyboard
Definition at line 70 of file lv_event.h.
typedef struct _VisEventMouseButton VisEventMouseButton
Definition at line 72 of file lv_event.h.
typedef struct _VisEventMouseMotion VisEventMouseMotion
Definition at line 71 of file lv_event.h.
typedef struct _VisEventNewSong VisEventNewSong
Definition at line 74 of file lv_event.h.
typedef struct _VisEventParam VisEventParam
Definition at line 78 of file lv_event.h.
typedef struct _VisEventQueue VisEventQueue
Definition at line 80 of file lv_event.h.
typedef struct _VisEventQuit VisEventQuit
Definition at line 75 of file lv_event.h.
typedef struct _VisEventResize VisEventResize
Definition at line 73 of file lv_event.h.
typedef struct _VisEventVisibility VisEventVisibility
Definition at line 76 of file lv_event.h.
Enumeration Type Documentation
enum VisEventType
Used to define what kind of event is emitted by the VisEvent system.
Enumerator:
VISUAL_EVENT_NOEVENT
No event.
VISUAL_EVENT_KEYDOWN
Keyboard key pressed event.
VISUAL_EVENT_KEYUP
Keyboard key released event.
VISUAL_EVENT_MOUSEMOTION
Mouse movement event.
VISUAL_EVENT_MOUSEBUTTONDOWN
Mouse button pressed event.
VISUAL_EVENT_MOUSEBUTTONUP
Mouse button released event.
VISUAL_EVENT_NEWSONG
Song change event.
VISUAL_EVENT_RESIZE
Window dimension change event.
VISUAL_EVENT_PARAM
Param set event, gets emitted when a parameter has been changed.
VISUAL_EVENT_QUIT
Quit event, Should get emitted when a program is about to quit.
VISUAL_EVENT_GENERIC
A Generic event.
Libvisual has nothing to do with it, this can be used for custom events.
VISUAL_EVENT_VISIBILITY
A visibility event.
Will be emited by lvdisplay (?) or app itself when window becomes (in)visible
VISUAL_EVENT_LAST
last event number.
Libvisual & friends will never use ids greater than this
Definition at line 36 of file lv_event.h.
enum VisKeyState
Used to define key states within the VisEvent system.
Enumerator:
VISUAL_KEY_DOWN
Key is pressed.
VISUAL_KEY_UP
Key is released.
Definition at line 56 of file lv_event.h.
enum VisMouseState
Used to define mouse button states within the VisEvent system.
Enumerator:
VISUAL_MOUSE_DOWN
Mouse button is pressed.
VISUAL_MOUSE_UP
Mouse button is released.
Definition at line 64 of file lv_event.h.
Function Documentation
int visual_event_copy (VisEvent * dest, VisEvent * src)
Definition at line 85 of file lv_event.c.
Referenced by visual_event_queue_poll(), and visual_event_queue_poll_by_reference().
int visual_event_init (VisEvent * event)
Definition at line 70 of file lv_event.c.
Referenced by visual_event_new(), and visual_event_queue_init().
VisEvent* visual_event_new (void)
Creates a new VisEvent structure.
See also:
visual_actor_get_eventqueue
Returns:
A newly allocated VisEvent
Definition at line 55 of file lv_event.c.
Referenced by visual_event_queue_add_generic(), visual_event_queue_add_keyboard(), visual_event_queue_add_mousebutton(), visual_event_queue_add_mousemotion(), visual_event_queue_add_newsong(), visual_event_queue_add_param(), visual_event_queue_add_quit(), visual_event_queue_add_visibility(), and visual_event_queue_poll_by_reference().
int visual_event_queue_add (VisEventQueue * eventqueue, VisEvent * event)
Adds an event to the event queue.
Add new VisEvents into the VisEventQueue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
event Pointer to a VisEvent that needs to be added to the queue.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or -VISUAL_ERROR_EVENT_NULL on failure.
Definition at line 181 of file lv_event.c.
Referenced by visual_event_queue_add_generic(), visual_event_queue_add_keyboard(), visual_event_queue_add_mousebutton(), visual_event_queue_add_mousemotion(), visual_event_queue_add_newsong(), visual_event_queue_add_param(), visual_event_queue_add_quit(), and visual_event_queue_add_visibility().
int visual_event_queue_add_generic (VisEventQueue * eventqueue, int eid, int param_int, void * param_ptr)
Adds a new generic event to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
eid ID of the custom event..
param_int Integer value for the custom event.
param_ptr Pointer to data for the custom event..
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 354 of file lv_event.c.
int visual_event_queue_add_keyboard (VisEventQueue * eventqueue, VisKey keysym, int keymod, VisKeyState state)
Adds a new keyboard event to the event queue.
By giving keyboard state information a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
keysym A keysym from the VisKey enumerate to set the key to which the event relates.
keymod Key modifier information from the VisKeyMod enumerate.
state Contains information about whatever the key is down or up.
return VISUAL_OK on succes -VISUAL_ERROR_EVENT_QUEUE_NULL, -VISUAL_ERROR_EVENT_NULL or error values returned by visual_event_queue_add on failure.
Definition at line 202 of file lv_event.c.
int visual_event_queue_add_mousebutton (VisEventQueue * eventqueue, int button, VisMouseState state, int x, int y)
Adds a new mouse button event to the event queue.
By giving a mouse button index number and a mouse button key state a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
button Index that indicates to which mouse button the state relates.
state Contains information about whatever the button is down or up
x Absolute X value for the mouse location.
y Absolute Y value for the mouse location.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 251 of file lv_event.c.
int visual_event_queue_add_mousemotion (VisEventQueue * eventqueue, int x, int y)
Adds a new mouse movement event to the event queue.
By giving absolute X and Y coordinates for the mouse a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
x Absolute X value for the mouse location.
y Absolute Y value for the mouse location.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 228 of file lv_event.c.
int visual_event_queue_add_newsong (VisEventQueue * eventqueue, VisSongInfo * songinfo)
Adds a new song change event to the event queue.
By giving a pointer to the new VisSongInfo structure a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
songinfo Pointer to the VisSongInfo containing all the new song information.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL, -VISUAL_ERROR_SONGINFO_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 295 of file lv_event.c.
Referenced by visual_actor_run().
int visual_event_queue_add_param (VisEventQueue * eventqueue, void * param)
Adds a new parameter change event to the event queue.
By giving the pointer to the VisParamEntry structure a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
param Pointer to the VisParamEntry containing the parameter that has been changed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL, -VISUAL_ERROR_PARAM_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 312 of file lv_event.c.
Referenced by visual_param_entry_changed().
int visual_event_queue_add_quit (VisEventQueue * eventqueue, int pass_zero_please)
Adds a new quit event to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
pass_zero_please Might be used in the future, but for now just pass.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 328 of file lv_event.c.
int visual_event_queue_add_resize (VisEventQueue * eventqueue, VisVideo * video, int width, int height)
Adds a new dimension change event to the event queue.
By giving a pointer to the VisVideo containing all the surface information and new width and height a new VisEvent will be created and added to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
video Pointer to the VisVideo containing all the display information, also used for negotiation so values can change within the VisVideo structure.
width The width for the new surface.
height The height for the new surface.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL on failure.
Definition at line 275 of file lv_event.c.
Referenced by visual_transform_video_negotiate().
int visual_event_queue_add_visibility (VisEventQueue * eventqueue, int is_visible)
Adds a new visibility event to the event queue.
Parameters:
eventqueue Pointer to the VisEventQueue to which new events are added.
is_visible TRUE when visible, FALSE when not visible.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_EVENT_QUEUE_NULL or error values returned by visual_event_queue_add () on failure.
Definition at line 340 of file lv_event.c.
int visual_event_queue_init (VisEventQueue * eventqueue)
Definition at line 111 of file lv_event.c.
Referenced by visual_event_queue_new().
VisEventQueue* visual_event_queue_new (void)
Creates a new VisEventQueue data structure.
Returns:
Newly allocated VisEventQueue.
Definition at line 96 of file lv_event.c.
int visual_event_queue_poll (VisEventQueue * eventqueue, VisEvent * event)
Polls for new events.
Looks at the event queue for new events and deletes them from the queue while loading them into the event argument.
Parameters:
eventqueue Pointer to a VisEventQueue from which new events should be taken.
event Pointer to a VisEvent in which the new events should be loaded.
Returns:
TRUE when events are handled and FALSE when the queue is out of events.
Definition at line 132 of file lv_event.c.
int visual_event_queue_poll_by_reference (VisEventQueue * eventqueue, VisEvent ** event)
Definition at line 149 of file lv_event.c.
Referenced by visual_event_queue_poll().