libvisual: VisObject
VisObject
Data Structures
struct _VisObject
The VisObject structure contains all the VisObject housekeeping data like refcounting and a pointer to the VisObjectDtorFunc.
Defines
#define VISUAL_OBJECT(obj) (VISUAL_CHECK_CAST ((obj), VisObject))
#define visual_object_clean(object, struct_type) visual_mem_set ((uint8_t *) (object) + sizeof (VisObject), 0, sizeof (struct_type) - sizeof (VisObject))
Macro that will set the data after the VisObject data to 0.
#define visual_object_copy_data(dest, src, struct_type)
Macro that will copy the data after the VisObject data to another VisObject.
Typedefs
typedef struct _VisObject VisObject
typedef int(* VisObjectDtorFunc)(VisObject *object)
The function defination for an object destructor.
Functions
int visual_object_collection_destroyer (void *data)
This function is a global VisListDestroyerFunc handler that unrefs VisObjects.
VisObject * visual_object_new (void)
Creates a new VisObject structure.
int visual_object_free (VisObject *object)
Frees the VisObject.
int visual_object_destroy (VisObject *object)
Destroys the VisObject.
int visual_object_initialize (VisObject *object, int allocated, VisObjectDtorFunc dtor)
Initializes a VisObject for usage.
int visual_object_clear (VisObject *object)
Clears a VisObject.
int visual_object_set_dtor (VisObject *object, VisObjectDtorFunc dtor)
Sets the destructor function to a VisObject.
int visual_object_set_allocated (VisObject *object, int allocated)
Sets whether a VisObject is allocated or not.
int visual_object_set_refcount (VisObject *object, int refcount)
Sets the refcount to a certain number.
int visual_object_ref (VisObject *object)
Increases the reference counter for a VisObject.
int visual_object_unref (VisObject *object)
Decreases the reference counter for a VisObject.
int visual_object_set_private (VisObject *object, void *priv)
Sets the private data pointer to a VisObject.
void * visual_object_get_private (VisObject *object)
Retrieves the private data from a VisObject.
Define Documentation
#define VISUAL_OBJECT (obj) (VISUAL_CHECK_CAST ((obj), VisObject))
Definition at line 38 of file lv_object.h.
Referenced by visual_actor_init(), visual_actor_new(), visual_actor_video_negotiate(), visual_audio_analyze(), visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), visual_audio_get_spectrum(), visual_audio_init(), visual_audio_new(), visual_audio_sample_init(), visual_audio_sample_new(), visual_audio_sample_transform_format(), visual_audio_sample_transform_rate(), visual_audio_samplepool_channel_init(), visual_audio_samplepool_channel_new(), visual_audio_samplepool_init(), visual_audio_samplepool_new(), visual_beat_adv_new(), visual_beat_new(), visual_bin_new(), visual_bin_set_morph_by_name(), visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), visual_bin_switch_finalize(), visual_bitmap_load_new_video(), visual_buffer_init(), visual_buffer_new(), visual_collection_iter_dtor(), visual_collection_iter_init(), visual_collection_iter_new(), visual_config_registry_new(), visual_config_registry_open(), visual_config_registry_remove(), visual_config_registry_section_new(), visual_event_init(), visual_event_new(), visual_event_queue_add(), visual_event_queue_init(), visual_event_queue_new(), visual_event_queue_poll(), visual_input_init(), visual_input_new(), visual_input_run(), visual_input_set_callback(), visual_list_init(), visual_list_new(), visual_morph_init(), visual_morph_new(), visual_object_collection_destroyer(), visual_param_container_new(), visual_param_entry_add_callback(), visual_param_entry_new(), visual_param_entry_notify_callbacks(), visual_param_entry_remove_callback(), visual_param_entry_set_collection(), visual_plugin_environ_new(), visual_plugin_environ_remove(), visual_plugin_get_reference(), visual_plugin_info_new(), visual_plugin_load(), visual_plugin_new(), visual_plugin_ref_new(), visual_plugin_unload(), visual_ringbuffer_entry_init(), visual_ringbuffer_entry_init_function(), visual_ringbuffer_entry_new(), visual_ringbuffer_entry_new_function(), visual_ringbuffer_get_data_offset(), visual_ringbuffer_get_size(), visual_ringbuffer_init(), visual_ringbuffer_new(), visual_transform_init(), visual_transform_new(), visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_alpha_rectangle(), visual_video_fill_color_rectangle(), visual_video_init(), visual_video_new(), visual_video_new_with_buffer(), visual_video_region_sub(), and visual_video_scale_depth().
#define visual_object_clean (object, struct_type) visual_mem_set ((uint8_t *) (object) + sizeof (VisObject), 0, sizeof (struct_type) - sizeof (VisObject))
Macro that will set the data after the VisObject data to 0.
Definition at line 215 of file lv_object.h.
Referenced by visual_event_init(), and visual_event_queue_init().
#define visual_object_copy_data (dest, src, struct_type)
Value:
visual_mem_copy ((uint8_t *) (dest) + sizeof (VisObject),   \
            (uint8_t *) (src) + sizeof (VisObject),     \
            sizeof (struct_type) - sizeof (VisObject))
Macro that will copy the data after the VisObject data to another VisObject.
Definition at line 223 of file lv_object.h.
Referenced by visual_event_copy().
Typedef Documentation
typedef struct _VisObject VisObject
Definition at line 40 of file lv_object.h.
typedef int(* VisObjectDtorFunc)(VisObject *object)
The function defination for an object destructor.
This can be assigned to any VisObject and is mostly used for internal usage or by support libraries. Keep in mind that this should not free the VisObject itself. This is done in the visual_object_destroy function itself.
The destructor function should be safe to enter more than once, the object always contains the object however make sure that freed members are set to NULL and that it's checked.
object The VisObject that is passed to the destructor.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_DTOR_FAILED on failure.
Definition at line 54 of file lv_object.h.
Function Documentation
int visual_object_clear (VisObject * object)
Clears a VisObject.
This basically means setting it's private to NULL and it's refcount to 0. This won't unref, or destroy the object and this function is mostly used for object creation.
Parameters:
object Pointer to a VisObject that is to be cleared.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 84 of file lv_object.c.
Referenced by visual_actor_init(), visual_audio_init(), visual_audio_sample_init(), visual_audio_samplepool_channel_init(), visual_audio_samplepool_init(), visual_buffer_init(), visual_collection_iter_init(), visual_event_init(), visual_event_queue_init(), visual_input_init(), visual_list_init(), visual_morph_init(), visual_object_initialize(), visual_ringbuffer_entry_init(), visual_ringbuffer_entry_init_function(), visual_ringbuffer_init(), visual_transform_init(), and visual_video_init().
int visual_object_collection_destroyer (void * data)
This function is a global VisListDestroyerFunc handler that unrefs VisObjects.
Parameters:
data Pointer to the VisObject that needs to be unrefed
Returns:
VISUAL_OK on success, or error failures by visual_object_unref() on failure.
Definition at line 28 of file lv_object.c.
Referenced by visual_audio_samplepool_init(), visual_config_registry_new(), visual_param_container_new(), visual_param_entry_new(), and visual_ringbuffer_init().
int visual_object_destroy (VisObject * object)
Destroys the VisObject.
This does destruct the VisObject by using the dtor function if it's set and also frees the memory it's using. It's valid to pass non allocated VisObjects, the function will recognize this by a flag that is set in the VisObject.
Parameters:
object Pointer to a VisObject that needs to be destroyed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL or error values returned byvisual_object_free on failure.
Definition at line 57 of file lv_object.c.
Referenced by visual_object_unref().
int visual_object_free (VisObject * object)
Frees the VisObject.
This does not destroy the object itself but only releases the memory it's using.
Parameters:
object Pointer to a VisObject that needs to be freed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL, -VISUAL_ERROR_OBJECT_NOT_ALLOCATED or error values returned by visual_mem_free on failure.
Definition at line 49 of file lv_object.c.
Referenced by visual_object_destroy().
void* visual_object_get_private (VisObject * object)
Retrieves the private data from a VisObject.
Parameters:
object Pointer to a VisObject from which the private data is requested.
Returns:
Pointer to the private data or NULL.
Definition at line 157 of file lv_object.c.
Referenced by visual_input_run(), and visual_param_entry_notify_callbacks().
int visual_object_initialize (VisObject * object, int allocated, VisObjectDtorFunc dtor)
Initializes a VisObject for usage.
This also ups the refcount by one, so this function really is for initial object creation.
Parameters:
object Pointer to a VisObject that is initialized.
allocated Flag to indicate if the VisObject itself is an allocated piece of memory.
dtor The destructor function, that is used to destroy the VisObject when it loses all references or when it's being destroyed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 70 of file lv_object.c.
Referenced by visual_actor_init(), visual_beat_adv_new(), visual_beat_new(), visual_bin_new(), visual_config_registry_new(), visual_config_registry_section_new(), visual_param_container_new(), visual_param_entry_add_callback(), visual_param_entry_new(), visual_plugin_environ_new(), visual_plugin_info_new(), visual_plugin_new(), and visual_plugin_ref_new().
VisObject* visual_object_new (void)
Creates a new VisObject structure.
Returns:
A newly allocated VisObject, or NULL on failure.
Definition at line 36 of file lv_object.c.
int visual_object_ref (VisObject * object)
Increases the reference counter for a VisObject.
Parameters:
object Pointer to a VisObject in which the reference count is increased.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 121 of file lv_object.c.
Referenced by visual_actor_new(), visual_audio_new(), visual_audio_sample_new(), visual_audio_samplepool_channel_new(), visual_audio_samplepool_new(), visual_buffer_new(), visual_collection_iter_init(), visual_collection_iter_new(), visual_event_new(), visual_event_queue_new(), visual_input_new(), visual_list_new(), visual_morph_new(), visual_object_initialize(), visual_object_new(), visual_param_entry_set_collection(), visual_param_entry_set_object(), visual_plugin_load(), visual_ringbuffer_entry_new(), visual_ringbuffer_entry_new_function(), visual_ringbuffer_new(), visual_transform_new(), visual_video_new(), and visual_video_region_sub().
int visual_object_set_allocated (VisObject * object, int allocated)
Sets whether a VisObject is allocated or not.
This is used when a VisObject is unreffed. If it's allocated it will get freed, if not, only the dtor gets called to cleanup the inside of the VisObject.
Parameters:
object pointer to a VisObject to which the destructor function is set.
allocated Boolean whether a VisObject is allocated or not.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 103 of file lv_object.c.
Referenced by visual_actor_init(), visual_actor_new(), visual_audio_init(), visual_audio_new(), visual_audio_sample_init(), visual_audio_sample_new(), visual_audio_samplepool_channel_init(), visual_audio_samplepool_channel_new(), visual_audio_samplepool_init(), visual_audio_samplepool_new(), visual_buffer_init(), visual_buffer_new(), visual_collection_iter_init(), visual_collection_iter_new(), visual_event_init(), visual_event_new(), visual_event_queue_init(), visual_event_queue_new(), visual_input_init(), visual_input_new(), visual_list_init(), visual_list_new(), visual_morph_init(), visual_morph_new(), visual_object_initialize(), visual_ringbuffer_entry_init(), visual_ringbuffer_entry_init_function(), visual_ringbuffer_entry_new(), visual_ringbuffer_entry_new_function(), visual_ringbuffer_init(), visual_ringbuffer_new(), visual_transform_init(), visual_transform_new(), visual_video_init(), and visual_video_new().
int visual_object_set_dtor (VisObject * object, VisObjectDtorFunc dtor)
Sets the destructor function to a VisObject.
Parameters:
object pointer to a VisObject to which the destructor function is set.
dtor The Destructor function, that is used to destroy the VisObject when it loses all references or when it's being destroyed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 94 of file lv_object.c.
Referenced by visual_actor_init(), visual_audio_init(), visual_audio_sample_init(), visual_audio_samplepool_channel_init(), visual_audio_samplepool_init(), visual_buffer_init(), visual_collection_iter_init(), visual_event_init(), visual_event_queue_init(), visual_input_init(), visual_list_init(), visual_morph_init(), visual_object_initialize(), visual_ringbuffer_entry_init(), visual_ringbuffer_entry_init_function(), visual_ringbuffer_init(), visual_transform_init(), and visual_video_init().
int visual_object_set_private (VisObject * object, void * priv)
Sets the private data pointer to a VisObject.
Parameters:
object Pointer to a VisObject to which the private data is set.
priv Pointer to the private data that is set to the VisObject.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 145 of file lv_object.c.
Referenced by visual_input_set_callback(), visual_object_clear(), and visual_param_entry_add_callback().
int visual_object_set_refcount (VisObject * object, int refcount)
Sets the refcount to a certain number.
Mostly used in VisObject initialization.
Parameters:
object Pointer to a VisObject to which the refcount is set.
refcount The value for the VisObject it's refcount.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL on failure.
Definition at line 112 of file lv_object.c.
Referenced by visual_object_clear().
int visual_object_unref (VisObject * object)
Decreases the reference counter for a VisObject.
If the reference counter hits zero it will destruct the object using visual_object_destroy.
See also:
visual_object_destroy
Parameters:
object Pointer to a VisObject in which the reference count is decreased.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_OBJECT_NULL or error values returned by visual_object_destroy on failure.
Definition at line 130 of file lv_object.c.
Referenced by visual_actor_video_negotiate(), visual_audio_analyze(), visual_audio_get_cheap_audio_data(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_get_sample_mixed_simple(), visual_audio_get_spectrum(), visual_audio_sample_transform_format(), visual_audio_sample_transform_rate(), visual_bin_set_morph_by_name(), visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), visual_bin_switch_finalize(), visual_bitmap_load_new_video(), visual_collection_iter_dtor(), visual_config_registry_open(), visual_config_registry_remove(), visual_event_queue_add(), visual_event_queue_poll(), visual_object_collection_destroyer(), visual_param_entry_remove_callback(), visual_param_entry_set_collection(), visual_param_entry_set_object(), visual_plugin_environ_remove(), visual_plugin_get_reference(), visual_plugin_unload(), visual_ringbuffer_get_data_offset(), visual_ringbuffer_get_size(), visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_alpha_rectangle(), visual_video_fill_color_rectangle(), visual_video_new_with_buffer(), and visual_video_scale_depth().