libvisual: VisTransform
VisTransform
Data Structures
struct _VisTransform
The VisTransform structure encapsulates the transform plugin and provides abstract interfaces to the transform.
struct _VisTransformPlugin
The VisTransformPlugin structure is the main data structure for the transform plugin.
Defines
#define VISUAL_TRANSFORM(obj) (VISUAL_CHECK_CAST ((obj), VisTransform))
#define VISUAL_TRANSFORM_PLUGIN(obj) (VISUAL_CHECK_CAST ((obj), VisTransformPlugin))
Typedefs
typedef struct _VisTransform VisTransform
typedef struct _VisTransformPlugin VisTransformPlugin
typedef int(* VisPluginTransformPaletteFunc)(VisPluginData *plugin, VisPalette *pal, VisAudio *audio)
A transform plugin needs this signature to transform VisPalettes.
typedef int(* VisPluginTransformVideoFunc)(VisPluginData *plugin, VisVideo *video, VisAudio *audio)
A transform plugin needs this signature to transform VisVideos.
Functions
VisPluginData * visual_transform_get_plugin (VisTransform *transform)
Gives the encapsulated VisPluginData from a VisTransform.
const char * visual_transform_get_next_by_name (const char *name)
Gives the next transform plugin based on the name of a plugin.
const char * visual_transform_get_prev_by_name (const char *name)
Gives the previous transform plugin based on the name of a plugin.
VisTransform * visual_transform_new (const char *transformname)
Creates a new transform from name, the plugin will be loaded but won't be realized.
int visual_transform_init (VisTransform *transform, const char *transformname)
Initializes a VisTransform, this will set the allocated flag for the object to FALSE.
int visual_transform_realize (VisTransform *transform)
Realize the VisTransform.
int visual_transform_video_negotiate (VisTransform *transform)
This function negotiates the VisTransform with it's target video that is set by visual_transform_set_video.
int visual_transform_get_supported_depth (VisTransform *transform)
Gives the by the plugin natively supported depths.
VisVideoAttributeOptions * visual_transform_get_video_attribute_options (VisTransform *transform)
int visual_transform_set_video (VisTransform *transform, VisVideo *video)
Used to connect the target display it's VisVideo structure to the VisTransform.
int visual_transform_set_palette (VisTransform *transform, VisPalette *palette)
Used to override the palette that is extracted from the VisVideo that is given using visual_transform_set_video.
int visual_transform_run (VisTransform *transform, VisAudio *audio)
This is called to run a VisTransform.
int visual_transform_run_video (VisTransform *transform, VisAudio *audio)
This is called to run the video part of a VisTransform.
int visual_transform_run_palette (VisTransform *transform, VisAudio *audio)
This is called to run the palette part of a VisTransform.
Define Documentation
#define VISUAL_TRANSFORM (obj) (VISUAL_CHECK_CAST ((obj), VisTransform))
Definition at line 38 of file lv_transform.h.
#define VISUAL_TRANSFORM_PLUGIN (obj) (VISUAL_CHECK_CAST ((obj), VisTransformPlugin))
Definition at line 39 of file lv_transform.h.
Typedef Documentation
typedef int(* VisPluginTransformPaletteFunc)(VisPluginData *plugin, VisPalette *pal, VisAudio *audio)
A transform plugin needs this signature to transform VisPalettes.
plugin Pointer to the VisPluginData instance structure.
pal Pointer to the VisPalette that is to be morphed. Only 256 entry VisPalettes have to be supported.
audio Optionally a pointer to the VisAudio, when requested.
Returns:
0 on succes -1 on error.
Definition at line 56 of file lv_transform.h.
typedef int(* VisPluginTransformVideoFunc)(VisPluginData *plugin, VisVideo *video, VisAudio *audio)
A transform plugin needs this signature to transform VisVideos.
plugin Pointer to the VisPluginData instance structure.
video Pointer to the VisVideo that needs to be transformed.
audio Optionally a pointer to the VisAudio, when requested.
Returns:
0 on succes -1 on error.
Definition at line 67 of file lv_transform.h.
typedef struct _VisTransform VisTransform
Definition at line 41 of file lv_transform.h.
typedef struct _VisTransformPlugin VisTransformPlugin
Definition at line 42 of file lv_transform.h.
Function Documentation
const char* visual_transform_get_next_by_name (const char * name)
Gives the next transform plugin based on the name of a plugin.
See also:
visual_transform_get_prev_by_name
Parameters:
name The name of the current plugin, or NULL to get the first.
Returns:
The name of the next plugin within the list.
Definition at line 78 of file lv_transform.cpp.
VisPluginData* visual_transform_get_plugin (VisTransform * transform)
Gives the encapsulated VisPluginData from a VisTransform.
Parameters:
transform Pointer of a VisTransform of which the VisPluginData needs to be returned.
Returns:
VisPluginData that is encapsulated in the VisTransform, possibly NULL.
Definition at line 73 of file lv_transform.cpp.
Referenced by visual_transform_run_palette(), and visual_transform_run_video().
const char* visual_transform_get_prev_by_name (const char * name)
Gives the previous transform plugin based on the name of a plugin.
See also:
visual_transform_get_next_by_name
Parameters:
name The name of the current plugin. or NULL to get the last.
Returns:
The name of the previous plugin within the list.
Definition at line 83 of file lv_transform.cpp.
int visual_transform_get_supported_depth (VisTransform * transform)
Gives the by the plugin natively supported depths.
Parameters:
transform Pointer to a VisTransform of which the supported depth of it's encapsulated plugin is requested.
Returns:
an OR value of the VISUAL_VIDEO_DEPTH_* values which can be checked against using AND on success, -VISUAL_ERROR_TRANSFORM_NULL, -VISUAL_ERROR_PLUGIN_NULL or -VISUAL_ERROR_TRANSFORM_PLUGIN_NULL on failure.
Definition at line 171 of file lv_transform.cpp.
Referenced by visual_transform_video_negotiate().
VisVideoAttributeOptions* visual_transform_get_video_attribute_options (VisTransform * transform)
Definition at line 186 of file lv_transform.cpp.
int visual_transform_init (VisTransform * transform, const char * transformname)
Initializes a VisTransform, this will set the allocated flag for the object to FALSE.
Should not be used to reset a VisTransform, or on a VisTransform created by visual_transform_new().
See also:
visual_transform_new
Parameters:
transform Pointer to the VisTransform that is initialized.
transformname The name of the plugin to load, or NULL to simply initialize a new transform.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL or -VISUAL_ERROR_PLUGIN_NO_LIST on failure.
Definition at line 108 of file lv_transform.cpp.
Referenced by visual_transform_new().
VisTransform* visual_transform_new (const char * transformname)
Creates a new transform from name, the plugin will be loaded but won't be realized.
Parameters:
transformname The name of the plugin to load, or NULL to simply allocate a new transform.
Returns:
A newly allocated VisTransform, optionally containing a loaded plugin. Or NULL on failure.
Definition at line 88 of file lv_transform.cpp.
int visual_transform_realize (VisTransform * transform)
Realize the VisTransform.
This also calls the plugin init function.
Parameters:
transform Pointer to a VisTransform that needs to be realized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL, -VISUAL_ERROR_PLUGIN_NULL or error values returned by visual_plugin_realize () on failure.
Definition at line 142 of file lv_transform.cpp.
int visual_transform_run (VisTransform * transform, VisAudio * audio)
This is called to run a VisTransform.
See also:
visual_transform_run_video
visual_transform_run_palette
Parameters:
transform Pointer to a VisTransform that needs to be runned.
audio Pointer to a VisAudio that contains all the audio data.
return VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL or error values returned by either visual_transform_run_video or visual_transform_run_palette on failure.
Definition at line 227 of file lv_transform.cpp.
int visual_transform_run_palette (VisTransform * transform, VisAudio * audio)
This is called to run the palette part of a VisTransform.
See also:
visual_transform_run
Parameters:
transform Pointer to a VisTransform that needs to be runned.
audio Pointer to a VisAudio that contains all the audio data.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL, -VISUAL_ERROR_TRANSFORM_PALETTE_NULL or -VISUAL_ERROR_TRANSFORM_PLUGIN_NULL on failure.
Definition at line 270 of file lv_transform.cpp.
Referenced by visual_transform_run().
int visual_transform_run_video (VisTransform * transform, VisAudio * audio)
This is called to run the video part of a VisTransform.
See also:
visual_transform_run
Parameters:
transform Pointer to a VisTransform that needs to be runned.
audio Pointer to a VisAudio that contains all the audio data.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL, -VISUAL_ERROR_TRANSFORM_VIDEO_NULL or -VISUAL_ERROR_TRANSFORM_PLUGIN_NULL on failure.
Definition at line 245 of file lv_transform.cpp.
Referenced by visual_transform_run().
int visual_transform_set_palette (VisTransform * transform, VisPalette * palette)
Used to override the palette that is extracted from the VisVideo that is given using visual_transform_set_video.
Always call this function after visual_transform_set_video is called.
See also:
visual_transform_set_video
Parameters:
transform Pointer to a VisTransform to which the VisVideo needs to be set.
palette Pointer to the VisPalette which is used to override the palette in the VisTransform.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL on failure.
Definition at line 215 of file lv_transform.cpp.
Referenced by visual_transform_set_video().
int visual_transform_set_video (VisTransform * transform, VisVideo * video)
Used to connect the target display it's VisVideo structure to the VisTransform.
Using the visual_video methods the screenbuffer, it's depth and dimension and optionally it's pitch can be set so the transform plugins know about their graphical environment and have a place to draw.
After this function it's most likely that visual_transform_video_negotiate needs to be called.
See also:
visual_video_new
visual_transform_video_negotiate
Parameters:
transform Pointer to a VisTransform to which the VisVideo needs to be set.
video Pointer to a VisVideo which contains information about the target display and the pointer to it's screenbuffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL on failure.
Definition at line 201 of file lv_transform.cpp.
int visual_transform_video_negotiate (VisTransform * transform)
This function negotiates the VisTransform with it's target video that is set by visual_transform_set_video.
When needed it also sets up size fitting environment and depth transformation environment.
Parameters:
transform Pointer to a VisTransform that needs negotiation.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_TRANSFORM_NULL, -VISUAL_ERROR_PLUGIN_NULL, -VISUAL_ERROR_PLUGIN_REF_NULL or -VISUAL_ERROR_TRANSFORM_NEGOTIATE on failure.
Definition at line 150 of file lv_transform.cpp.