libvisual: VisRectangle
VisRectangle
Defines
#define VISUAL_RECTANGLE(obj) (VISUAL_CHECK_CAST ((obj, VisRectangle))
Typedefs
typedef struct _VisRectangle VisRectangle
Functions
VISUAL_BEGIN_DECLS VisRectangle * visual_rectangle_new (int x, int y, int width, int height)
VisRectangle * visual_rectangle_new_empty (void)
void visual_rectangle_free (VisRectangle *rect)
void visual_rectangle_set (VisRectangle *rect, int x, int y, int width, int height)
void visual_rectangle_copy (VisRectangle *dest, VisRectangle *src)
VisRectangle * visual_rectangle_clone (VisRectangle *rect)
void visual_rectangle_set_x (VisRectangle *rect, int x)
int visual_rectangle_get_x (VisRectangle *rect)
void visual_rectangle_set_y (VisRectangle *rect, int y)
int visual_rectangle_get_y (VisRectangle *rect)
void visual_rectangle_set_width (VisRectangle *rect, int width)
int visual_rectangle_get_width (VisRectangle *rect)
void visual_rectangle_set_height (VisRectangle *rect, int height)
int visual_rectangle_get_height (VisRectangle *rect)
int visual_rectangle_is_empty (VisRectangle *rect)
int visual_rectangle_intersects (VisRectangle *dest, VisRectangle *src)
int visual_rectangle_contains_point (VisRectangle *rect, int x, int y)
int visual_rectangle_contains_rect (VisRectangle *dest, VisRectangle *src)
void visual_rectangle_clip (VisRectangle *dest, VisRectangle *within, VisRectangle *src)
void visual_rectangle_normalize (VisRectangle *rect)
void visual_rectangle_normalize_to (VisRectangle *dest, VisRectangle *src)
void visual_rectangle_denormalize_point (VisRectangle *rect, float fx, float fy, int32_t *x, int32_t *y)
void visual_rectangle_denormalize_points (VisRectangle *rect, const float *fxlist, const float *fylist, int32_t *xlist, int32_t *ylist, unsigned int size)
void visual_rectangle_denormalize_point_neg (VisRectangle *rect, float fx, float fy, int32_t *x, int32_t *y)
void visual_rectangle_denormalize_points_neg (VisRectangle *rect, const float *fxlist, const float *fylist, int32_t *xlist, int32_t *ylist, unsigned int size)
Define Documentation
#define VISUAL_RECTANGLE (obj) (VISUAL_CHECK_CAST ((obj, VisRectangle))
Definition at line 233 of file lv_rectangle.h.
Typedef Documentation
typedef struct _VisRectangle VisRectangle
Definition at line 238 of file lv_rectangle.h.
Function Documentation
void visual_rectangle_clip (VisRectangle * dest, VisRectangle * within, VisRectangle * src)
Definition at line 128 of file lv_rectangle_c.cpp.
Referenced by visual_video_region_sub_with_boundary().
VisRectangle* visual_rectangle_clone (VisRectangle * rect)
Definition at line 35 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_rectangle_custom(), visual_video_blit_overlay_rectangle_scale_custom(), and visual_video_region_sub_with_boundary().
int visual_rectangle_contains_point (VisRectangle * rect, int x, int y)
Definition at line 113 of file lv_rectangle_c.cpp.
int visual_rectangle_contains_rect (VisRectangle * dest, VisRectangle * src)
Definition at line 120 of file lv_rectangle_c.cpp.
Referenced by visual_video_region_sub().
void visual_rectangle_copy (VisRectangle * dest, VisRectangle * src)
Definition at line 27 of file lv_rectangle_c.cpp.
Referenced by visual_video_region_sub().
void visual_rectangle_denormalize_point (VisRectangle * rect, float fx, float fy, int32_t * x, int32_t * y)
Definition at line 152 of file lv_rectangle_c.cpp.
void visual_rectangle_denormalize_point_neg (VisRectangle * rect, float fx, float fy, int32_t * x, int32_t * y)
Definition at line 161 of file lv_rectangle_c.cpp.
void visual_rectangle_denormalize_points (VisRectangle * rect, const float * fxlist, const float * fylist, int32_t * xlist, int32_t * ylist, unsigned int size)
Definition at line 170 of file lv_rectangle_c.cpp.
void visual_rectangle_denormalize_points_neg (VisRectangle * rect, const float * fxlist, const float * fylist, int32_t * xlist, int32_t * ylist, unsigned int size)
void visual_rectangle_free (VisRectangle * rect)
Definition at line 17 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_color_rectangle(), visual_video_region_sub(), visual_video_region_sub_all(), visual_video_region_sub_by_values(), and visual_video_region_sub_with_boundary().
int visual_rectangle_get_height (VisRectangle * rect)
Definition at line 91 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), and visual_video_region_sub().
int visual_rectangle_get_width (VisRectangle * rect)
Definition at line 77 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), and visual_video_region_sub().
int visual_rectangle_get_x (VisRectangle * rect)
Definition at line 49 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), and visual_video_region_sub().
int visual_rectangle_get_y (VisRectangle * rect)
Definition at line 63 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), and visual_video_region_sub().
int visual_rectangle_intersects (VisRectangle * dest, VisRectangle * src)
Definition at line 105 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), and visual_video_fill_color_rectangle().
int visual_rectangle_is_empty (VisRectangle * rect)
Definition at line 98 of file lv_rectangle_c.cpp.
Referenced by visual_video_region_sub().
VISUAL_BEGIN_DECLS VisRectangle* visual_rectangle_new (int x, int y, int width, int height)
Definition at line 7 of file lv_rectangle_c.cpp.
Referenced by visual_rectangle_clone(), visual_video_blit_overlay_custom(), visual_video_get_boundary(), and visual_video_region_sub_by_values().
VisRectangle* visual_rectangle_new_empty (void)
Definition at line 12 of file lv_rectangle_c.cpp.
Referenced by visual_video_init().
void visual_rectangle_normalize (VisRectangle * rect)
Definition at line 137 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_rectangle_scale_custom().
void visual_rectangle_normalize_to (VisRectangle * dest, VisRectangle * src)
Definition at line 144 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_rectangle_custom().
void visual_rectangle_set (VisRectangle * rect, int x, int y, int width, int height)
Definition at line 22 of file lv_rectangle_c.cpp.
void visual_rectangle_set_height (VisRectangle * rect, int height)
Definition at line 84 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom().
void visual_rectangle_set_width (VisRectangle * rect, int width)
Definition at line 70 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom().
void visual_rectangle_set_x (VisRectangle * rect, int x)
Definition at line 42 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom().
void visual_rectangle_set_y (VisRectangle * rect, int y)
Definition at line 56 of file lv_rectangle_c.cpp.
Referenced by visual_video_blit_overlay_custom().