libvisual: VisList
VisList
Data Structures
struct _VisListEntry
The VisListEntry data structure is an entry within the linked list.
struct _VisList
The VisList data structure represents a linked list.
Defines
#define VISUAL_LIST(obj) (VISUAL_CHECK_CAST ((obj), VisList))
Typedefs
typedef struct _VisListEntry VisListEntry
typedef struct _VisList VisList
Functions
VisList * visual_list_new (VisCollectionDestroyerFunc destroyer)
Creates a new VisList structure.
int visual_list_init (VisList *list, VisCollectionDestroyerFunc destroyer)
Initializes a new VisList.
void * visual_list_next (VisList *list, VisListEntry **le)
Goes to the next entry in the list and return it's data element.
void * visual_list_prev (VisList *list, VisListEntry **le)
Go to the previous entry in the list and return it's data element.
void * visual_list_get (VisList *list, int index)
Get an data entry by index.
int visual_list_add_at_begin (VisList *list, void *data)
Get an data entry by index.
int visual_list_add (VisList *list, void *data)
Adds an entry at the end of the list.
int visual_list_chain_at_begin (VisList *list, VisListEntry *le)
Chains an VisListEntry at the beginning of the list.
int visual_list_chain (VisList *list, VisListEntry *le)
Chains an VisListEntry at the end of the list.
int visual_list_unchain (VisList *list, VisListEntry *le)
Unchain a VisListEntry from a VisList, entry won't be deleted.
int visual_list_insert (VisList *list, VisListEntry **le, void *data)
Insert an entry in the middle of a list.
int visual_list_delete (VisList *list, VisListEntry **le)
Removes an entry from the list.
int visual_list_destroy (VisList *list, VisListEntry **le)
Removes and entry from the list and uses the VisListDestroyerFunc when present to clean up the data.
int visual_list_count (VisList *list)
Gets the amount of elements in a VisList.
Define Documentation
#define VISUAL_LIST (obj) (VISUAL_CHECK_CAST ((obj), VisList))
Definition at line 50 of file lv_list.h.
Typedef Documentation
typedef struct _VisList VisList
Definition at line 53 of file lv_list.h.
typedef struct _VisListEntry VisListEntry
Definition at line 52 of file lv_list.h.
Function Documentation
int visual_list_add (VisList * list, void * data)
Adds an entry at the end of the list.
Parameters:
list Pointer to the VisList to which an entry needs to be added at it's tail.
data A pointer to the data that needs to be added to the list.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL on failure.
Definition at line 278 of file lv_list.c.
Referenced by visual_audio_samplepool_add_channel(), visual_config_registry_add(), visual_event_queue_add(), visual_param_container_add(), visual_param_container_add_with_defaults(), visual_param_entry_add_callback(), visual_plugin_environ_add(), and visual_ringbuffer_add_entry().
int visual_list_add_at_begin (VisList * list, void * data)
Get an data entry by index.
This will give the pointer to an data element based on the index in the list.
Parameters:
list Pointer to the VisList of which we want an element.
index Index to determine which entry we want. The index starts at 1.
Returns:
The data element of the requested entry, or NULL.
Definition at line 261 of file lv_list.c.
int visual_list_chain (VisList * list, VisListEntry * le)
Chains an VisListEntry at the end of the list.
Parameters:
list Pointer to the VisList to which an entry needs to be added at it's tail.
le A pointer to the VisListEntry that needs to be chained to the list.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL or -VISUAL_ERROR_LIST_ENTRY_NULL on failure.
Definition at line 322 of file lv_list.c.
Referenced by visual_list_add().
int visual_list_chain_at_begin (VisList * list, VisListEntry * le)
Chains an VisListEntry at the beginning of the list.
Parameters:
list Pointer to the VisList to which an entry needs to be added at it's tail.
le A pointer to the VisListEntry that needs to be chained to the list.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL or -VISUAL_ERROR_LIST_ENTRY_NULL on failure.
Definition at line 294 of file lv_list.c.
Referenced by visual_list_add_at_begin().
int visual_list_count (VisList * list)
Gets the amount of elements in a VisList.
list - the list of which the element-count is requested
Returns:
amount of elements currently in list (or -VISUAL_ERROR_COLLECTION_NULL on error)
Definition at line 176 of file lv_list.c.
Referenced by visual_ringbuffer_get_data_offset().
int visual_list_delete (VisList * list, VisListEntry ** le)
Removes an entry from the list.
Parameters:
list A pointer to the VisList in which an entry needs to be deleted.
le A pointer to the entry that needs to be deleted.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL or -VISUAL_ERROR_LIST_ENTRY_NULL on failure.
Definition at line 435 of file lv_list.c.
Referenced by visual_config_registry_remove(), visual_event_queue_poll_by_reference(), visual_list_destroy(), visual_param_container_remove(), visual_param_entry_remove_callback(), and visual_plugin_environ_remove().
int visual_list_destroy (VisList * list, VisListEntry ** le)
Removes and entry from the list and uses the VisListDestroyerFunc when present to clean up the data.
Parameters:
list A pointer to the VisList in which an entry needs to be destroyed.
le A pointer to the entry that needs to be destroyed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL or -VISUAL_ERROR_LIST_ENTRY_NULL on failure.
Definition at line 459 of file lv_list.c.
Referenced by visual_audio_samplepool_channel_flush_old().
void* visual_list_get (VisList * list, int index)
Get an data entry by index.
This will give the pointer to an data element based on the index in the list.
Parameters:
list Pointer to the VisList of which we want an element.
index Index to determine which entry we want. The index starts at 1.
Returns:
The data element of the requested entry, or NULL.
Definition at line 237 of file lv_list.c.
int visual_list_init (VisList * list, VisCollectionDestroyerFunc destroyer)
Initializes a new VisList.
list - newly generated list (output of visual_list_new()) destroyer - the function that cleans up the list upon visual_list_destroy()
Definition at line 182 of file lv_list.c.
Referenced by visual_list_new(), and visual_param_container_new().
int visual_list_insert (VisList * list, VisListEntry ** le, void * data)
Insert an entry in the middle of a list.
By adding it after the le entry.
Parameters:
list Pointer to the VisList in which an entry needs to be inserted.
le Pointer to a VisListEntry after which the entry needs to be inserted.
data Pointer to the data the new entry represents.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL, -VISUAL_ERROR_LIST_ENTRY_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 385 of file lv_list.c.
VisList* visual_list_new (VisCollectionDestroyerFunc destroyer)
Creates a new VisList structure.
The VisList system is a double linked list implementation.
Returns:
A newly allocated VisList.
Definition at line 161 of file lv_list.c.
Referenced by visual_audio_samplepool_init(), and visual_ringbuffer_init().
void* visual_list_next (VisList * list, VisListEntry ** le)
Goes to the next entry in the list and return it's data element.
This function will load the next entry in le and return a pointer to the data element.
See also:
visual_list_prev
Parameters:
list Pointer to the VisList we're traversing.
le Pointer to a VisListEntry to store the next entry within and also to use as a reference to determine at which entry we're currently. To begin traversing do: VisListEntry *le = NULL and pass it as &le in the argument.
Returns:
The data element of the next entry, or NULL.
Definition at line 205 of file lv_list.c.
Referenced by visual_audio_get_sample_mixed_all(), visual_audio_get_sample_mixed_category(), visual_audio_samplepool_channel_flush_old(), visual_audio_samplepool_flush_old(), visual_audio_samplepool_get_channel(), visual_config_registry_find(), visual_config_registry_remove(), visual_event_queue_poll_by_reference(), visual_list_get(), visual_param_container_copy(), visual_param_container_copy_match(), visual_param_container_get(), visual_param_container_remove(), visual_param_entry_notify_callbacks(), visual_param_entry_remove_callback(), visual_plugin_environ_get(), visual_plugin_environ_remove(), visual_ringbuffer_get_data_offset(), and visual_ringbuffer_get_size().
void* visual_list_prev (VisList * list, VisListEntry ** le)
Go to the previous entry in the list and return it's data element.
This function will load the previous entry in le and return a pointer to the data element.
See also:
visual_list_next
Parameters:
list Pointer to the VisList we're traversing.
le Pointer to a VisListEntry to store the previous entry within and also to use as a reference to determine at which entry we're currently. To begin traversing at the end of the list do: VisList *le = NULL and pass it as &le in the argument.
Returns:
The data element of the previous entry, or NULL.
Definition at line 221 of file lv_list.c.
int visual_list_unchain (VisList * list, VisListEntry * le)
Unchain a VisListEntry from a VisList, entry won't be deleted.
This function will only remove the links with it's VisList.
Parameters:
list Pointer to the VisList from which an entry is unchained.
le Pointer to a VisListEntry that is being unchained.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_LIST_NULL or -VISUAL_ERROR_LIST_ENTRY_NULL on failure.
Definition at line 357 of file lv_list.c.
Referenced by visual_list_delete().