libvisual: VisColor
VisColor
Data Structures
struct _VisColor
Defines
#define VISUAL_COLOR(obj) (VISUAL_CHECK_CAST ((obj), VisColor))
Typedefs
typedef
typedefVISUAL_BEGIN_DECLS
struct _VisColor VisColor
Functions
VisColor * visual_color_new (void)
void visual_color_free (VisColor *color)
int visual_color_set (VisColor *color, uint8_t r, uint8_t g, uint8_t b)
int visual_color_set_with_alpha (VisColor *color, uint8_t r, uint8_t g, uint8_t b, uint8_t a)
int visual_color_compare (VisColor *src1, VisColor *src2)
int visual_color_from_hsv (VisColor *color, float h, float s, float v)
int visual_color_to_hsv (VisColor *color, float *h, float *s, float *v)
int visual_color_copy (VisColor *dest, VisColor *src)
int visual_color_from_uint32 (VisColor *color, uint32_t rgb)
int visual_color_from_uint16 (VisColor *color, uint16_t rgb)
uint32_t visual_color_to_uint32 (VisColor *color)
uint16_t visual_color_to_uint16 (VisColor *color)
VisColor * visual_color_black (void)
VisColor * visual_color_white (void)
Define Documentation
#define VISUAL_COLOR (obj) (VISUAL_CHECK_CAST ((obj), VisColor))
Definition at line 150 of file lv_color.h.
Typedef Documentation
typedef typedefVISUAL_BEGIN_DECLS struct _VisColor VisColor
Definition at line 143 of file lv_color.h.
Function Documentation
VisColor* visual_color_black (void)
Definition at line 103 of file lv_color_c.cpp.
int visual_color_compare (VisColor * src1, VisColor * src2)
Definition at line 35 of file lv_color_c.cpp.
Referenced by visual_param_entry_compare(), and visual_param_entry_set_color_by_color().
int visual_color_copy (VisColor * dest, VisColor * src)
Definition at line 61 of file lv_color_c.cpp.
Referenced by visual_param_entry_default_set_color(), visual_param_entry_set_color_by_color(), visual_video_composite_set_colorkey(), visual_video_fill_color(), and visual_video_region_sub().
void visual_color_free (VisColor * color)
Definition at line 12 of file lv_color_c.cpp.
int visual_color_from_hsv (VisColor * color, float h, float s, float v)
Definition at line 43 of file lv_color_c.cpp.
int visual_color_from_uint16 (VisColor * color, uint16_t rgb)
Definition at line 80 of file lv_color_c.cpp.
int visual_color_from_uint32 (VisColor * color, uint32_t rgb)
Definition at line 71 of file lv_color_c.cpp.
VisColor* visual_color_new (void)
Definition at line 7 of file lv_color_c.cpp.
Referenced by visual_video_init().
int visual_color_set (VisColor * color, uint8_t r, uint8_t g, uint8_t b)
Definition at line 17 of file lv_color_c.cpp.
Referenced by visual_param_entry_set_color(), visual_video_composite_set_colorkey(), and visual_video_fill_color().
int visual_color_set_with_alpha (VisColor * color, uint8_t r, uint8_t g, uint8_t b, uint8_t a)
Definition at line 26 of file lv_color_c.cpp.
int visual_color_to_hsv (VisColor * color, float * h, float * s, float * v)
Definition at line 52 of file lv_color_c.cpp.
uint16_t visual_color_to_uint16 (VisColor * color)
Definition at line 96 of file lv_color_c.cpp.
Referenced by blit_overlay_colorkey(), and blit_overlay_surfacealphacolorkey().
uint32_t visual_color_to_uint32 (VisColor * color)
Definition at line 89 of file lv_color_c.cpp.
Referenced by blit_overlay_colorkey(), and blit_overlay_surfacealphacolorkey().
VisColor* visual_color_white (void)
Definition at line 108 of file lv_color_c.cpp.