libvisual: VisMem
VisMem
Defines
#define visual_mem_new0(struct_type, n_structs) ((struct_type *) visual_mem_malloc0 (((visual_size_t) sizeof (struct_type)) * ((visual_size_t) (n_structs))))
Convenient macro to request n_structs structures of type struct_type initialized to 0.
Typedefs
typedef void *(* VisMemCopyPitchFunc)(void *dest, const void *src, int pitch1, int pitch2, int width, int rows)
The visual_mem_copy_pitch function needs this signature.
typedef void *(* VisMemSet8Func)(void *dest, int c, visual_size_t n)
The visual_mem_set function needs this signature.
typedef void *(* VisMemSet16Func)(void *dest, int c, visual_size_t n)
The visual_mem_set16 function needs this signature.
typedef void *(* VisMemSet32Func)(void *dest, int c, visual_size_t n)
The visual_mem_set32 function needs this signature.
Functions
int visual_mem_initialize (void)
Initialize the memory functions.
void * visual_mem_malloc (visual_size_t nbytes) VIS_ATTR_MALLOC
Allocates nbytes of uninitialized memory.
void * visual_mem_malloc0 (visual_size_t nbytes) VIS_ATTR_MALLOC
Allocates nbytes of memory initialized to 0.
void * visual_mem_realloc (void *ptr, visual_size_t nbytes) VIS_ATTR_MALLOC
Reallocates memory, can be used to grow a buffer.
int visual_mem_free (void *ptr)
Frees allocated memory.
Variables
VISUAL_BEGIN_DECLS typedef void *(* VisMemCopyFunc)(void *dest, const void *src, visual_size_t n)
The visual_mem_copy function needs this signature.
VisMemCopyFunc visual_mem_copy
VisMemCopyPitchFunc visual_mem_copy_pitch
VisMemSet8Func visual_mem_set
VisMemSet16Func visual_mem_set16
VisMemSet32Func visual_mem_set32
Define Documentation
#define visual_mem_new0 (struct_type, n_structs) ((struct_type *) visual_mem_malloc0 (((visual_size_t) sizeof (struct_type)) * ((visual_size_t) (n_structs))))
Convenient macro to request n_structs structures of type struct_type initialized to 0.
Definition at line 163 of file lv_mem.h.
Referenced by visual_actor_init(), visual_actor_new(), visual_audio_new(), visual_audio_sample_new(), visual_audio_samplepool_channel_new(), visual_audio_samplepool_new(), visual_beat_adv_new(), visual_beat_new(), visual_bin_new(), visual_buffer_new(), visual_collection_iter_new(), visual_config_registry_new(), visual_config_registry_section_new(), visual_event_new(), visual_event_queue_new(), visual_input_new(), visual_list_add(), visual_list_add_at_begin(), visual_list_insert(), visual_list_new(), visual_morph_new(), visual_mutex_new(), visual_object_new(), visual_param_container_new(), visual_param_entry_add_callback(), visual_param_entry_new(), visual_plugin_environ_new(), visual_plugin_info_new(), visual_plugin_new(), visual_plugin_ref_new(), visual_ringbuffer_entry_new(), visual_ringbuffer_entry_new_function(), visual_ringbuffer_new(), visual_thread_create(), visual_transform_new(), visual_video_allocate_buffer(), visual_video_new(), and visual_video_set_buffer().
Typedef Documentation
typedef void*(* VisMemCopyPitchFunc)(void *dest, const void *src, int pitch1, int pitch2, int width, int rows)
The visual_mem_copy_pitch function needs this signature.
This function supports a negative pitch.
dest Pointer to the dest buffer.
src Pointer to the source buffer.
pitch1 The number of bytes a row in the dest buffer.
pitch2 The number of bytes a row in the src buffer.
width The copy width of each row.
rows The number of rows.
Returns:
Pointer to the dest buffer.
Definition at line 60 of file lv_mem.h.
typedef void*(* VisMemSet16Func)(void *dest, int c, visual_size_t n)
The visual_mem_set16 function needs this signature.
dest Pointer to the dest buffer.
c Value that is used as the set value.
n The number of words (16bits) to be set.
Returns:
Pointer to the dest buffer.
Definition at line 82 of file lv_mem.h.
typedef void*(* VisMemSet32Func)(void *dest, int c, visual_size_t n)
The visual_mem_set32 function needs this signature.
dest Pointer to the dest buffer.
c Value that is used as the set value.
n The number of integers (32bits) to be set.
Returns:
Pointer to the dest buffer.
Definition at line 93 of file lv_mem.h.
typedef void*(* VisMemSet8Func)(void *dest, int c, visual_size_t n)
The visual_mem_set function needs this signature.
dest Pointer to the dest buffer.
c Value that is used as the set value.
n The number of bytes to be set.
Returns:
Pointer to the dest buffer.
Definition at line 71 of file lv_mem.h.
Function Documentation
int visual_mem_free (void * ptr)
Frees allocated memory.
Parameters:
ptr Frees memory to which ptr points to.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_MEM_NULL on failure.
Definition at line 152 of file lv_mem.c.
Referenced by visual_actor_new(), visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_simple(), visual_audio_sample_buffer_mix_many(), visual_beat_get_info(), visual_buffer_destroyer_free(), visual_input_new(), visual_list_delete(), visual_morph_new(), visual_mutex_free(), visual_object_free(), visual_param_entry_default_set_string(), visual_param_entry_set_annotation(), visual_param_entry_set_name(), visual_param_entry_set_string(), visual_plugin_type_get_depth(), visual_plugin_type_get_type(), visual_plugin_type_has_flag(), visual_plugin_type_member_of(), visual_thread_create(), visual_thread_free(), visual_transform_new(), visual_video_free_buffer(), and visual_video_set_buffer().
int visual_mem_initialize (void)
Initialize the memory functions.
This is used to set the function pointers to the right optimized version. It's legal to call visual_mem_initialize more than once in the same context if it's needed to reset the optimal function pointers. This function bases it's choices upon the VisCPU system.
Be aware that visual_mem_initialize() should be called to set the most optimize mem_copy() and mem_set() functions is called. Be sure that visual_cpu_initialize() is called before this however if possible the best solution is to just call visual_init() which will call all the libvisual initialize functions.
return VISUAL_OK on succes.
Definition at line 73 of file lv_mem.c.
void* visual_mem_malloc (visual_size_t nbytes)
Allocates nbytes of uninitialized memory.
Parameters:
nbytes N bytes of mem requested to be allocated.
Returns:
On success, a pointer to a new allocated memory block of size nbytes, on failure, program is aborted.
Definition at line 117 of file lv_mem.c.
Referenced by visual_audio_get_sample_mixed(), visual_audio_get_sample_mixed_simple(), visual_audio_sample_buffer_mix_many(), visual_mem_malloc0(), and visual_strdup().
void* visual_mem_malloc0 (visual_size_t nbytes)
Allocates nbytes of memory initialized to 0.
Parameters:
nbytes N bytes of mem requested to be allocated.
Returns:
On success, a pointer to a new allocated memory initialized to 0 of size nbytes, on failure, program is aborted.
Definition at line 134 of file lv_mem.c.
Referenced by visual_beat_adv_init(), visual_beat_init(), visual_buffer_allocate_data(), visual_config_registry_open(), visual_plugin_type_get_flags(), visual_plugin_type_get_type(), and visual_plugin_type_member_of().
void* visual_mem_realloc (void * ptr, visual_size_t nbytes)
Reallocates memory, can be used to grow a buffer.
Parameters:
ptr Pointer that is to be reallocated.
nbytes The size of the new buffer.
Returns:
On success, a pointer to the new reallocated memory, on failure NULL.
Definition at line 147 of file lv_mem.c.
Referenced by visual_buffer_append(), and visual_buffer_append_data().
Variable Documentation
VISUAL_BEGIN_DECLS typedef void*(* VisMemCopyFunc)(void *dest, const void *src, visual_size_t n)
The visual_mem_copy function needs this signature.
dest Pointer to the dest buffer.
src Pointer to the source buffer.
n The number of bytes to be copied.
Returns:
Pointer to the dest buffer.
Definition at line 46 of file lv_mem.h.
VisMemCopyFunc visual_mem_copy
Definition at line 64 of file lv_mem.c.
Referenced by blit_overlay_noalpha(), visual_audio_analyze(), visual_bin_switch_actor(), visual_buffer_clone(), visual_buffer_copy_data_to(), visual_buffer_put_data(), visual_mem_initialize(), visual_param_container_add_with_defaults(), and visual_plugin_info_copy().
VisMemCopyPitchFunc visual_mem_copy_pitch
Definition at line 65 of file lv_mem.c.
Referenced by visual_mem_initialize().
VisMemSet8Func visual_mem_set
Definition at line 67 of file lv_mem.c.
Referenced by visual_bin_switch_actor(), visual_buffer_fill(), visual_cpu_initialize(), visual_mem_initialize(), visual_mem_malloc0(), and visual_video_fill_color_index8().
VisMemSet16Func visual_mem_set16
Definition at line 68 of file lv_mem.c.
Referenced by visual_mem_initialize(), and visual_video_fill_color_rgb16().
VisMemSet32Func visual_mem_set32
Definition at line 69 of file lv_mem.c.
Referenced by visual_mem_initialize(), and visual_video_fill_color_argb32().