libvisual: VisVideo
VisVideo
Data Structures
struct _VisVideo
Data structure that contains all the information about a screen surface.
struct _VisVideoAttributeOptions
Defines
#define VISUAL_VIDEO(obj) (VISUAL_CHECK_CAST ((obj), VisVideo))
#define VISUAL_VIDEO_ATTRIBUTE_OPTIONS(obj) (VISUAL_CHECK_CAST ((obj), VisVideoAttributeOptions))
#define VISUAL_VIDEO_ATTRIBUTE_OPTIONS_GL_ENTRY(options, attr, val)
Typedefs
typedef struct _VisVideo VisVideo
typedef struct
_VisVideoAttributeOptions VisVideoAttributeOptions
typedef int(* VisVideoCustomCompositeFunc)(VisVideo *dest, VisVideo *src)
A custom composite function needs this signature.
Enumerations
enum VisVideoDepth {
VISUAL_VIDEO_DEPTH_NONE = 0, VISUAL_VIDEO_DEPTH_8BIT = 1, VISUAL_VIDEO_DEPTH_16BIT = 2, VISUAL_VIDEO_DEPTH_24BIT = 4,
VISUAL_VIDEO_DEPTH_32BIT = 8, VISUAL_VIDEO_DEPTH_GL = 16, VISUAL_VIDEO_DEPTH_ENDLIST = 32, VISUAL_VIDEO_DEPTH_ERROR = -1,
VISUAL_VIDEO_DEPTH_ALL
}
Enumerate that defines video depths for use within plugins, libvisual functions, etc.
enum VisVideoRotateDegrees { VISUAL_VIDEO_ROTATE_NONE = 0, VISUAL_VIDEO_ROTATE_90 = 1, VISUAL_VIDEO_ROTATE_180 = 2, VISUAL_VIDEO_ROTATE_270 = 3 }
Enumerate that defines video rotate types, used with the visual_video_rotate_*() functions.
enum VisVideoMirrorOrient { VISUAL_VIDEO_MIRROR_NONE = 0, VISUAL_VIDEO_MIRROR_X = 1, VISUAL_VIDEO_MIRROR_Y = 2 }
Enumerate that defines the video mirror types, used with the visual_video_mirror_*() functions.
enum VisVideoScaleMethod { VISUAL_VIDEO_SCALE_NEAREST = 0, VISUAL_VIDEO_SCALE_BILINEAR = 1 }
Enumerate that defines the different methods of scaling within VisVideo.
enum VisVideoCompositeType {
VISUAL_VIDEO_COMPOSITE_TYPE_NONE = 0, VISUAL_VIDEO_COMPOSITE_TYPE_SRC, VISUAL_VIDEO_COMPOSITE_TYPE_COLORKEY, VISUAL_VIDEO_COMPOSITE_TYPE_SURFACE,
VISUAL_VIDEO_COMPOSITE_TYPE_SURFACECOLORKEY, VISUAL_VIDEO_COMPOSITE_TYPE_CUSTOM
}
Enumerate that defines the different blitting methods for a VisVideo.
Functions
VisVideo * visual_video_new (void)
Creates a new VisVideo structure, without an associated screen buffer.
int visual_video_init (VisVideo *video)
Initializes a VisVideo, this will set the allocated flag for the object to FALSE.
VisVideo * visual_video_new_with_buffer (int width, int height, VisVideoDepth depth)
Creates a new VisVideo and also allocates a buffer.
int visual_video_free_buffer (VisVideo *video)
Frees the buffer that relates to the VisVideo.
int visual_video_allocate_buffer (VisVideo *video)
Allocates a buffer for the VisVideo.
int visual_video_have_allocated_buffer (VisVideo *video)
Checks if the given VisVideo has a private allocated buffer.
int visual_video_clone (VisVideo *dest, VisVideo *src)
Clones the information from a VisVideo to another.
int visual_video_compare (VisVideo *src1, VisVideo *src2)
Checks if two VisVideo objects are the same depth, pitch and dimension wise.
int visual_video_compare_ignore_pitch (VisVideo *src1, VisVideo *src2)
Checks if two VisVideo objects are the same depth and dimension wise.
int visual_video_set_palette (VisVideo *video, VisPalette *pal)
Sets a palette to a VisVideo.
int visual_video_set_buffer (VisVideo *video, void *buffer)
Sets a buffer to a VisVideo.
int visual_video_set_dimension (VisVideo *video, int width, int height)
Sets the dimension for a VisVideo.
int visual_video_set_pitch (VisVideo *video, int pitch)
Sets the pitch for a VisVideo.
int visual_video_set_depth (VisVideo *video, VisVideoDepth depth)
Sets the depth for a VisVideo.
int visual_video_set_attributes (VisVideo *video, int width, int height, int pitch, VisVideoDepth depth)
Sets all attributes for a VisVideo.
int visual_video_get_size (VisVideo *video)
void * visual_video_get_pixels (VisVideo *video)
Retrieves the pixel buffer from a VisVideo.
VisBuffer * visual_video_get_buffer (VisVideo *video)
Retrieves the VisBuffer object from a VisVideo.
int visual_video_depth_is_supported (int depthflag, VisVideoDepth depth)
Checks if a certain depth is supported by checking against an ORred depthflag.
VisVideoDepth visual_video_depth_get_prev (int depthflag, VisVideoDepth depth)
Get the previous depth from the ORred depthflag.
VisVideoDepth visual_video_depth_get_next (int depthflag, VisVideoDepth depth)
Get the next depth from the ORred depthflag.
VisVideoDepth visual_video_depth_get_lowest (int depthflag)
Return the lowest supported graphical depth from the ORred depthflag.
VisVideoDepth visual_video_depth_get_highest (int depthflag)
Return the highest supported graphical depth from the ORred depthflag.
VisVideoDepth visual_video_depth_get_highest_nogl (int depthflag)
Return the highest supported depth that is NOT openGL.
int visual_video_depth_is_sane (VisVideoDepth depth)
Checks if a certain value is a sane depth.
int visual_video_depth_value_from_enum (VisVideoDepth depth)
Returns the number of bits per pixel from a VisVideoDepth enumerate value.
VisVideoDepth visual_video_depth_enum_from_value (int depthvalue)
Returns a VisVideoDepth enumerate value from bits per pixel.
int visual_video_bpp_from_depth (VisVideoDepth depth)
Returns the number of bytes per pixel from the VisVideoDepth enumerate.
VisRectangle * visual_video_get_boundary (VisVideo *video)
Converts the VisVideo it's buffer boundries to a VisRectangle.
int visual_video_region_sub (VisVideo *dest, VisVideo *src, VisRectangle *rect)
Creates a sub region of a VisVideo.
int visual_video_region_sub_by_values (VisVideo *dest, VisVideo *src, int x, int y, int width, int height)
Creates a sub region of a VisVideo likewise visual_video_region_sub() however the position and dimension is given by separated values instead of a VisRectangle.
int visual_video_region_sub_all (VisVideo *dest, VisVideo *src)
int visual_video_region_sub_with_boundary (VisVideo *dest, VisRectangle *drect, VisVideo *src, VisRectangle *srect)
int visual_video_composite_set_type (VisVideo *video, VisVideoCompositeType type)
int visual_video_composite_set_colorkey (VisVideo *video, VisColor *color)
int visual_video_composite_set_surface (VisVideo *video, uint8_t alpha)
VisVideoCustomCompositeFunc visual_video_composite_get_function (VisVideo *dest, VisVideo *src, int alpha)
int visual_video_composite_set_function (VisVideo *video, VisVideoCustomCompositeFunc compfunc)
int visual_video_blit_overlay_rectangle (VisVideo *dest, VisRectangle *drect, VisVideo *src, VisRectangle *srect, int alpha)
int visual_video_blit_overlay_rectangle_custom (VisVideo *dest, VisRectangle *drect, VisVideo *src, VisRectangle *srect, VisVideoCustomCompositeFunc compfunc)
int visual_video_blit_overlay_rectangle_scale (VisVideo *dest, VisRectangle *drect, VisVideo *src, VisRectangle *srect, int alpha, VisVideoScaleMethod scale_method)
int visual_video_blit_overlay_rectangle_scale_custom (VisVideo *dest, VisRectangle *drect, VisVideo *src, VisRectangle *srect, VisVideoScaleMethod scale_method, VisVideoCustomCompositeFunc compfunc)
int visual_video_blit_overlay (VisVideo *dest, VisVideo *src, int x, int y, int alpha)
This function blits a VisVideo into another VisVideo.
int visual_video_blit_overlay_custom (VisVideo *dest, VisVideo *src, int x, int y, VisVideoCustomCompositeFunc compfunc)
int visual_video_fill_alpha_color (VisVideo *video, VisColor *color, uint8_t density)
Sets a certain color as the alpha channel and the density for the non alpha channel colors.
int visual_video_fill_alpha (VisVideo *video, uint8_t density)
Sets a certain alpha value for the complete buffer in the VisVideo.
int visual_video_fill_alpha_rectangle (VisVideo *video, uint8_t density, VisRectangle *rect)
int visual_video_fill_color (VisVideo *video, VisColor *color)
This function is used to fill a VisVideo with one color.
int visual_video_fill_color_rectangle (VisVideo *video, VisColor *color, VisRectangle *rect)
int visual_video_flip_pixel_bytes (VisVideo *dest, VisVideo *src)
Flips the byte ordering of each pixel.
int visual_video_rotate (VisVideo *dest, VisVideo *src, VisVideoRotateDegrees degrees)
VisVideo * visual_video_rotate_new (VisVideo *src, VisVideoRotateDegrees degrees)
int visual_video_mirror (VisVideo *dest, VisVideo *src, VisVideoMirrorOrient orient)
VisVideo * visual_video_mirror_new (VisVideo *src, VisVideoMirrorOrient orient)
int visual_video_depth_transform (VisVideo *viddest, VisVideo *vidsrc)
Video depth transforms one VisVideo into another using the depth information stored within the VisVideos.
VisVideo * visual_video_zoom_new (VisVideo *src, VisVideoScaleMethod scale_method, float zoom_factor)
int visual_video_zoom_double (VisVideo *dest, VisVideo *src)
Non interpolating fast pixel doubler zoom.
int visual_video_scale (VisVideo *dest, VisVideo *src, VisVideoScaleMethod scale_method)
Scale VisVideo.
VisVideo * visual_video_scale_new (VisVideo *src, int width, int height, VisVideoScaleMethod scale_method)
Scale VisVideo, and return a newly allocated scaled VisVideo.
int visual_video_scale_depth (VisVideo *dest, VisVideo *src, VisVideoScaleMethod scale_method)
Scale VisVideo, but does an internal depth transformation when the source VisVideo is not of the same depth as the destination VisVideo.
VisVideo * visual_video_scale_depth_new (VisVideo *src, int width, int height, VisVideoDepth depth, VisVideoScaleMethod scale_method)
Creates a new scaled VisVideo, but does an internal depth transformation when the source VisVideo is not of the same depth as the destination VisVideo.
int _lv_blit_overlay_alphasrc_mmx (VisVideo *dest, VisVideo *src)
int _lv_scale_bilinear_32_mmx (VisVideo *dest, VisVideo *src)
Define Documentation
#define VISUAL_VIDEO (obj) (VISUAL_CHECK_CAST ((obj), VisVideo))
Definition at line 44 of file lv_video.h.
#define VISUAL_VIDEO_ATTRIBUTE_OPTIONS (obj) (VISUAL_CHECK_CAST ((obj), VisVideoAttributeOptions))
Definition at line 45 of file lv_video.h.
#define VISUAL_VIDEO_ATTRIBUTE_OPTIONS_GL_ENTRY (options, attr, val)
Value:
options.gl_attributes[attr].attribute = attr;  \
    options.gl_attributes[attr].value = val;       \
    options.gl_attributes[attr].mutated = TRUE;
Definition at line 47 of file lv_video.h.
Typedef Documentation
typedef struct _VisVideo VisVideo
Definition at line 113 of file lv_video.h.
typedef struct _VisVideoAttributeOptions VisVideoAttributeOptions
Definition at line 114 of file lv_video.h.
typedef int(* VisVideoCustomCompositeFunc)(VisVideo *dest, VisVideo *src)
A custom composite function needs this signature.
Custom composite functions can be used to overload the normal libvisual overlay functions, these are used by the different blit methods. The following template should be used for custom composite functions:
int custom_composite (VisVideo *dest, VisVideo *src) { int i uint8_t *destbuf = dest->pixels; uint8_t *srcbuf = src->pixels;
for (i = 0; i < src->height; i++) { for (j = 0; j < src->width; j++) {
destbuf += dest->bpp; srcbuf += src->bpp; }
destbuf += dest->pitch - (dest->width * dest->bpp); srcbuf += src->pitch - (src->width * src->bpp); } }
It's very important that the function is pitch (rowstride, bytes per line) aware, also for width and height, it's compulsory to look at the source, and not the dest. Also be aware that the custom composite function is correct for the depth you're using, if you want to add depth awareness to the function, you could do this by checking dest->depth.
See also:
visual_video_blit_overlay_rectangle_custom
visual_video_blit_overlay_rectangle_scale_custom
visual_video_blit_overlay_custom
dest a pointer to the dest visvideo source.
src A pointer to the source VisVideo source.
Returns:
VISUAL_OK on succes -VISUAL_ERROR_GENERAL on error.
Definition at line 156 of file lv_video.h.
Enumeration Type Documentation
enum VisVideoCompositeType
Enumerate that defines the different blitting methods for a VisVideo.
Enumerator:
VISUAL_VIDEO_COMPOSITE_TYPE_NONE
No composite set, use default.
VISUAL_VIDEO_COMPOSITE_TYPE_SRC
Source alpha channel.
VISUAL_VIDEO_COMPOSITE_TYPE_COLORKEY
Colorkey alpha.
VISUAL_VIDEO_COMPOSITE_TYPE_SURFACE
One alpha channel for the complete surface.
VISUAL_VIDEO_COMPOSITE_TYPE_SURFACECOLORKEY
Use surface alpha on colorkey.
VISUAL_VIDEO_COMPOSITE_TYPE_CUSTOM
Custom composite function (looks up on the source VisVideo.
Definition at line 103 of file lv_video.h.
enum VisVideoDepth
Enumerate that defines video depths for use within plugins, libvisual functions, etc.
Enumerator:
VISUAL_VIDEO_DEPTH_NONE
No video surface flag.
VISUAL_VIDEO_DEPTH_8BIT
8 bits indexed surface flag.
VISUAL_VIDEO_DEPTH_16BIT
16 bits 5-6-5 surface flag.
VISUAL_VIDEO_DEPTH_24BIT
24 bits surface flag.
VISUAL_VIDEO_DEPTH_32BIT
32 bits surface flag.
VISUAL_VIDEO_DEPTH_GL
openGL surface flag.
VISUAL_VIDEO_DEPTH_ENDLIST
Used to mark the end of the depth list.
VISUAL_VIDEO_DEPTH_ERROR
Used when there is an error.
VISUAL_VIDEO_DEPTH_ALL
All graphical depths.
Definition at line 57 of file lv_video.h.
enum VisVideoMirrorOrient
Enumerate that defines the video mirror types, used with the visual_video_mirror_*() functions.
Enumerator:
VISUAL_VIDEO_MIRROR_NONE
No mirroring.
VISUAL_VIDEO_MIRROR_X
Mirror on the X ax.
VISUAL_VIDEO_MIRROR_Y
Mirror on the Y ax.
Definition at line 86 of file lv_video.h.
enum VisVideoRotateDegrees
Enumerate that defines video rotate types, used with the visual_video_rotate_*() functions.
Enumerator:
VISUAL_VIDEO_ROTATE_NONE
No rotating.
VISUAL_VIDEO_ROTATE_90
90 degrees rotate.
VISUAL_VIDEO_ROTATE_180
180 degrees rotate.
VISUAL_VIDEO_ROTATE_270
270 degrees rotate.
Definition at line 76 of file lv_video.h.
enum VisVideoScaleMethod
Enumerate that defines the different methods of scaling within VisVideo.
Enumerator:
VISUAL_VIDEO_SCALE_NEAREST
Nearest neighbour.
VISUAL_VIDEO_SCALE_BILINEAR
Bilinearly interpolated.
Definition at line 95 of file lv_video.h.
Function Documentation
int _lv_blit_overlay_alphasrc_mmx (VisVideo * dest, VisVideo * src)
Definition at line 28 of file lv_video_simd.c.
Referenced by blit_overlay_alphasrc().
int _lv_scale_bilinear_32_mmx (VisVideo * dest, VisVideo * src)
Definition at line 76 of file lv_video_simd.c.
Referenced by visual_video_scale().
int visual_video_allocate_buffer (VisVideo * video)
Allocates a buffer for the VisVideo.
Allocates based on the VisVideo it's information about the screen dimension and depth.
Parameters:
video Pointer to a VisVideo that needs an allocated buffer.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_HAS_PIXELS on failure.
Definition at line 179 of file lv_video.c.
Referenced by visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), visual_bin_sync(), visual_bitmap_load(), visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_new_with_buffer(), and visual_video_scale_depth().
int visual_video_blit_overlay (VisVideo * dest, VisVideo * src, int x, int y, int alpha)
This function blits a VisVideo into another VisVideo.
Placement can be done and there is support for the alpha channel.
Parameters:
dest Pointer to the destination VisVideo in which the source is overlayed.
src Pointer to the source VisVideo which is overlayed in the destination.
x Horizontal placement offset.
y Vertical placement offset.
alpha Sets if we want to check the alpha channel. Use FALSE or TRUE here.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_INVALID_DEPTH or -VISUAL_ERROR_VIDEO_OUT_OF_BOUNDS on failure.
Definition at line 867 of file lv_video.c.
Referenced by visual_actor_run(), visual_video_depth_transform(), visual_video_mirror(), visual_video_rotate(), and visual_video_scale().
int visual_video_blit_overlay_custom (VisVideo * dest, VisVideo * src, int x, int y, VisVideoCustomCompositeFunc compfunc)
Definition at line 873 of file lv_video.c.
Referenced by visual_video_blit_overlay(), and visual_video_blit_overlay_rectangle_custom().
int visual_video_blit_overlay_rectangle (VisVideo * dest, VisRectangle * drect, VisVideo * src, VisRectangle * srect, int alpha)
Definition at line 767 of file lv_video.c.
int visual_video_blit_overlay_rectangle_custom (VisVideo * dest, VisRectangle * drect, VisVideo * src, VisRectangle * srect, VisVideoCustomCompositeFunc compfunc)
Definition at line 773 of file lv_video.c.
Referenced by visual_video_blit_overlay_rectangle(), and visual_video_blit_overlay_rectangle_scale_custom().
int visual_video_blit_overlay_rectangle_scale (VisVideo * dest, VisRectangle * drect, VisVideo * src, VisRectangle * srect, int alpha, VisVideoScaleMethod scale_method)
Definition at line 805 of file lv_video.c.
int visual_video_blit_overlay_rectangle_scale_custom (VisVideo * dest, VisRectangle * drect, VisVideo * src, VisRectangle * srect, VisVideoScaleMethod scale_method, VisVideoCustomCompositeFunc compfunc)
Definition at line 812 of file lv_video.c.
Referenced by visual_video_blit_overlay_rectangle_scale().
int visual_video_bpp_from_depth (VisVideoDepth depth)
Returns the number of bytes per pixel from the VisVideoDepth enumerate.
Parameters:
depth The VisVideodepth enumerate value from which the bytes per pixel needs to be returned.
Returns:
The number of bytes per pixel, -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 556 of file lv_video.c.
Referenced by visual_video_set_depth().
int visual_video_clone (VisVideo * dest, VisVideo * src)
Clones the information from a VisVideo to another.
This will clone the depth, dimension and screen pitch into another VisVideo. It doesn't clone the palette or buffer.
Parameters:
dest Pointer to a destination VisVideo in which the information needs to be placed.
src Pointer to a source VisVideo from which the information needs to be obtained.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 232 of file lv_video.c.
Referenced by visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), and visual_bin_sync().
int visual_video_compare (VisVideo * src1, VisVideo * src2)
Checks if two VisVideo objects are the same depth, pitch and dimension wise.
Parameters:
src1 Pointer to the first VisVideo that is used in the compare.
src2 Pointer to the second VisVideo that is used in the compare.
Returns:
FALSE on different, TRUE on same, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 244 of file lv_video.c.
Referenced by blit_overlay_noalpha(), and visual_video_flip_pixel_bytes().
int visual_video_compare_ignore_pitch (VisVideo * src1, VisVideo * src2)
Checks if two VisVideo objects are the same depth and dimension wise.
Parameters:
src1 Pointer to the first VisVideo that is used in the compare.
src2 Pointer to the second VisVideo that is used in the compare.
Returns:
FALSE on different, TRUE on same, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 259 of file lv_video.c.
Referenced by visual_video_compare(), and visual_video_scale().
VisVideoCustomCompositeFunc visual_video_composite_get_function (VisVideo * dest, VisVideo * src, int alpha)
Definition at line 735 of file lv_video.c.
Referenced by visual_video_blit_overlay(), visual_video_blit_overlay_rectangle(), and visual_video_blit_overlay_rectangle_scale().
int visual_video_composite_set_colorkey (VisVideo * video, VisColor * color)
Definition at line 705 of file lv_video.c.
int visual_video_composite_set_function (VisVideo * video, VisVideoCustomCompositeFunc compfunc)
Definition at line 726 of file lv_video.c.
int visual_video_composite_set_surface (VisVideo * video, uint8_t alpha)
Definition at line 717 of file lv_video.c.
int visual_video_composite_set_type (VisVideo * video, VisVideoCompositeType type)
Definition at line 696 of file lv_video.c.
VisVideoDepth visual_video_depth_enum_from_value (int depthvalue)
Returns a VisVideoDepth enumerate value from bits per pixel.
Parameters:
depthvalue Integer containing the number of bits per pixel.
Returns:
The corespondending enumerate value or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 533 of file lv_video.c.
Referenced by visual_bitmap_load().
VisVideoDepth visual_video_depth_get_highest (int depthflag)
Return the highest supported graphical depth from the ORred depthflag.
Parameters:
depthflag The ORred depthflag that we check against.
Returns:
The highest supported depth or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 449 of file lv_video.c.
Referenced by visual_video_depth_get_highest_nogl().
VisVideoDepth visual_video_depth_get_highest_nogl (int depthflag)
Return the highest supported depth that is NOT openGL.
Parameters:
depthflag The ORred depthflag that we check against.
Returns:
The highest supported depth that is not openGL or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 466 of file lv_video.c.
Referenced by visual_bin_connect().
VisVideoDepth visual_video_depth_get_lowest (int depthflag)
Return the lowest supported graphical depth from the ORred depthflag.
Parameters:
depthflag The ORred depthflag that we check against.
Returns:
The lowest supported depth or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 444 of file lv_video.c.
VisVideoDepth visual_video_depth_get_next (int depthflag, VisVideoDepth depth)
Get the next depth from the ORred depthflag.
By giving a depth and a depthflag this returns the next supported depth checked from the depthflag.
See also:
visual_video_depth_get_prev
Parameters:
depthflag The ORred depthflag that we check against.
depth The depth of which we want the next supported depth.
Returns:
The next supported depth or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 400 of file lv_video.c.
Referenced by visual_video_depth_get_highest(), and visual_video_depth_get_lowest().
VisVideoDepth visual_video_depth_get_prev (int depthflag, VisVideoDepth depth)
Get the previous depth from the ORred depthflag.
By giving a depth and a depthflag this returns the previous supported depth checked from the depthflag.
See also:
visual_video_depth_get_next
Parameters:
depthflag The ORred depthflag that we check against.
depth The depth of which we want the previous supported depth.
Returns:
The previous supported depth or VISUAL_VIDEO_DEPTH_ERROR on failure.
Definition at line 424 of file lv_video.c.
Referenced by visual_video_depth_get_highest_nogl().
int visual_video_depth_is_sane (VisVideoDepth depth)
Checks if a certain value is a sane depth.
Parameters:
depth Depth to be checked if it's sane.
Returns:
TRUE if the depth is sane, FALSE if the depth is not sane.
Definition at line 487 of file lv_video.c.
Referenced by visual_video_depth_get_next(), visual_video_depth_get_prev(), and visual_video_depth_is_supported().
int visual_video_depth_is_supported (int depthflag, VisVideoDepth depth)
Checks if a certain depth is supported by checking against an ORred depthflag.
Parameters:
depthflag The ORred depthflag that we check against.
depth The depth that we want to test.
Returns:
TRUE when supported, FALSE when unsupported and -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 389 of file lv_video.c.
Referenced by visual_actor_video_negotiate(), visual_bin_set_depth(), visual_bin_set_morph_by_name(), visual_bin_switch_actor_by_name(), and visual_transform_video_negotiate().
int visual_video_depth_transform (VisVideo * viddest, VisVideo * vidsrc)
Video depth transforms one VisVideo into another using the depth information stored within the VisVideos.
The dimension should be equal however the pitch value of the destination may be set.
Parameters:
dest Pointer to the destination VisVideo to which the source VisVideo is transformed.
src Pointer to the source VisVideo.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL, -VISUAL_ERROR_PALETTE_NULL, -VISUAL_ERROR_PALETTE_SIZE, -VISUAL_ERROR_VIDEO_NOT_TRANSFORMED or error values returned by visual_video_blit_overlay on failure.
Definition at line 1380 of file lv_video.c.
Referenced by visual_actor_run(), visual_video_blit_overlay_custom(), and visual_video_scale_depth().
int visual_video_depth_value_from_enum (VisVideoDepth depth)
Returns the number of bits per pixel from a VisVideoDepth enumerate value.
Parameters:
depth The VisVideodepth enumerate value from which the bits per pixel needs to be returned.
Returns:
The bits per pixel or -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 511 of file lv_video.c.
int visual_video_fill_alpha (VisVideo * video, uint8_t density)
Sets a certain alpha value for the complete buffer in the VisVideo.
This function can be only used on VISUAL_VIDEO_DEPTH_32BIT surfaces.
Parameters:
video Pointer to the VisVideo in which the alpha channel density is set.
density The alpha density that is to be set.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL, -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 1001 of file lv_video.c.
Referenced by visual_video_fill_alpha_rectangle().
int visual_video_fill_alpha_color (VisVideo * video, VisColor * color, uint8_t density)
Sets a certain color as the alpha channel and the density for the non alpha channel colors.
This function can be only used on VISUAL_VIDEO_DEPTH_32BIT surfaces.
Parameters:
video Pointer to the VisVideo in which the alpha channel is made.
color Pointer to the VisColor containing the color value for the alpha channel.
density The alpha density for the other colors.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 971 of file lv_video.c.
int visual_video_fill_alpha_rectangle (VisVideo * video, uint8_t density, VisRectangle * rect)
Definition at line 1022 of file lv_video.c.
int visual_video_fill_color (VisVideo * video, VisColor * color)
This function is used to fill a VisVideo with one color.
It's highly advice to use this function to fill a VisVideo with a color instead of using visual_mem_set, the reason is that this function takes the pitch of a line in consideration. When you use a visual_mem_set on sub regions the results won't be pretty.
Parameters:
video Pointer to the VisVideo which is filled with one color
rcolor Pointer to the VisColor that is used as color. NULL is a valid color and will be interperted as black.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL, -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 1046 of file lv_video.c.
Referenced by visual_video_fill_color_rectangle().
int visual_video_fill_color_rectangle (VisVideo * video, VisColor * color, VisRectangle * rect)
Definition at line 1080 of file lv_video.c.
int visual_video_flip_pixel_bytes (VisVideo * dest, VisVideo * src)
Flips the byte ordering of each pixel.
Parameters:
dest Pointer to the destination VisVideo, which should be a clone of the source VisVideo depth, pitch, dimension wise.
src Pointer to the source VisVideo from which the bgr data is read.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NOT_INDENTICAL, -VISUAL_ERROR_VIDEO_PIXELS_NULL or -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 1117 of file lv_video.c.
int visual_video_free_buffer (VisVideo * video)
Frees the buffer that relates to the VisVideo.
Parameters:
video Pointer to a VisVideo of which the buffer needs to be freed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL, -VISUAL_ERROR_VIDEO_PIXELS_NULL or -VISUAL_ERROR_VIDEO_NO_ALLOCATED on failure.
Definition at line 157 of file lv_video.c.
Referenced by visual_bin_sync(), visual_bitmap_load(), and visual_video_allocate_buffer().
VisRectangle* visual_video_get_boundary (VisVideo * video)
Converts the VisVideo it's buffer boundries to a VisRectangle.
This means that the rectangle it's position will be set to 0, 0 and it's width and height respectively to that of the VisVideo.
Parameters:
video Pointer to the VisVideo for which the buffer boundries are requested.
Returns:
New VisRectangle, or NULL on failure
Definition at line 581 of file lv_video.c.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_color_rectangle(), visual_video_region_sub(), visual_video_region_sub_all(), and visual_video_region_sub_with_boundary().
VisBuffer* visual_video_get_buffer (VisVideo * video)
Retrieves the VisBuffer object from a VisVideo.
Parameters:
video Pointer to the VisVideo from which the VisBuffer object is requested.
Returns:
The VisBuffer object, NULL on failure.
Definition at line 382 of file lv_video.c.
void* visual_video_get_pixels (VisVideo * video)
Retrieves the pixel buffer from a VisVideo.
Parameters:
video Pointer to the VisVideo from which the pixel buffer is requested.
Returns:
The VisVideo it's pixel buffer, NULL on failure.
Definition at line 375 of file lv_video.c.
Referenced by _lv_blit_overlay_alphasrc_mmx(), _lv_scale_bilinear_32_mmx(), blit_overlay_alphasrc(), blit_overlay_colorkey(), blit_overlay_noalpha(), blit_overlay_surfacealpha(), blit_overlay_surfacealphacolorkey(), visual_bin_switch_actor(), visual_video_allocate_buffer(), visual_video_argb32_to_index8(), visual_video_argb32_to_rgb16(), visual_video_argb32_to_rgb24(), visual_video_fill_alpha(), visual_video_fill_alpha_color(), visual_video_fill_color_argb32(), visual_video_fill_color_index8(), visual_video_fill_color_rgb16(), visual_video_fill_color_rgb24(), visual_video_flip_pixel_bytes(), visual_video_flip_pixel_bytes_color16(), visual_video_flip_pixel_bytes_color24(), visual_video_flip_pixel_bytes_color32(), visual_video_free_buffer(), visual_video_index8_to_argb32(), visual_video_index8_to_rgb16(), visual_video_index8_to_rgb24(), visual_video_region_sub(), visual_video_rgb16_to_argb32(), visual_video_rgb16_to_index8(), visual_video_rgb16_to_rgb24(), visual_video_rgb24_to_argb32(), visual_video_rgb24_to_index8(), visual_video_rgb24_to_rgb16(), visual_video_scale_bilinear_color16(), visual_video_scale_bilinear_color24(), visual_video_scale_bilinear_color32(), visual_video_scale_bilinear_color8(), visual_video_scale_nearest_color16(), visual_video_scale_nearest_color24(), visual_video_scale_nearest_color32(), visual_video_scale_nearest_color8(), visual_video_zoom_color16(), visual_video_zoom_color32(), and visual_video_zoom_color8().
int visual_video_get_size (VisVideo * video)
Definition at line 368 of file lv_video.c.
Referenced by blit_overlay_noalpha(), visual_bin_switch_actor(), and visual_video_allocate_buffer().
int visual_video_have_allocated_buffer (VisVideo * video)
Checks if the given VisVideo has a private allocated buffer.
Parameters:
video Pointer to the VisVideo of which we want to know if it has a private allocated buffer.
Returns:
TRUE if the VisVideo has an allocated buffer, or FALSE if not.
Definition at line 211 of file lv_video.c.
int visual_video_init (VisVideo * video)
Initializes a VisVideo, this will set the allocated flag for the object to FALSE.
When visual_video_new() is used, this function should not be used since visual_video_new() makes sure that the VisObject initialization is done right. It's best to use this function in cases where the VisVideo was not being allocated. To cleanup the none allocated VisVideo you can still use visual_object_unref(). When it loses all references, it will get internally cleaned up. Added to that, don't use this function to reset your VisVideo.
See also:
visual_video_new
Parameters:
video Pointer to the VisVideo that is to be initialized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 106 of file lv_video.c.
Referenced by visual_video_new().
int visual_video_mirror (VisVideo * dest, VisVideo * src, VisVideoMirrorOrient orient)
Definition at line 1303 of file lv_video.c.
Referenced by visual_video_mirror_new().
VisVideo* visual_video_mirror_new (VisVideo * src, VisVideoMirrorOrient orient)
Definition at line 1329 of file lv_video.c.
VisVideo* visual_video_new (void)
Creates a new VisVideo structure, without an associated screen buffer.
Returns:
A newly allocated VisVideo.
Definition at line 91 of file lv_video.c.
Referenced by visual_bin_switch_actor(), visual_bin_switch_actor_by_name(), visual_bitmap_load_new_video(), visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_alpha_rectangle(), visual_video_fill_color_rectangle(), visual_video_new_with_buffer(), and visual_video_scale_depth().
VisVideo* visual_video_new_with_buffer (int width, int height, VisVideoDepth depth)
Creates a new VisVideo and also allocates a buffer.
Parameters:
width The width for the new buffer.
height The height for the new buffer.
depth The depth being used.
Returns:
A newly allocates VisVideo with a buffer allocated.
Definition at line 136 of file lv_video.c.
Referenced by visual_video_mirror_new(), visual_video_rotate_new(), visual_video_scale_depth_new(), and visual_video_scale_new().
int visual_video_region_sub (VisVideo * dest, VisVideo * src, VisRectangle * rect)
Creates a sub region of a VisVideo.
An extra reference to the src VisVideo is created. The region should fall completely within the src, else the region won't be created. Notice that a sub region is not a copy
See also:
visual_video_region_sub_by_values
visual_video_region_copy
Parameters:
dest Pointer to the destination VisVideo, There should not be a buffer allocated for this VisVideo.
src Pointer to the source VisVideo from which a subregion is created.
rect Pointer to the rectangle containing the position and dimension information.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL, -VISUAL_ERROR_RECTANGLE_NULL or -VISUAL_ERROR_VIDEO_OUT_OF_BOUNDS on failure.
Definition at line 588 of file lv_video.c.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_scale_custom(), visual_video_fill_alpha_rectangle(), visual_video_region_sub_all(), visual_video_region_sub_by_values(), and visual_video_region_sub_with_boundary().
int visual_video_region_sub_all (VisVideo * dest, VisVideo * src)
Definition at line 653 of file lv_video.c.
int visual_video_region_sub_by_values (VisVideo * dest, VisVideo * src, int x, int y, int width, int height)
Creates a sub region of a VisVideo likewise visual_video_region_sub() however the position and dimension is given by separated values instead of a VisRectangle.
See also:
visual_video_region_sub
Parameters:
dest Pointer to the destination VisVideo, There should not be a buffer allocated for this VisVideo.
src Pointer to the source VisVideo from which a subregion is created.
x X Position of the sub region.
y Y Position of the sub region.
width Width of the sub region.
height Height Height of the sub region.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_OUT_OF_BOUNDS on failure.
Definition at line 636 of file lv_video.c.
int visual_video_region_sub_with_boundary (VisVideo * dest, VisRectangle * drect, VisVideo * src, VisRectangle * srect)
Definition at line 670 of file lv_video.c.
Referenced by visual_video_blit_overlay_custom(), visual_video_blit_overlay_rectangle_custom(), and visual_video_fill_color_rectangle().
int visual_video_rotate (VisVideo * dest, VisVideo * src, VisVideoRotateDegrees degrees)
Definition at line 1138 of file lv_video.c.
Referenced by visual_video_rotate_new().
VisVideo* visual_video_rotate_new (VisVideo * src, VisVideoRotateDegrees degrees)
Definition at line 1178 of file lv_video.c.
int visual_video_scale (VisVideo * dest, VisVideo * src, VisVideoScaleMethod scale_method)
Scale VisVideo.
Parameters:
dest Pointer to VisVideo object for storing scaled image.
src Pointer to VisVideo object whose image is to be scaled.
scale_method Scaling method to use.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_INVALID_DEPTH on failure.
Definition at line 1501 of file lv_video.c.
Referenced by visual_video_blit_overlay_rectangle_scale_custom(), visual_video_scale_depth(), and visual_video_scale_new().
int visual_video_scale_depth (VisVideo * dest, VisVideo * src, VisVideoScaleMethod scale_method)
Scale VisVideo, but does an internal depth transformation when the source VisVideo is not of the same depth as the destination VisVideo.
See also:
visual_video_scale
Parameters:
dest Pointer to the destination VisVideo in which the scaled version is stored
src Pointer to the source VisVideo whose image is to be scaled.
scale_method Scaling method to use.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_IMPOSSIBLE, -VISUAL_ERROR_VIDEO_NULL or error values returned by visual_video_scale() on failure.
Definition at line 1577 of file lv_video.c.
Referenced by visual_video_scale_depth_new().
VisVideo* visual_video_scale_depth_new (VisVideo * src, int width, int height, VisVideoDepth depth, VisVideoScaleMethod scale_method)
Creates a new scaled VisVideo, but does an internal depth transformation when the source VisVideo is not of the same depth as the destination VisVideo.
See also:
visual_video_scale_depth
Parameters:
src Pointer to the source VisVideo whose image is to be scaled.
width The width of the new scaled VisVideo.
height The height of the new scaled VisVideo.
depth The depth of the new scaled VisVideo.
scale_method Scaling method to use.
Returns:
A newly allocated scaled version of the source VisVideo with the given width, height and depth, NULL on failure.
Definition at line 1605 of file lv_video.c.
VisVideo* visual_video_scale_new (VisVideo * src, int width, int height, VisVideoScaleMethod scale_method)
Scale VisVideo, and return a newly allocated scaled VisVideo.
Parameters:
src Pointer to VisVideo object whose image is to be scaled.
scale_method Scaling method to use.
width New width.
height New height.
Returns:
A newly allocated scaled VisVideo, NULL on failure.
Definition at line 1564 of file lv_video.c.
int visual_video_set_attributes (VisVideo * video, int width, int height, int pitch, VisVideoDepth depth)
Sets all attributes for a VisVideo.
Used to set width, height, pitch and the depth for a VisVideo.
Parameters:
video Pointer to a VisVideo to which the depth is set.
width The width of the surface.
height The height of the surface.
pitch The pitch or rowstride of the surface.
depth The depth coohsen from the VisVideoDepth enumerate.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 357 of file lv_video.c.
Referenced by visual_video_blit_overlay_rectangle_scale_custom(), visual_video_init(), visual_video_region_sub(), and visual_video_scale_depth().
int visual_video_set_buffer (VisVideo * video, void * buffer)
Sets a buffer to a VisVideo.
Links a sreenbuffer to the VisVideo.
Warning:
The given video must be one previously created with visual_video_new(), and not with visual_video_new_with_buffer().
Parameters:
video Pointer to a VisVideo to which a buffer needs to be linked.
buffer Pointer to a buffer that needs to be linked with the VisVideo.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_HAS_ALLOCATED on failure.
Definition at line 290 of file lv_video.c.
Referenced by visual_bin_sync(), visual_video_init(), and visual_video_region_sub().
int visual_video_set_depth (VisVideo * video, VisVideoDepth depth)
Sets the depth for a VisVideo.
Used to set the depth for a surface. This will also define the number of bytes per pixel.
Parameters:
video Pointer to a VisVideo to which the depth is set.
depth The depth choosen from the VisVideoDepth enumerate.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 347 of file lv_video.c.
Referenced by visual_bin_set_depth(), visual_bin_switch_actor_by_name(), visual_bitmap_load(), visual_video_blit_overlay_custom(), visual_video_clone(), visual_video_new_with_buffer(), and visual_video_set_attributes().
int visual_video_set_dimension (VisVideo * video, int width, int height)
Sets the dimension for a VisVideo.
Used to set the dimension for a surface.
Parameters:
video Pointer to a VisVideo to which the dimension is set.
width The width of the surface.
height The height of the surface.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 319 of file lv_video.c.
Referenced by visual_bin_switch_actor_by_name(), visual_bitmap_load(), visual_video_blit_overlay_custom(), visual_video_clone(), visual_video_new_with_buffer(), and visual_video_set_attributes().
int visual_video_set_palette (VisVideo * video, VisPalette * pal)
Sets a palette to a VisVideo.
Links a VisPalette to the VisVideo.
Parameters:
video Pointer to a VisVideo to which a VisPalette needs to be linked.
pal Pointer to a Vispalette that needs to be linked with the VisVideo.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 277 of file lv_video.c.
Referenced by visual_actor_run(), visual_bitmap_load(), visual_morph_run(), visual_video_init(), and visual_video_region_sub().
int visual_video_set_pitch (VisVideo * video, int pitch)
Sets the pitch for a VisVideo.
Used to set the screen pitch for a surface. If the pitch doesn't differ from the screen width * bpp you only need to call the visual_video_set_dimension method.
Parameters:
video Pointer to a VisVideo to which the pitch is set.
pitch The screen pitch in bytes per line.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL or -VISUAL_ERROR_VIDEO_INVALID_BPP on failure.
Definition at line 333 of file lv_video.c.
Referenced by visual_bin_switch_actor_by_name(), visual_video_clone(), and visual_video_set_attributes().
int visual_video_zoom_double (VisVideo * dest, VisVideo * src)
Non interpolating fast pixel doubler zoom.
Parameters:
dest Pointer to destination VisVideo in which the pixel doubled VisVideo is stored.
src Pointer to source VisVideo that is pixel doubled.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_VIDEO_NULL on failure.
Definition at line 1466 of file lv_video.c.
VisVideo* visual_video_zoom_new (VisVideo * src, VisVideoScaleMethod scale_method, float zoom_factor)