libvisual: VisPlugin
VisPlugin
Data Structures
struct _VisPluginRef
The VisPluginRef data structure contains information about the plugins and does refcounting.
struct _VisPluginInfo
The VisPluginInfo data structure contains information about a plugin and is filled within the plugin itself.
struct _VisPluginData
The VisPluginData structure is the main plugin structure, every plugin is encapsulated in this.
struct _VisPluginEnviron
The VisPluginEnviron is used to setup a pre realize/init environment for plugins.
Defines
#define VISUAL_PLUGINREF(obj) (VISUAL_CHECK_CAST ((obj), VisPluginRef))
#define VISUAL_PLUGININFO(obj) (VISUAL_CHECK_CAST ((obj), VisPluginInfo))
#define VISUAL_PLUGINDATA(obj) (VISUAL_CHECK_CAST ((obj), VisPluginData))
#define VISUAL_PLUGINENVIRON(obj) (VISUAL_CHECK_CAST ((obj), VisPluginEnviron))
#define VISUAL_PLUGIN_API_VERSION 3004
Indicates at which version the plugin API is.
#define VISUAL_PLUGIN_LICENSE_GPLv1 "GPLv1"
Standard defination for GPLv1 plugins, use this for the .license entry in VisPluginInfo.
#define VISUAL_PLUGIN_LICENSE_GPL "GPLv2"
Standard defination for GPLv2 plugins, use this for the .license entry in VisPluginInfo.
#define VISUAL_PLUGIN_LICENSE_GPLv3 "GPLv3"
Standard defination for GPLv3 plugins, use this for the .license entry in VisPluginInfo.
#define VISUAL_PLUGIN_LICENSE_LGPL "LGPL"
Standard defination for LGPL plugins, use this for the .license entry in VisPluginInfo.
#define VISUAL_PLUGIN_LICENSE_BSD "BSD"
Standard defination for BSD plugins, use this for the .license entry in VisPluginInfo.
#define VISUAL_PLUGIN_VERSION_TAG "__lv_plugin_libvisual_api_version"
#define VISUAL_PLUGIN_API_VERSION_VALIDATOR
Typedefs
typedef struct _VisPluginRef VisPluginRef
typedef struct _VisPluginInfo VisPluginInfo
typedef struct _VisPluginData VisPluginData
typedef struct _VisPluginEnviron VisPluginEnviron
typedef const VisPluginInfo *(* VisPluginGetInfoFunc)(void)
This is the signature for the 'get_plugin_info' function every libvisual plugin needs to have.
typedef int(* VisPluginInitFunc)(VisPluginData *plugin)
Every libvisual plugin that is loaded by the libvisual plugin loader needs this signature for it's intialize function.
typedef int(* VisPluginCleanupFunc)(VisPluginData *plugin)
Every libvisual plugin that is loaded by the libvisual plugin loader needs this signature for it's cleanup function.
typedef int(* VisPluginEventsFunc)(VisPluginData *plugin, VisEventQueue *events)
This is the signature for the event handler within libvisual plugins.
Enumerations
enum VisPluginFlags { VISUAL_PLUGIN_FLAG_NONE = 0, VISUAL_PLUGIN_FLAG_NOT_REENTRANT = 1, VISUAL_PLUGIN_FLAG_SPECIAL = 2 }
Enumerate to define the plugin flags.
enum VisPluginTypeDepth { VISUAL_PLUGIN_TYPE_DEPTH_NONE = 0, VISUAL_PLUGIN_TYPE_DEPTH_DOMAIN = 1, VISUAL_PLUGIN_TYPE_DEPTH_PACKAGE = 2, VISUAL_PLUGIN_TYPE_DEPTH_TYPE = 3 }
Enumerate to check the depth of the type wildcard/defination used, used together with the visual_plugin_type functions.
enum VisPluginType { VISUAL_PLUGIN_TYPE_ACTOR, VISUAL_PLUGIN_TYPE_INPUT, VISUAL_PLUGIN_TYPE_MORPH, VISUAL_PLUGIN_TYPE_TRANSFORM }
Functions
VisPluginInfo * visual_plugin_info_new (void)
Creates a new VisPluginInfo structure.
int visual_plugin_info_copy (VisPluginInfo *dest, VisPluginInfo *src)
Copies data from one VisPluginInfo to another, this does not copy everything but only things that are needed in the local copy for the plugin registry.
int visual_plugin_events_pump (VisPluginData *plugin)
Pumps the queued events into the plugin it's event handler if it has one.
VisEventQueue * visual_plugin_get_eventqueue (VisPluginData *plugin)
Gives the event queue from a VisPluginData.
VisPluginInfo * visual_plugin_get_info (VisPluginData *plugin)
Gives the VisPluginInfo related to a VisPluginData.
VisParamContainer * visual_plugin_get_params (VisPluginData *plugin)
Gives the VisParamContainer related to a VisPluginData.
VisRandomContext * visual_plugin_get_random_context (VisPluginData *plugin)
Gives the VisRandomContext related to a VisPluginData.
void * visual_plugin_get_specific (VisPluginData *plugin)
Retrieves the plugin specific part of a plugin.
VisPluginRef * visual_plugin_ref_new (void)
Creates a new VisPluginRef structure.
VisPluginData * visual_plugin_new (void)
Creates a new VisPluginData structure.
int visual_plugin_unload (VisPluginData *plugin)
Private function to unload a plugin.
VisPluginData * visual_plugin_load (VisPluginRef *ref)
Private function to load a plugin.
int visual_plugin_realize (VisPluginData *plugin)
Private function to realize the plugin.
VisPluginRef * visual_plugin_get_reference (const char *pluginpath)
Private function to create VisPluginRefs from plugins.
int visual_plugin_get_api_version (void)
Gives the VISUAL_PLUGIN_API_VERSION value for which the library is compiled.
const char * visual_plugin_type_get_domain (const char *type)
Get the domain part from a plugin type string.
const char * visual_plugin_type_get_package (const char *type)
Get the package part from a plugin type string.
const char * visual_plugin_type_get_type (const char *type)
Get the type part from a plugin type string.
VisPluginTypeDepth visual_plugin_type_get_depth (const char *type)
Get the depth of a plugin type string.
int visual_plugin_type_member_of (const char *domain, const char *type)
Check if a certain plugin type string falls within the domain of the other.
const char * visual_plugin_type_get_flags (const char *type)
Retrieves the flags section from the plugin type string.
int visual_plugin_type_has_flag (const char *type, const char *flag)
Checks if a certain flag is found within a plugin type string.
VisPluginEnviron * visual_plugin_environ_new (const char *type, VisObject *envobj)
Creates a VisPluginEnviron structure.
int visual_plugin_environ_add (VisPluginData *plugin, VisPluginEnviron *enve)
Adds a VisPluginEnviron to the plugin its environment list.
int visual_plugin_environ_remove (VisPluginData *plugin, const char *type)
Removes a VisPluginEnviron from the plugin it's environment list.
VisObject * visual_plugin_environ_get (VisPluginData *plugin, const char *type)
Retrieves a VisPluginEnviron from the plugin it's environment list.
Define Documentation
#define VISUAL_PLUGIN_API_VERSION 3004
Indicates at which version the plugin API is.
Definition at line 52 of file lv_plugin.h.
Referenced by visual_plugin_get_api_version(), and visual_plugin_get_reference().
#define VISUAL_PLUGIN_API_VERSION_VALIDATOR
Value:
VISUAL_C_LINKAGE const int __lv_plugin_libvisual_api_version = \
                        VISUAL_PLUGIN_API_VERSION;
Definition at line 80 of file lv_plugin.h.
#define VISUAL_PLUGIN_LICENSE_BSD "BSD"
Standard defination for BSD plugins, use this for the .license entry in VisPluginInfo.
Definition at line 77 of file lv_plugin.h.
#define VISUAL_PLUGIN_LICENSE_GPL "GPLv2"
Standard defination for GPLv2 plugins, use this for the .license entry in VisPluginInfo.
Definition at line 62 of file lv_plugin.h.
#define VISUAL_PLUGIN_LICENSE_GPLv1 "GPLv1"
Standard defination for GPLv1 plugins, use this for the .license entry in VisPluginInfo.
Definition at line 57 of file lv_plugin.h.
#define VISUAL_PLUGIN_LICENSE_GPLv3 "GPLv3"
Standard defination for GPLv3 plugins, use this for the .license entry in VisPluginInfo.
Definition at line 68 of file lv_plugin.h.
#define VISUAL_PLUGIN_LICENSE_LGPL "LGPL"
Standard defination for LGPL plugins, use this for the .license entry in VisPluginInfo.
Definition at line 73 of file lv_plugin.h.
#define VISUAL_PLUGIN_VERSION_TAG "__lv_plugin_libvisual_api_version"
Definition at line 79 of file lv_plugin.h.
Referenced by visual_plugin_get_reference().
#define VISUAL_PLUGINDATA (obj) (VISUAL_CHECK_CAST ((obj), VisPluginData))
Definition at line 46 of file lv_plugin.h.
#define VISUAL_PLUGINENVIRON (obj) (VISUAL_CHECK_CAST ((obj), VisPluginEnviron))
Definition at line 47 of file lv_plugin.h.
#define VISUAL_PLUGININFO (obj) (VISUAL_CHECK_CAST ((obj), VisPluginInfo))
Definition at line 45 of file lv_plugin.h.
Referenced by visual_plugin_get_reference(), and visual_plugin_load().
#define VISUAL_PLUGINREF (obj) (VISUAL_CHECK_CAST ((obj), VisPluginRef))
Definition at line 44 of file lv_plugin.h.
Typedef Documentation
typedef int(* VisPluginCleanupFunc)(VisPluginData *plugin)
Every libvisual plugin that is loaded by the libvisual plugin loader needs this signature for it's cleanup function.
plugin Pointer to the VisPluginData instance structure.
Returns:
0 on succes -1 on error.
Definition at line 154 of file lv_plugin.h.
typedef struct _VisPluginData VisPluginData
Definition at line 116 of file lv_plugin.h.
typedef struct _VisPluginEnviron VisPluginEnviron
Definition at line 117 of file lv_plugin.h.
typedef int(* VisPluginEventsFunc)(VisPluginData *plugin, VisEventQueue *events)
This is the signature for the event handler within libvisual plugins.
An event handler is not mandatory because it has no use in some plugin classes but some plugin types require it nonetheless.
plugin Pointer to the VisPluginData instance structure.
events Pointer to the VisEventQueue that might contain events that need to be handled.
Returns:
0 on succes -1 on error.
Definition at line 165 of file lv_plugin.h.
typedef const VisPluginInfo*(* VisPluginGetInfoFunc)(void)
This is the signature for the 'get_plugin_info' function every libvisual plugin needs to have.
The 'get_plugin_info' function provides libvisual plugin data and all the detailed information regarding the plugin. This function is compulsory without it libvisual won't load the plugin.
count An int pointer in which the number of VisPluginData entries within the plugin. Plugins can have multiple 'features' and thus the count is needed.
Returns:
Pointer to the VisPluginInfo array which contains information about the plugin.
Definition at line 132 of file lv_plugin.h.
typedef struct _VisPluginInfo VisPluginInfo
Definition at line 115 of file lv_plugin.h.
typedef int(* VisPluginInitFunc)(VisPluginData *plugin)
Every libvisual plugin that is loaded by the libvisual plugin loader needs this signature for it's intialize function.
plugin Pointer to the VisPluginData instance structure.
Returns:
0 on succes -1 on error.
Definition at line 144 of file lv_plugin.h.
typedef struct _VisPluginRef VisPluginRef
Definition at line 114 of file lv_plugin.h.
Enumeration Type Documentation
enum VisPluginFlags
Enumerate to define the plugin flags.
Plugin flags can be used to define some of the plugin it's behavior.
Enumerator:
VISUAL_PLUGIN_FLAG_NONE
Used to set no flags.
VISUAL_PLUGIN_FLAG_NOT_REENTRANT
Used to tell the plugin loader that this plugin is not reentrant, and can be loaded only once.
VISUAL_PLUGIN_FLAG_SPECIAL
Used to tell the plugin loader that this plugin has special purpose, like the GdkPixbuf plugin, or a webcam plugin.
Definition at line 88 of file lv_plugin.h.
enum VisPluginType
Enumerator:
VISUAL_PLUGIN_TYPE_ACTOR
VISUAL_PLUGIN_TYPE_INPUT
VISUAL_PLUGIN_TYPE_MORPH
VISUAL_PLUGIN_TYPE_TRANSFORM
Definition at line 107 of file lv_plugin.h.
enum VisPluginTypeDepth
Enumerate to check the depth of the type wildcard/defination used, used together with the visual_plugin_type functions.
Enumerator:
VISUAL_PLUGIN_TYPE_DEPTH_NONE
No type found.
VISUAL_PLUGIN_TYPE_DEPTH_DOMAIN
Only domain in type.
VISUAL_PLUGIN_TYPE_DEPTH_PACKAGE
Domain and package in type.
VISUAL_PLUGIN_TYPE_DEPTH_TYPE
Domain, package and type found in type.
Definition at line 100 of file lv_plugin.h.
Function Documentation
int visual_plugin_environ_add (VisPluginData * plugin, VisPluginEnviron * enve)
Adds a VisPluginEnviron to the plugin its environment list.
Parameters:
plugin Pointer to the VisPluginData to which the VisPluginEnviron is added.
enve Pointer to the VisPluginEnviron that is added to the VisPluginData.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_NULL, -VISUAL_ERROR_PLUGIN_ENVIRON_NULL, -VISUAL_ERROR_NULL or error values returned by visual_list_add() on failure.
Definition at line 752 of file lv_plugin.cpp.
Referenced by visual_actor_init().
VisObject* visual_plugin_environ_get (VisPluginData * plugin, const char * type)
Retrieves a VisPluginEnviron from the plugin it's environment list.
Parameters:
plugin Pointer to the VisPluginData from which the VisPluginEnviron is requested.
type The Environ type that is requested.
Returns:
The requested VisPluginEnviron it's environ specific VisObject, or NULL on failure
Definition at line 786 of file lv_plugin.cpp.
VisPluginEnviron* visual_plugin_environ_new (const char * type, VisObject * envobj)
Creates a VisPluginEnviron structure.
Parameters:
type The Environ type that is requested.
envobj The VisObject connected to this Environ type.
Returns:
A newly allocated VisPluginEnviron, or NULL on failure.
Definition at line 737 of file lv_plugin.cpp.
Referenced by visual_actor_init().
int visual_plugin_environ_remove (VisPluginData * plugin, const char * type)
Removes a VisPluginEnviron from the plugin it's environment list.
Parameters:
plugin Pointer to the VisPluginData from which the VisPluginEnviron is removed.
type The Environ type that is removed.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_NULL or -VISUAL_ERROR_NULL on failure.
Definition at line 763 of file lv_plugin.cpp.
Referenced by visual_plugin_environ_add().
int visual_plugin_events_pump (VisPluginData * plugin)
Pumps the queued events into the plugin it's event handler if it has one.
Parameters:
plugin Pointer to a VisPluginData of which the events need to be pumped into the handler.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_NULL or -VISUAL_ERROR_PLUGIN_NO_EVENT_HANDLER on failure.
Definition at line 227 of file lv_plugin.cpp.
Referenced by visual_actor_run(), visual_transform_run_palette(), visual_transform_run_video(), and visual_transform_video_negotiate().
int visual_plugin_get_api_version (void)
Gives the VISUAL_PLUGIN_API_VERSION value for which the library is compiled.
This can be used to check against for API/ABI compatibility check.
Returns:
The VISUAL_PLUGIN_API_VERSION define value.
Definition at line 566 of file lv_plugin.cpp.
VisEventQueue* visual_plugin_get_eventqueue (VisPluginData * plugin)
Gives the event queue from a VisPluginData.
This queue needs to be used when you want to send events to the plugin.
See also:
visual_plugin_events_pump
Parameters:
plugin Pointer to the VisPluginData from which we want the queue.
Returns:
A pointer to the requested VisEventQueue or NULL on failure.
Definition at line 240 of file lv_plugin.cpp.
Referenced by visual_actor_run().
VisPluginInfo* visual_plugin_get_info (VisPluginData * plugin)
Gives the VisPluginInfo related to a VisPluginData.
Parameters:
plugin The VisPluginData of which the VisPluginInfo is requested.
Returns:
The VisPluginInfo within the VisPluginData, or NULL on failure.
Definition at line 247 of file lv_plugin.cpp.
Referenced by visual_plugin_get_specific().
VisParamContainer* visual_plugin_get_params (VisPluginData * plugin)
Gives the VisParamContainer related to a VisPluginData.
Parameters:
plugin The VisPluginData of which the VisParamContainer is requested.
Returns:
The VisParamContainer within the VisPluginData, or NULL on failure.
Definition at line 254 of file lv_plugin.cpp.
Referenced by visual_plugin_realize().
VisRandomContext* visual_plugin_get_random_context (VisPluginData * plugin)
Gives the VisRandomContext related to a VisPluginData.
Parameters:
plugin The VisPluginData of which the VisRandomContext is requested.
Returns:
The VisRandomContext within the VisPluginDAta, or NULL on failure.
Definition at line 261 of file lv_plugin.cpp.
VisPluginRef* visual_plugin_get_reference (const char * pluginpath)
Private function to create VisPluginRefs from plugins.
Parameters:
pluginpath The full path and filename to the plugin of which a reference needs to be obtained.
Returns:
The newly allocated VisPluginRef for the plugin.
Definition at line 462 of file lv_plugin.cpp.
void* visual_plugin_get_specific (VisPluginData * plugin)
Retrieves the plugin specific part of a plugin.
Parameters:
plugin The pointer to the VisPluginData from which we want the plugin specific part.
Returns:
Void * pointing to the plugin specific part which can be cast.
Definition at line 268 of file lv_plugin.cpp.
int visual_plugin_info_copy (VisPluginInfo * dest, VisPluginInfo * src)
Copies data from one VisPluginInfo to another, this does not copy everything but only things that are needed in the local copy for the plugin registry.
Parameters:
dest Pointer to the destination VisPluginInfo in which some data is copied.
src Pointer to the source VisPluginInfo from which some data is copied.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_INFO_NULL on failure.
Definition at line 209 of file lv_plugin.cpp.
Referenced by visual_plugin_get_reference().
VisPluginInfo* visual_plugin_info_new (void)
Creates a new VisPluginInfo structure.
Returns:
A newly allocated VisPluginInfo
Definition at line 197 of file lv_plugin.cpp.
Referenced by visual_plugin_get_reference().
VisPluginData* visual_plugin_load (VisPluginRef * ref)
Private function to load a plugin.
Parameters:
ref Pointer to the VisPluginRef containing information about the plugin that needs to be loaded.
Returns:
A newly created and loaded VisPluginData.
Definition at line 352 of file lv_plugin.cpp.
Referenced by visual_actor_get_next_by_name_gl(), visual_actor_get_next_by_name_nogl(), visual_actor_get_prev_by_name_gl(), visual_actor_get_prev_by_name_nogl(), visual_actor_init(), visual_input_init(), visual_morph_init(), and visual_transform_init().
VisPluginData* visual_plugin_new (void)
Creates a new VisPluginData structure.
Returns:
A newly allocated VisPluginData.
Definition at line 292 of file lv_plugin.cpp.
Referenced by visual_plugin_load().
int visual_plugin_realize (VisPluginData * plugin)
Private function to realize the plugin.
This initializes the plugin.
Parameters:
plugin Pointer to the VisPluginData that needs to be realized.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_NULL or -VISUAL_ERROR_PLUGIN_ALREADY_REALIZED on failure.
Definition at line 442 of file lv_plugin.cpp.
Referenced by visual_actor_realize(), visual_input_realize(), visual_morph_realize(), and visual_transform_realize().
VisPluginRef* visual_plugin_ref_new (void)
Creates a new VisPluginRef structure.
The VisPluginRef contains data for the plugin loader.
Returns:
Newly allocated VisPluginRef.
Definition at line 280 of file lv_plugin.cpp.
Referenced by visual_plugin_get_reference().
VisPluginTypeDepth visual_plugin_type_get_depth (const char * type)
Get the depth of a plugin type string.
Parameters:
type The type string.
Returns:
A VisPluginTypeDepth enum value that describes out of how many parts this plugin type string consists, -VISUAL_ERROR_NULL on failure.
Definition at line 610 of file lv_plugin.cpp.
Referenced by visual_plugin_type_member_of().
const char* visual_plugin_type_get_domain (const char * type)
Get the domain part from a plugin type string.
Parameters:
type The type string.
Returns:
A newly allocated string containing the domain part of this plugin type, or NULL on failure.
Definition at line 571 of file lv_plugin.cpp.
const char* visual_plugin_type_get_flags (const char * type)
Retrieves the flags section from the plugin type string.
Parameters:
type The type string, containing the plugin type and optional flags.
return NULL if no flags are found, the flags between the '[' and ']' braces on succes. for example when the plugin type string is "Libvisual:core:actor.[special|something]" the returned flag string would be "special|something". Keep in mind that the string is allocated and should be freed after it's not being used anylonger.
Definition at line 681 of file lv_plugin.cpp.
Referenced by visual_plugin_type_has_flag().
const char* visual_plugin_type_get_package (const char * type)
Get the package part from a plugin type string.
Parameters:
type The type string.
Returns:
A newly allocated string containing the package part of this plugin type, or NULL on failure.
Definition at line 578 of file lv_plugin.cpp.
const char* visual_plugin_type_get_type (const char * type)
Get the type part from a plugin type string.
Parameters:
type The type string.
Returns:
A newly allocated string containing the type part of this plugin type, or NULL on failure.
Definition at line 585 of file lv_plugin.cpp.
int visual_plugin_type_has_flag (const char * type, const char * flag)
Checks if a certain flag is found within a plugin type string.
Parameters:
type The type string, containing the plugin type and optional flags.
flag The flag string to check for within the type string.
Returns:
TRUE in found, FALSE if not found, -VISUAL_ERROR_NULL on failure.
Definition at line 700 of file lv_plugin.cpp.
int visual_plugin_type_member_of (const char * domain, const char * type)
Check if a certain plugin type string falls within the domain of the other.
Parameters:
domain The domain in which the type string should fall.
type The type string that is checked against the given domain.
Returns:
TRUE if it falls within the domain, FALSE when not, -VISUAL_ERROR_NULL on failure
Definition at line 632 of file lv_plugin.cpp.
int visual_plugin_unload (VisPluginData * plugin)
Private function to unload a plugin.
After calling this function the given argument is no longer usable.
Parameters:
plugin Pointer to the VisPluginData that needs to be unloaded.
Returns:
VISUAL_OK on success, -VISUAL_ERROR_PLUGIN_NULL, -VISUAL_ERROR_PLUGIN_HANDLE_NULL or -VISUAL_ERROR_PLUGIN_REF_NULL on failure.
Definition at line 306 of file lv_plugin.cpp.
Referenced by visual_actor_get_next_by_name_gl(), visual_actor_get_next_by_name_nogl(), visual_actor_get_prev_by_name_gl(), and visual_actor_get_prev_by_name_nogl().