libvisual: VisConfig
VisConfig
Data Structures
struct _VisConfigRegistry
The VisConfigRegistry structure is the container for a complete config registry.
struct _VisConfigRegistrySection
The VisConfigRegistrySection structure is used as a section separator within VisConfigRegistry.
Defines
#define VISUAL_CONFIG_REGISTRY(obj) (VISUAL_CHECK_CAST ((obj), VisConfigRegistry))
#define VISUAL_CONFIG_REGISTRYSECTION(obj) (VISUAL_CHECK_CAST ((obj), VisConfigRegistrySection))
#define VISUAL_CONFIG_VERSION "LV CONFIG FILE 3"
Indicates at which version the config registry file format is.
Typedefs
typedef struct _VisConfigRegistry VisConfigRegistry
typedef struct
_VisConfigRegistrySection VisConfigRegistrySection
Functions
VisConfigRegistry * visual_config_registry_new (void)
VisConfigRegistry * visual_config_registry_open (const char *configfile)
VisConfigRegistrySection * visual_config_registry_find (VisConfigRegistry *registry, const char *name)
int visual_config_registry_remove (VisConfigRegistry *registry, const char *name)
int visual_config_registry_add (VisConfigRegistry *registry, VisConfigRegistrySection *rsection)
VisConfigRegistrySection * visual_config_registry_section_new (void)
VisConfigRegistrySection * visual_config_registry_section_open (const char *name, const char *configfile)
int visual_config_registry_write_by_data (VisConfigRegistry *registry, const char *name, const char *data, int datalength)
int visual_config_registry_write (VisConfigRegistry *registry, VisConfigRegistrySection *rsection)
int visual_config_registry_sync (VisConfigRegistry *registry)
Define Documentation
#define VISUAL_CONFIG_REGISTRY (obj) (VISUAL_CHECK_CAST ((obj), VisConfigRegistry))
Definition at line 38 of file lv_config.h.
#define VISUAL_CONFIG_REGISTRYSECTION (obj) (VISUAL_CHECK_CAST ((obj), VisConfigRegistrySection))
Definition at line 39 of file lv_config.h.
#define VISUAL_CONFIG_VERSION "LV CONFIG FILE 3"
Indicates at which version the config registry file format is.
Definition at line 44 of file lv_config.h.
Referenced by visual_config_registry_open().
Typedef Documentation
typedef struct _VisConfigRegistry VisConfigRegistry
Definition at line 46 of file lv_config.h.
typedef struct _VisConfigRegistrySection VisConfigRegistrySection
Definition at line 47 of file lv_config.h.
Function Documentation
int visual_config_registry_add (VisConfigRegistry * registry, VisConfigRegistrySection * rsection)
Definition at line 205 of file lv_config.c.
Referenced by visual_config_registry_open().
VisConfigRegistrySection* visual_config_registry_find (VisConfigRegistry * registry, const char * name)
Definition at line 170 of file lv_config.c.
Referenced by visual_config_registry_section_open().
VisConfigRegistry* visual_config_registry_new (void)
Definition at line 72 of file lv_config.c.
Referenced by visual_config_registry_open().
VisConfigRegistry* visual_config_registry_open (const char * configfile)
Definition at line 86 of file lv_config.c.
Referenced by visual_config_registry_section_open().
int visual_config_registry_remove (VisConfigRegistry * registry, const char * name)
Definition at line 185 of file lv_config.c.
VisConfigRegistrySection* visual_config_registry_section_new (void)
Definition at line 215 of file lv_config.c.
Referenced by visual_config_registry_open().
VisConfigRegistrySection* visual_config_registry_section_open (const char * name, const char * configfile)
Definition at line 227 of file lv_config.c.
int visual_config_registry_sync (VisConfigRegistry * registry)
Definition at line 260 of file lv_config.c.
int visual_config_registry_write (VisConfigRegistry * registry, VisConfigRegistrySection * rsection)
Definition at line 250 of file lv_config.c.
int visual_config_registry_write_by_data (VisConfigRegistry * registry, const char * name, const char * data, int datalength)
Definition at line 241 of file lv_config.c.
Referenced by visual_config_registry_write().