libvisual: lv_video_scale.h File Reference
lv_video_scale.h File Reference
#include "lv_video.h"
Functions
void visual_video_zoom_color8 (VisVideo *dest, VisVideo *src)
void visual_video_zoom_color16 (VisVideo *dest, VisVideo *src)
void visual_video_zoom_color24 (VisVideo *dest, VisVideo *src)
void visual_video_zoom_color32 (VisVideo *dest, VisVideo *src)
void visual_video_scale_nearest_color8 (VisVideo *dest, VisVideo *src)
void visual_video_scale_nearest_color16 (VisVideo *dest, VisVideo *src)
void visual_video_scale_nearest_color24 (VisVideo *dest, VisVideo *src)
void visual_video_scale_nearest_color32 (VisVideo *dest, VisVideo *src)
void visual_video_scale_bilinear_color8 (VisVideo *dest, VisVideo *src)
void visual_video_scale_bilinear_color16 (VisVideo *dest, VisVideo *src)
void visual_video_scale_bilinear_color24 (VisVideo *dest, VisVideo *src)
void visual_video_scale_bilinear_color32 (VisVideo *dest, VisVideo *src)
Function Documentation
void visual_video_scale_bilinear_color16 (VisVideo * dest, VisVideo * src)
Definition at line 251 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_bilinear_color24 (VisVideo * dest, VisVideo * src)
Definition at line 324 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_bilinear_color32 (VisVideo * dest, VisVideo * src)
Definition at line 397 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_bilinear_color8 (VisVideo * dest, VisVideo * src)
Definition at line 191 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_nearest_color16 (VisVideo * dest, VisVideo * src)
Definition at line 111 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_nearest_color24 (VisVideo * dest, VisVideo * src)
Definition at line 139 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_nearest_color32 (VisVideo * dest, VisVideo * src)
Definition at line 165 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_scale_nearest_color8 (VisVideo * dest, VisVideo * src)
Definition at line 85 of file lv_video_scale.c.
Referenced by visual_video_scale().
void visual_video_zoom_color16 (VisVideo * dest, VisVideo * src)
Definition at line 40 of file lv_video_scale.c.
Referenced by visual_video_zoom_double().
void visual_video_zoom_color24 (VisVideo * dest, VisVideo * src)
Definition at line 59 of file lv_video_scale.c.
Referenced by visual_video_zoom_double().
void visual_video_zoom_color32 (VisVideo * dest, VisVideo * src)
Definition at line 63 of file lv_video_scale.c.
Referenced by visual_video_zoom_double().
void visual_video_zoom_color8 (VisVideo * dest, VisVideo * src)
Definition at line 21 of file lv_video_scale.c.
Referenced by visual_video_zoom_double().