libvisual: lv_video_convert.c File Reference
lv_video_convert.c File Reference
#include "lv_video_convert.h"
#include "lv_common.h"
Data Structures
struct rgb16_t
Functions
void visual_video_convert_get_smallest (VisVideo *dest, VisVideo *src, int *width, int *height)
void visual_video_index8_to_rgb16 (VisVideo *dest, VisVideo *src)
void visual_video_index8_to_rgb24 (VisVideo *dest, VisVideo *src)
void visual_video_index8_to_argb32 (VisVideo *dest, VisVideo *src)
void visual_video_rgb16_to_index8 (VisVideo *dest, VisVideo *src)
void visual_video_rgb16_to_rgb24 (VisVideo *dest, VisVideo *src)
void visual_video_rgb16_to_argb32 (VisVideo *dest, VisVideo *src)
void visual_video_rgb24_to_index8 (VisVideo *dest, VisVideo *src)
void visual_video_rgb24_to_rgb16 (VisVideo *dest, VisVideo *src)
void visual_video_rgb24_to_argb32 (VisVideo *dest, VisVideo *src)
void visual_video_argb32_to_index8 (VisVideo *dest, VisVideo *src)
void visual_video_argb32_to_rgb16 (VisVideo *dest, VisVideo *src)
void visual_video_argb32_to_rgb24 (VisVideo *dest, VisVideo *src)
void visual_video_flip_pixel_bytes_color16 (VisVideo *dest, VisVideo *src)
void visual_video_flip_pixel_bytes_color24 (VisVideo *dest, VisVideo *src)
void visual_video_flip_pixel_bytes_color32 (VisVideo *dest, VisVideo *src)
Function Documentation
void visual_video_argb32_to_index8 (VisVideo * dest, VisVideo * src)
Definition at line 372 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_argb32_to_rgb16 (VisVideo * dest, VisVideo * src)
Definition at line 421 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_argb32_to_rgb24 (VisVideo * dest, VisVideo * src)
Definition at line 460 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_convert_get_smallest (VisVideo * dest, VisVideo * src, int * width, int * height)
Definition at line 16 of file lv_video_convert.c.
Referenced by visual_video_argb32_to_index8(), visual_video_argb32_to_rgb16(), visual_video_argb32_to_rgb24(), visual_video_index8_to_argb32(), visual_video_index8_to_rgb16(), visual_video_index8_to_rgb24(), visual_video_rgb16_to_argb32(), visual_video_rgb16_to_index8(), visual_video_rgb16_to_rgb24(), visual_video_rgb24_to_argb32(), visual_video_rgb24_to_index8(), and visual_video_rgb24_to_rgb16().
void visual_video_flip_pixel_bytes_color16 (VisVideo * dest, VisVideo * src)
Definition at line 497 of file lv_video_convert.c.
Referenced by visual_video_flip_pixel_bytes().
void visual_video_flip_pixel_bytes_color24 (VisVideo * dest, VisVideo * src)
Definition at line 519 of file lv_video_convert.c.
Referenced by visual_video_flip_pixel_bytes().
void visual_video_flip_pixel_bytes_color32 (VisVideo * dest, VisVideo * src)
Definition at line 542 of file lv_video_convert.c.
Referenced by visual_video_flip_pixel_bytes().
void visual_video_index8_to_argb32 (VisVideo * dest, VisVideo * src)
Definition at line 97 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_index8_to_rgb16 (VisVideo * dest, VisVideo * src)
Definition at line 22 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_index8_to_rgb24 (VisVideo * dest, VisVideo * src)
Definition at line 59 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb16_to_argb32 (VisVideo * dest, VisVideo * src)
Definition at line 214 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb16_to_index8 (VisVideo * dest, VisVideo * src)
Definition at line 136 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb16_to_rgb24 (VisVideo * dest, VisVideo * src)
Definition at line 178 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb24_to_argb32 (VisVideo * dest, VisVideo * src)
Definition at line 335 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb24_to_index8 (VisVideo * dest, VisVideo * src)
Definition at line 253 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().
void visual_video_rgb24_to_rgb16 (VisVideo * dest, VisVideo * src)
Definition at line 299 of file lv_video_convert.c.
Referenced by visual_video_depth_transform().