libvisual: lv_video_fill.h File Reference
lv_video_fill.h File Reference
#include "lv_video.h"
#include "lv_color.h"
Functions
void visual_video_fill_color_index8 (VisVideo *video, VisColor *color)
void visual_video_fill_color_rgb16 (VisVideo *video, VisColor *color)
void visual_video_fill_color_rgb24 (VisVideo *video, VisColor *color)
void visual_video_fill_color_argb32 (VisVideo *video, VisColor *color)
Function Documentation
void visual_video_fill_color_argb32 (VisVideo * video, VisColor * color)
Definition at line 90 of file lv_video_fill.c.
Referenced by visual_video_fill_color().
void visual_video_fill_color_index8 (VisVideo * video, VisColor * color)
Definition at line 18 of file lv_video_fill.c.
Referenced by visual_video_fill_color().
void visual_video_fill_color_rgb16 (VisVideo * video, VisColor * color)
Definition at line 31 of file lv_video_fill.c.
Referenced by visual_video_fill_color().
void visual_video_fill_color_rgb24 (VisVideo * video, VisColor * color)
Definition at line 48 of file lv_video_fill.c.
Referenced by visual_video_fill_color().