libvisual: lv_beat.c File Reference
lv_beat.c File Reference
#include "config.h"
#include "lv_beat.h"
#include "lv_common.h"
#include "lv_time.h"
#include "lv_util.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Defines
#define min(a, b) a < b ? a : b;
#define max(a, b) a > b ? a : b;
Functions
int beat_song_changed (VisBeat *beat)
void beat_insert_hist_step (VisBeat *beat, VisBeatType *t, clock_t TC, int type, int i)
void beat_double_beat (VisBeat *beat)
void beat_half_beat (VisBeat *beat)
int beat_TC_hist_step (VisBeat *beat, VisBeatType *t, int *_hdPos, clock_t TC, int type)
int beat_ready_to_learn (VisBeat *beat)
int beat_ready_to_guess (VisBeat *beat)
void beat_new_bpm (VisBeat *beat, int thisBpm)
int beat_get_bpm (VisBeat *beat)
void beat_calc_bpm (VisBeat *beat)
void beat_slider_step (VisBeat *beat, int Ctl, int *slide)
int beat_get_time_offset_since_start (VisBeat *beat, clock_t TC)
VisBeat * visual_beat_new ()
Create a new VisBeat.
int visual_beat_init (VisBeat *beat)
Initialize a VisBeat.
VisBeatAdv * visual_beat_adv_new ()
Create a VisBeat and initialize it.
int visual_beat_adv_init (VisBeatAdv *adv)
Initialize a VisBeatAdv.
int visual_beat_set_config (VisBeat *beat, int smartbeat, int smartbeatsticky, int smartbeatresetnewsong, int smartbeatonlysticky)
Set the configuration parameters for a VisBeat.
int visual_beat_set_smartbeat (VisBeat *beat, int smartbeat)
Set the smartbeat parameter for a VisBeat.
int visual_beat_set_smartbeat_sticky (VisBeat *beat, int smartbeatsticky)
int visual_beat_set_smartbeat_reset_on_newsong (VisBeat *beat, int smartbeatresetnewsong)
Set the smartbeat parameter for a VisBeat.
int visual_beat_set_smartbeat_only_sticky (VisBeat *beat, int smartbeatonlysticky)
Set the smartbeat parameter for a VisBeat.
int visual_beat_change_song (VisBeat *beat)
Signal that the song has changed.
char * visual_beat_get_info (VisBeat *beat)
Retrive a formatted string indicating current BPM and confidence.
int visual_beat_reset_adapt (VisBeat *beat)
Reset a VisBeat so that it may readapt.
int visual_beat_slider_get (VisBeat *beat, VisBeatSlider slider)
int visual_beat_refine_beat (VisBeat *beat, int isBeat)
Refine the beat indication through adaptive learning.
VisBeatPeak * visual_beat_get_peak (VisBeat *beat)
Retrieve the VisBeatPeak from a VisBeat.
VisBeatAdv * visual_beat_get_adv (VisBeat *beat)
Retrieve the VisBeatAdv from a VisBeat.
int visual_beat_adv_set_config (VisBeatAdv *adv, int sensitivity, int max_bpm, int thick_on_beats)
Set the configuration parameters for a VisBeatAdv.
int visual_beat_adv_set_sensitivity (VisBeatAdv *adv, int sensitivity)
Set the sensitivy parameter for a VisBeatAdv.
int visual_beat_adv_set_max_detect (VisBeatAdv *adv, int max_bpm)
Set the maximum BPM for a VisBeatAdv.
int visual_beat_adv_set_thick_on_beats (VisBeatAdv *adv, int thick_on_beats)
Set the thick on beats parameter for a VisBeatAdv.
Define Documentation
#define max (a, b) a > b ? a : b;
Definition at line 79 of file lv_beat.c.
Referenced by beat_calc_bpm().
#define min (a, b) a < b ? a : b;
Definition at line 78 of file lv_beat.c.
Referenced by beat_calc_bpm().
Function Documentation
void beat_calc_bpm (VisBeat * beat)
Definition at line 716 of file lv_beat.c.
Referenced by visual_beat_refine_beat().
void beat_double_beat (VisBeat * beat)
Definition at line 572 of file lv_beat.c.
Referenced by beat_calc_bpm().
int beat_get_bpm (VisBeat * beat)
Definition at line 696 of file lv_beat.c.
Referenced by beat_calc_bpm(), and visual_beat_refine_beat().
int beat_get_time_offset_since_start (VisBeat * beat, clock_t TC)
void beat_half_beat (VisBeat * beat)
Definition at line 596 of file lv_beat.c.
Referenced by beat_calc_bpm().
void beat_insert_hist_step (VisBeat * beat, VisBeatType * t, clock_t TC, int type, int i)
Definition at line 559 of file lv_beat.c.
Referenced by beat_TC_hist_step().
void beat_new_bpm (VisBeat * beat, int thisBpm)
Definition at line 688 of file lv_beat.c.
Referenced by beat_calc_bpm(), and visual_beat_refine_beat().
int beat_ready_to_guess (VisBeat * beat)
Definition at line 681 of file lv_beat.c.
Referenced by beat_calc_bpm().
int beat_ready_to_learn (VisBeat * beat)
Definition at line 669 of file lv_beat.c.
Referenced by beat_calc_bpm(), and beat_TC_hist_step().
void beat_slider_step (VisBeat * beat, int Ctl, int * slide)
Definition at line 842 of file lv_beat.c.
Referenced by visual_beat_refine_beat().
int beat_song_changed (VisBeat * beat)
Definition at line 545 of file lv_beat.c.
Referenced by visual_beat_refine_beat().
int beat_TC_hist_step (VisBeat * beat, VisBeatType * t, int * _hdPos, clock_t TC, int type)
Definition at line 622 of file lv_beat.c.
Referenced by visual_beat_refine_beat().