libvisual: lv_util.c File Reference
lv_util.c File Reference
#include "lv_util.h"
#include "lv_common.h"
#include <string.h>
Functions
char * visual_strdup (const char *str)
Function Documentation
char* visual_strdup (const char * str)
Definition at line 5 of file lv_util.c.
Referenced by visual_audio_samplepool_channel_init(), visual_beat_get_info(), visual_config_registry_open(), visual_param_container_add_with_defaults(), visual_param_entry_default_set_string(), visual_param_entry_set_annotation(), visual_param_entry_set_name(), visual_param_entry_set_string(), and visual_plugin_get_reference().