libvisual: lv_video_blit.h File Reference
lv_video_blit.h File Reference
#include "lv_video.h"
Functions
int blit_overlay_noalpha (VisVideo *dest, VisVideo *src)
int blit_overlay_alphasrc (VisVideo *dest, VisVideo *src)
int blit_overlay_colorkey (VisVideo *dest, VisVideo *src)
int blit_overlay_surfacealpha (VisVideo *dest, VisVideo *src)
int blit_overlay_surfacealphacolorkey (VisVideo *dest, VisVideo *src)
Function Documentation
int blit_overlay_alphasrc (VisVideo * dest, VisVideo * src)
Definition at line 42 of file lv_video_blit.c.
Referenced by visual_video_composite_get_function().
int blit_overlay_colorkey (VisVideo * dest, VisVideo * src)
Definition at line 71 of file lv_video_blit.c.
Referenced by visual_video_composite_get_function().
int blit_overlay_noalpha (VisVideo * dest, VisVideo * src)
Definition at line 18 of file lv_video_blit.c.
Referenced by blit_overlay_colorkey(), blit_overlay_surfacealphacolorkey(), and visual_video_composite_get_function().
int blit_overlay_surfacealpha (VisVideo * dest, VisVideo * src)
Definition at line 145 of file lv_video_blit.c.
Referenced by visual_video_composite_get_function().
int blit_overlay_surfacealphacolorkey (VisVideo * dest, VisVideo * src)
Definition at line 221 of file lv_video_blit.c.
Referenced by visual_video_composite_get_function().